repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        exclude: (^search/exports/2026-09-02/2026-09-02_pubmed_ABC_zotero_production\.(ris|bib)$|\.raw\.txt$)
      - id: check-added-large-files
        args: ['--maxkb=2000']
        exclude: ^search/exports/2026-09-02/2026-09-02_pubmed_ABC_zotero_production\.(ris|bib)$
      - id: detect-private-key
      - id: check-merge-conflict
