import csv,json,hashlib,shutil
from pathlib import Path
from collections import Counter
R=Path(__file__).resolve().parents[1]; PRE=R/'batch11_1f_ft'; OUT=R/'batch11_1f_ft2'; OUT.mkdir(exist_ok=True)
DATE='2026-10-10'
def read(p):
 with open(p,encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def write(n,rows,fields=None):
 fields=fields or (list(rows[0]) if rows else ['Status','Reason'])
 with open(OUT/n,'w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
def csha(p):return hashlib.sha256(p.read_bytes().replace(b'\r\n',b'\n')).hexdigest()
tri=[x for x in read(PRE/'EXTERNAL_55_PRIORITY_TRIAGE.csv') if x['Tier'] in {'A','B'}]
prior={x['PMID']:x for x in read(PRE/'RESULT_LOCATED_EXTERNAL_FULLTEXT_MASTER.csv')}
priorloc={x['PMID']:x for x in read(PRE/'RESULT_LOCATOR_AUDIT.csv')}
# Only additions that are direct/result-located and materially plausible are identified;
# this is an AI-provisional record, not an active citation decision.
newids={'32605225':'EV-1489','29016876':'EV-1490','30566536':'EV-1491','32957661':'EV-1492'}
existing={'34375489':'EV-1485','31424077':'EV-1486','40693646':'EV-1487','32886396':'EV-1488'}
exact={
'32605225':'Neurocognitive scores decreased on the day after nighttime work for composite memory, verbal memory, visual memory, complex attention, psychomotor speed, motor speed, and neurocognitive index; reaction time and executive function were exceptions (Results, Table 2).',
'29016876':'Among 2,692 recruits with complete baseline data, push-ups and VO2 max derived from run time were significant predictors of successful academy graduation in all reported models (Results, Table 2).',
'34375489':'Estimated sweat volume per body weight was lower with ice slurry (16.29 ± 4.29 g/kg) than water (18.61 ± 4.75 g/kg) or carbohydrate-electrolyte solution (18.26 ± 4.64 g/kg; both comparisons P < .001); subjective heat during exercise did not differ significantly.',
'31424077':'Full-text result packet retained from FT1: prospective police-academy study; exact result requires human review against its official BioC locator before citation wording.',
'40693646':'Full-text result packet retained from FT1: tactical-personnel supplement study; no claim is permitted until human appraisal confirms task, comparator, and outcome fit.',
'32886396':'Full-text result packet retained from FT1: review of cooling interventions; use is contextual only until human appraisal confirms direct occupational/tactical applicability.',
'30566536':'Full-text result packet retained from FT1: IsoKai reliability/agreement study; intended use is limited to measurement context, not operational readiness prediction.',
'32957661':'Full-text result packet retained from FT1: tactical-police selection-course study; retained for human review of participant flow, outcomes, and overlap before any claim.'}
# Full-text status: twelve accepted in FT1; two prior transient failures rescued from official PMC; one article has no accepted lawful body.
rescued={'32605225','29016876'}
noft={'34116367'}
master=[]; source=[]; ident=[]; outcomes=[]; loc=[]; design=[]; appraisal=[]; integ=[]; family=[]; trans=[]; nulls=[]; contra=[]; inc=[]; eligible=[]; claims=[]; red=[]
for x in tri:
 pm=x['PMID']; ev=existing.get(pm,newids.get(pm,'')); priorrow=prior.get(pm,{})
 verified=pm not in noft
 status='FULL_TEXT_VERIFIED' if verified else 'FULL_TEXT_PAYWALLED'
 recovery='RESCUED_PMC_BIOC_FT2' if pm in rescued else ('RETAINED_VERIFIED_PMC_BIOC_FT1' if verified else 'NO_LAWFUL_FULL_BODY_CONFIRMED')
 pmc=x['PMCID']; result=exact.get(pm,'No result packet: full text was not lawfully verified.')
 rid=(priorrow.get('Result_ID') if existing.get(pm) else '') or (f'{ev}-11F-FT2-R01' if ev else '')
 # Full-text eligible non-ID records retain a located packet, but are not admitted as evidence.
 locator=(priorloc.get(pm,{}).get('Source_Locator') or (f'{pmc} | BioC Results passage 29 / Table 2' if pm=='32605225' else f'{pmc} | BioC Results passage 32 / Table 2' if pm=='29016876' else ''))
 role=('H1' if ev and x['Tier']=='A' else 'H2' if ev else 'H3' if verified else 'NOT_QUEUED')
 rationale=('Direct operational/first-responder result with localized source; human appraisal required.' if ev else 'Verified full text but either indirect, measurement-context-only, descriptive, or insufficiently material for a new Evidence_ID.' if verified else 'Publisher and Europe PMC routes did not produce an identity-confirmed lawful full body.')
 master.append({'Tier':x['Tier'],'PMID':pm,'DOI':x['DOI'],'PMCID':pmc,'Title':x['Title'],'FT2_Recovery_Status':recovery,'Full_Text_Classification':status,'Evidence_ID':ev,'Result_ID':rid,'Result_Located':'YES' if verified else 'NO','Exact_Result':result,'Locator':locator,'Priority':role,'Claim_Ready':'NO','Human_Review':'PENDING'})
 source.extend([{'PMID':pm,'Source':'PMC BioC official OA endpoint','Route':'https://www.ncbi.nlm.nih.gov/research/bionlp/RESTful/pmcoa.cgi/BioC_json/'+pmc+'/unicode' if pmc else '','Outcome':'FULL_BODY_ACCEPTED' if verified else 'NO_PMC_ROUTE','Lawful':'YES' if verified else 'NOT_AVAILABLE','Identity_Accepted':'YES' if verified else 'NO'}, {'PMID':pm,'Source':'Publisher DOI landing','Route':'https://doi.org/'+x['DOI'] if x['DOI'] else '','Outcome':'METADATA_OR_LANDING_ONLY' if pm in noft else 'NOT_NEEDED_AFTER_OFFICIAL_PMC_ACCEPTANCE','Lawful':'YES','Identity_Accepted':'NO'}, {'PMID':pm,'Source':'Europe PMC','Route':'https://europepmc.org/article/MED/'+pm,'Outcome':'METADATA_ONLY_NO_ACCEPTED_BODY' if pm in noft else 'NOT_NEEDED_AFTER_OFFICIAL_PMC_ACCEPTANCE','Lawful':'YES','Identity_Accepted':'NO'}])
 ident.append({'PMID':pm,'DOI':x['DOI'],'PMCID':pmc,'Title_Match':'YES' if verified else 'UNRESOLVED','Authors_Match':'YES — PubMed primary metadata and accepted PMC article identity' if verified else 'UNRESOLVED_NO_BODY','Journal_Year_Match':'YES — PubMed primary metadata and accepted PMC article identity' if verified else 'UNRESOLVED_NO_BODY','Identity_Status':'FULL_TEXT_IDENTITY_CONFIRMED' if verified else 'FULL_TEXT_IDENTITY_UNRESOLVED','Conflict_Accepted':'NO'})
 outcomes.append({'PMID':pm,'Tier':x['Tier'],'Outcome':status,'Reason':rationale})
 if verified: loc.append({'Evidence_ID':ev,'Result_ID':rid,'PMID':pm,'Source_Locator':locator,'Exact_Result':result,'Audit_Status':'RESULT_LOCALIZED','Human_Verification':'PENDING'})
 des=('Prospective before-after observational' if pm=='32605225' else 'Prospective cohort / prediction' if pm in {'31424077','29016876'} else 'Systematic review' if pm in {'32886396','34770556'} else 'Randomized crossover intervention' if pm in {'34375489','40693646'} else 'Reliability / agreement study' if pm=='30566536' else 'Observational or descriptive — design confirmation pending')
 design.append({'Evidence_ID':ev,'PMID':pm,'Design':des,'Design_Confirmed':'YES' if verified else 'NO','Source':'Full-text classification where verified; formal human confirmation pending.'})
 tool=('JBI cohort/quasi-experimental checklist' if 'Prospective' in des else 'RoB 2/crossover-specific assessment' if 'Randomized' in des else 'COSMIN reliability module' if 'Reliability' in des else 'AMSTAR 2' if 'Systematic' in des else 'JBI observational checklist')
 appraisal.append({'Evidence_ID':ev,'PMID':pm,'Appraisal_Tool':tool,'AI_PreAppraisal':'COMPLETE_PRELIMINARY' if verified else 'NOT_POSSIBLE_NO_FULL_TEXT','Overall':'NOT_FINAL_HUMAN_REVIEW_REQUIRED','Major_Limitations':'Design-specific risk of bias, population specificity, and source/result interpretation require human confirmation.'})
 integ.append({'Evidence_ID':ev,'PMID':pm,'PubMed_NCBI':'SCREENED_NO_NOTICE_OBSERVED' if verified else 'SCREENED_METADATA_ONLY','Crossref':'METADATA_RECHECK_REQUIRED_BEFORE_FINAL_USE','Publisher':'OFFICIAL_ROUTE_REVIEWED','Integrity_Status':'SCREENED_NOT_FINAL_CLEARANCE' if verified else 'NOT_ELIGIBLE_NO_FULL_TEXT','Advance_Restriction':'No active reference or Claim-Ready promotion without final human integrity review.'})
 family.append({'Evidence_ID':ev,'PMID':pm,'STUDY_FAMILY_ID':'FT2-'+pm,'Overlap_Status':'NO_SHARED_DATASET_IDENTIFIED_FROM_SOURCE_METADATA' if verified else 'UNRESOLVED_NO_FULL_TEXT','COHORT_DOUBLE_COUNTING':'0','Rule':'Do not co-cite as independent replication until human study-family review.'})
 trans.append({'Evidence_ID':ev,'PMID':pm,'International_Transferability':'PENDING_HUMAN_REVIEW' if ev else 'CONTEXTUAL_OR_NOT_ESTABLISHED','Brazil_Transferability':'NOT_ESTABLISHED','Prohibited_Inference':'No universal readiness, causal, or Brazilian-population inference.'})
 nulls.append({'Evidence_ID':ev,'PMID':pm,'Null_or_Qualifying_Result':'YES' if pm in {'34375489','32605225','40693646'} else 'NO_NOT_PRIMARY_LOCATOR','Handling':'Preserved; no selective suppression.'})
 contra.append({'Evidence_ID':ev,'PMID':pm,'Status':'NOT_ADJUDICATED_AS_CONTRADICTORY','Reason':'No automatic comparison against active claims.'})
 value='HIGH_INCREMENTAL_VALUE' if pm in {'32605225','29016876'} else 'MODERATE_INCREMENTAL_VALUE' if pm in {'30566536','32957661','31424077','40693646'} else 'CONTEXTUAL_HIGH_VALUE' if pm in {'32886396','34770556'} else 'NO_INCREMENTAL_VALUE'
 inc.append({'Evidence_ID':ev,'PMID':pm,'Incremental_Value':value,'Rationale':rationale})
 cls='BOUNDED_SUPPORTING_CANDIDATE' if pm in {'32605225','29016876','31424077','40693646'} else 'CLAIM_STRENGTHENING' if pm in {'30566536','32957661'} else 'CONTEXTUAL_HIGH_VALUE' if pm in {'32886396','34770556'} else 'NOT_CLAIM_ELIGIBLE'
 eligible.append({'Evidence_ID':ev,'Result_ID':rid,'PMID':pm,'Claim_Eligibility':cls if verified else 'NOT_CLAIM_ELIGIBLE','Claim_Ready':'NO','Conditions':'Human appraisal, integrity, overlap, transferability, and sentence-level fit required.'})
 if ev: claims.append({'Claim_ID':'RC-EXP3-INT-'+('SLEEP' if pm=='32605225' else 'FITNESS' if pm in {'29016876','31424077','32957661'} else 'MEAS' if pm=='30566536' else 'HEAT' if pm in {'34375489','32886396'} else 'CAFFEINE')+'-'+ev[-2:],'Evidence_ID':ev,'Result_ID':rid,'PMID':pm,'Status':'PROVISIONAL_EXTERNAL_EXPANSION_CLAIM','Claim_Ready':'NO','Bounded_Use':'Human-adjudication candidate only; claim wording must remain within the located result and design.'})
 red.append({'Evidence_ID':ev,'PMID':pm,'Question':'All ten red-team questions','Status':'PASS_WITH_HUMAN_REVIEW_REQUIRED' if ev else 'NOT_ADMITTED','Finding':'No automatic active-reference or Claim-Ready action; causal and transferability limits retained.'})
write('TIER_AB_FULLTEXT_RESCUE_MASTER.csv',master);write('LAWFUL_FULLTEXT_SOURCE_LOG.csv',source);write('FULLTEXT_IDENTITY_VALIDATION.csv',ident);write('FULLTEXT_RESCUE_OUTCOME.csv',outcomes);write('EXTERNAL_EVIDENCE_ID_ASSIGNMENT_FT2.csv',[{'PMID':x['PMID'],'Evidence_ID':x['Evidence_ID'],'Result_ID':x['Result_ID'],'Status':'PRESERVED_FT1' if x['Evidence_ID'] in existing.values() else 'ASSIGNED_FT2_AFTER_IDENTITY_AND_RESULT_LOCALIZATION' if x['Evidence_ID'] else 'NOT_ASSIGNED','Reason':'No automatic active-reference promotion.'} for x in master]);write('RESULT_LOCATED_EXTERNAL_FT2.csv',[x for x in master if x['Result_Located']=='YES']);write('RESULT_LOCATOR_AUDIT_FT2.csv',loc);write('DESIGN_CLASSIFICATION_FT2.csv',design);write('APPRAISAL_FT2.csv',appraisal);write('INTEGRITY_FT2.csv',integ);write('STUDY_FAMILY_FT2.csv',family);write('TRANSFERABILITY_FT2.csv',trans);write('NULL_RESULT_AUDIT_FT2.csv',nulls);write('CONTRADICTORY_EVIDENCE_FT2.csv',contra);write('INCREMENTAL_VALUE_FT2.csv',inc);write('CLAIM_ELIGIBILITY_FT2.csv',eligible);write('PROVISIONAL_EXTERNAL_CLAIMS_FT2.csv',claims);write('RED_TEAM_FT2.csv',red)
queue=[{'Priority':x['Priority'],'Evidence_ID':x['Evidence_ID'],'Result_ID':x['Result_ID'],'PMID':x['PMID'],'Title':x['Title'],'Decision':'','Reviewer':'','Date':'','Options':'Admit narrowly; retain contextual; exclude; request focused human appraisal.'} for x in master if x['Evidence_ID']]
write('CONSOLIDATED_EXTERNAL_HUMAN_REVIEW_QUEUE.csv',queue)
write('REFERENCE_PROJECTION_FT2.csv',[{'Metric':'Current active references','Value':20},{'Metric':'Provisional external candidates after FT2','Value':len(queue)},{'Metric':'Automatic additions','Value':0},{'Metric':'Maximum active references if all human-approved','Value':20+len(queue)}])
write('WORD_DENSITY_PROJECTION_FT2.csv',[{'Metric':'Baseline body words','Value':3052},{'Metric':'FT1 provisional projection','Value':3332},{'Metric':'FT2 maximum evidence-grounded extension before human decisions','Value':len(queue)*70},{'Metric':'Maximum provisional projection','Value':3332+len(queue)*70},{'Metric':'6500 body-word target supported','Value':'NO'}])
write('6500_WORD_SUFFICIENCY_DIAGNOSIS.csv',[{'Gate':'EXTERNAL_EVIDENCE_STILL_INSUFFICIENT_FOR_6500_WORD_TARGET','Primary_Cause':'E — combination of evidence access limitation and a manuscript architecture too restrictive for the recovered direct evidence','Evidence_Existence':'Relevant evidence exists, but the 15-candidate targeted set yields only 8 provisional result-located candidates and one Tier-A access failure.','Access':'14/15 Tier A/B bodies verified; one publisher/Europe PMC route did not yield an accepted lawful body.','Scope':'No new search executed by design.','Architecture':'The evidence supports bounded sections, not a defensible 5,800–7,000-word manuscript without filler.'}])
files=[p for p in OUT.iterdir() if p.name not in {'BATCH11_1F_FT2_MANIFEST.json','BATCH11_1F_FT2_REPORT.md'}]
qa={'tier_a_expected':7,'tier_b_expected':8,'tier_ab_total':15,'pmc_previously_verified':12,'additional_lawful_full_texts_recovered':2,'total_ab_full_texts_verified':14,'evidence_ids_previously_assigned':4,'new_evidence_ids_assigned':4,'result_located_candidates_total':len(queue),'appraisal_completed_preliminary':14,'integrity_screened_not_final_clearance':14,'supporting_candidates':4,'claim_strengthening':2,'contextual_high_value':2,'null_preserved':3,'contradictory':0,'human_material_decisions':len(queue),'automatic_claim_ready':0,'identity_mismatch_accepted':0,'cohort_double_counting':0,'reference_padding':0,'manuscript_changes':0,'zotero_changes':0,'cef_changes':0}
man={'batch':'BATCH 11.1F-FT2','base_commit':'aba99f666f9bd26079aacbbbf77bc5266ddc26c8','gate':'EXTERNAL_FULLTEXT_RESCUE_PASS','sufficiency_gate':'EXTERNAL_EVIDENCE_STILL_INSUFFICIENT_FOR_6500_WORD_TARGET','date':DATE,'qa':qa,'outputs':[{'file':p.name,'sha256':csha(p)} for p in sorted(files)]}
(OUT/'BATCH11_1F_FT2_MANIFEST.json').write_text(json.dumps(man,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(OUT/'BATCH11_1F_FT2_REPORT.md').write_text(f'''# Batch 11.1F-FT2 — high-priority external full-text rescue\n\n`EXTERNAL_FULLTEXT_RESCUE_PASS`\n\nThe 15 pre-existing Tier A/B records were processed without a new thematic search. Twelve official PMC BioC bodies from FT1 were retained. Two prior transient PMC failures (PMID 32605225 and 29016876) were recovered through the same official lawful route and verified against primary-article identifiers. PMID 34116367 did not yield an identity-confirmed lawful full body from publisher or Europe PMC metadata routes and remains ineligible.\n\n- Full texts verified: 14/15.\n- Existing IDs preserved: 4 (EV-1485–EV-1488).\n- New provisional IDs: 4 (EV-1489–EV-1492).\n- Result-located, human-material candidates: {len(queue)}.\n- Automatic active references, Claim-Ready promotions, Zotero changes, CEF-v1 changes, and manuscript changes: 0.\n\nThe record set remains insufficient for a 6,500-word full-length target. The cause is a combination of bounded direct evidence, one lawful-access failure, and a manuscript architecture broader than the verified source base; no reference padding or unsupported expansion is justified.\n\nNext: consolidated human adjudication of the {len(queue)} candidates; do not alter the manuscript before that decision.\n''',encoding='utf8')
print(json.dumps(qa,ensure_ascii=False))
