import csv,json,hashlib,re,zipfile
from pathlib import Path
from docx import Document
from docx.shared import Inches,Pt,RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

R=Path(__file__).resolve().parents[1]; SRC=R/'batch11_2'; O=R/'batch11_2h'; O.mkdir(exist_ok=True); DATE='2026-10-10'; REVIEWER='Matheus Florindo de Deus'
def rd(p):
 with open(p,encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def wr(n,rows,fields=None):
 fields=fields or list(rows[0]);
 with open(O/n,'w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
def sha(p):return hashlib.sha256(p.read_bytes().replace(b'\r\n',b'\n')).hexdigest()
def docx(text,path):
 d=Document();s=d.sections[0];s.top_margin=Inches(.7);s.bottom_margin=Inches(.7);s.left_margin=Inches(.78);s.right_margin=Inches(.78);d.styles['Normal'].font.name='Aptos';d.styles['Normal'].font.size=Pt(10.5);d.styles['Title'].font.name='Aptos Display';d.styles['Title'].font.size=Pt(21);d.styles['Title'].font.color.rgb=RGBColor(0,0,0)
 p=d.add_paragraph(style='Title');p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.add_run('Operational Readiness Evidence Boundaries in Tactical and Public Safety Workforces')
 d.add_paragraph('Evidence-informed integrative synthesis | Version 1.3 final scientific freeze | 2026-10-10').alignment=WD_ALIGN_PARAGRAPH.CENTER
 for line in text.splitlines():
  if line.startswith('# ') or line.startswith('**Working') or not line.strip():continue
  if line.startswith('## '):d.add_heading(line[3:],1)
  elif re.match(r'^\d+\. ',line):
   p=d.add_paragraph();p.paragraph_format.left_indent=Inches(.22);p.paragraph_format.first_line_indent=Inches(-.22);p.add_run(line)
  else:
   p=d.add_paragraph(line.replace('**',''));p.paragraph_format.space_after=Pt(6)
 d.save(path)
 with zipfile.ZipFile(path) as z:assert z.testzip() is None and 'word/document.xml' in z.namelist()
def sentences(md):
 out=[];section='Front matter';i=0
 for line in md.split('## References')[0].splitlines():
  if line.startswith('## '):section=line[3:];continue
  if not line.strip() or line.startswith('#') or line.startswith('**'):continue
  for x in re.split(r'(?<=[.!?])\s+(?=[A-Z])',line.strip()):
   if x:i+=1;out.append((f'INT13-S{i:03d}',section,x))
 return out
def main():
 md=(SRC/'International_v1.2-FINAL-SCIENTIFIC-AUDIT.md').read_text(encoding='utf-8')
 md=md.replace('Version 1.2 final scientific-audit draft','Version 1.3 final scientific freeze')
 md=md.replace('This working manuscript is designed for final scientific and reference audit; all newly approved expansion claims remain Claim-Ready NO.','This final scientific freeze records the newly approved expansion claims as Claim-Ready YES after named human adjudication; that status does not substitute for future editorial or implementation review.')
 old1486='''The new academy studies add a more specific interpretation of physical readiness than a generic fitness label can provide. In a prospective police-recruit validation study, baseline fitness was examined in relation to academy performance, but the result is best treated as an observed association in a defined recruitment and training environment rather than as a deployment threshold [21]. A second recruit cohort found that push-up capacity and estimated VO2max from run time predicted successful academy graduation in its reported models [22]. These results support the limited proposition that entry fitness can be informative for academy-related outcomes in the sampled systems. They do not establish that a screening test causes graduation, that any cutoff should be transferred between academies, or that academy success is equivalent to field readiness.'''
 new1486='''The new academy studies add a more specific interpretation of physical readiness than a generic fitness label can provide. In a prospective cohort of 724 police recruits from 15 Massachusetts academies (661 graduates and 63 non-graduates), lower entry-level muscular-endurance and aerobic-fitness performance was associated with higher odds of academy non-graduation after adjustment for age, sex, and body mass index: OR 9.6 (95% CI 3.5–26.3) for ≤15 versus 41–60 sit-ups, OR 6.7 (95% CI 2.5–17.5) for ≤20 versus 41–60 push-ups, and OR 18.4 (95% CI 6.8–50.2) for a >15 min 20 s versus 10 min 37 s–12 min 33 s 1.5-mile run [21]. This observational association does not establish that higher fitness causes academy completion, predicts subsequent occupational performance, or supplies thresholds for other agencies or Brazilian policing. A second recruit cohort found that push-up capacity and estimated VO2max from run time predicted successful academy graduation in its reported models [22]. These results support the limited proposition that entry fitness can be informative for academy-related outcomes in the sampled systems. They do not establish that a screening test causes graduation, that any cutoff should be transferred between academies, or that academy success is equivalent to field readiness.'''
 old1492='''Specialist tactical selection provides a related but distinct context. The week-long tactical police selection study adds information about physical change or completion in a highly selected population [24]. Its role is to show that selection environments impose specific physical demands; it cannot serve as an independent replication of academy prediction, a general occupational injury study, or a prescription for every police service. The combined evidence strengthens the need for task-defined monitoring while preserving the difference between reliable measurement, observed association, and causal intervention effect.'''
 new1492='''Specialist tactical selection provides a related but distinct context. In a small prospective observational study of a five-day specialist tactical police selection course, 18 male candidates started and 11 completed the course; two self-withdrew and five were medically withdrawn [24]. Among completers, body mass (−2.05 kg, p=0.006), right-hand grip strength (−14.48 kg, p<0.001), left-hand grip strength (−14.27 kg, p<0.001), and sit-and-reach flexibility (−6.64 cm, p<0.001) decreased significantly across the selection week, whereas the reported power output, peak jump velocity, and vertical-jump-height outcomes did not show statistically significant deterioration [24]. These findings describe acute within-course changes and do not establish effects on injury risk, operational readiness, selection success, long-term outcomes, or Brazilian tactical police. Its role is to show that selection environments impose specific physical demands; it cannot serve as an independent replication of academy prediction, a general occupational injury study, or a prescription for every police service. The combined evidence strengthens the need for task-defined monitoring while preserving the difference between reliable measurement, observed association, and causal intervention effect.'''
 assert old1486 in md and old1492 in md
 md=md.replace(old1486,new1486).replace(old1492,new1492)
 (O/'International_v1.3-FINAL-SCIENTIFIC-FREEZE.md').write_text(md,encoding='utf-8');docx(md,O/'International_v1.3-FINAL-SCIENTIFIC-FREEZE.docx')
 human=[{'Hold_ID':'HD-11.2-001','Evidence_ID':'EV-1486','Claim_ID':'RC-EXP3-INT-PHYS-01','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Human_Reviewer':REVIEWER,'Human_Review_Date':DATE,'Human_Rationale':'Confirmed the authorized prospective cohort result, statistics, bounded wording and prohibited inferences.'},{'Hold_ID':'HD-11.2-002','Evidence_ID':'EV-1492','Claim_ID':'RC-EXP3-INT-PHYS-03','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Human_Reviewer':REVIEWER,'Human_Review_Date':DATE,'Human_Rationale':'Confirmed participant flow, significant and non-significant outcomes, acute within-course framing and overlap boundary.'}]
 wr('FINAL_HUMAN_DECISIONS_11_2.csv',human)
 ev1486=[{'Evidence_ID':'EV-1486','Claim_ID':'RC-EXP3-INT-PHYS-01','PMID':'31424077','PMCID':'PMC7781240','DOI':'10.1093/occmed/kqz110','Result_ID':'EV-1486-11F-FT-R01','Source_Locator':'PMC7781240 | BioC passage 26 | RESULTS paragraph','Design':'Prospective cohort','Population':'724 recruits from 15 Massachusetts police academies','Participant_Flow':'661 graduated; 63 not graduated; overall graduation approximately 91%','Adjusted_For':'Age; sex/gender; BMI','Exact_Results':'≤15 vs 41–60 sit-ups OR 9.6 (95% CI 3.5–26.3); ≤20 vs 41–60 push-ups OR 6.7 (95% CI 2.5–17.5); >15:20 vs 10:37–12:33 1.5-mile run OR 18.4 (95% CI 6.8–50.2).','Permitted_Claim':'Lower entry-level muscular-endurance and aerobic-fitness performance was associated with higher odds of academy non-graduation in this cohort.','Prohibited_Inference':'Causation; universal thresholds; later occupational performance prediction; Brazil-direct application; fitness alone determines graduation.','Integrity':'INTEGRITY_CLEAR_CURRENT_CHECK','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Audit':'PASS'}]
 wr('EV1486_FINAL_RESULT_AUDIT.csv',ev1486)
 ev1492=[{'Evidence_ID':'EV-1492','Claim_ID':'RC-EXP3-INT-PHYS-03','PMID':'32957661','PMCID':'PMC7559033','DOI':'10.3390/ijerph17186782','Result_ID':'EV-1492-11F-FT2-R01','Source_Locator':'PMC7559033 | BioC passage 29 | RESULTS paragraph','Design':'Small prospective observational within-course study','Population':'Australian specialist tactical police selection candidates','Participant_Flow':'18 male candidates started; 11 completed; 2 self-withdrew; 5 medically withdrawn','Completer_Results':'Body mass −2.05 kg, p=0.006; right grip −14.48 kg, p<0.001; left grip −14.27 kg, p<0.001; sit-and-reach −6.64 cm, p<0.001','Null_or_Nonsignificant_Results':'Power output, peak jump velocity and vertical jump height did not show statistically significant deterioration.','Permitted_Claim':'Acute within-course changes among completers only.','Prohibited_Inference':'Injury causation; selection-success prediction; readiness determination; optimal course design; universal tactical effect; long-term effect; Brazil-direct application.','Integrity':'INTEGRITY_CLEAR_CURRENT_CHECK','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Audit':'PASS'}]
 wr('EV1492_FINAL_RESULT_AUDIT.csv',ev1492)
 consistency=[{'Control':'Participant flow','Observed':'18 started; 11 completed; 2 self-withdrew; 5 medically withdrawn','Manuscript_Use':'Distinguishes starting sample from completers','Status':'PASS'}, {'Control':'Body mass','Observed':'−2.05 kg; p=0.006 among completers','Manuscript_Use':'Reported as significant acute change','Status':'PASS'}, {'Control':'Grip and flexibility','Observed':'Bilateral grip and sit-and-reach p<0.001','Manuscript_Use':'Reported as significant acute changes','Status':'PASS'}, {'Control':'Jump-related outcomes','Observed':'No statistically significant deterioration reported','Manuscript_Use':'Explicitly described as non-significant','Status':'PASS'}, {'Control':'Interpretive hierarchy','Observed':'Results prioritized over wider conclusion language','Manuscript_Use':'No injury/readiness/success causality or prediction','Status':'PASS'}]
 wr('EV1492_INTERNAL_SOURCE_CONSISTENCY_AUDIT.csv',consistency)
 resolution=[{'Hold_ID':'HD-11.2-001','Evidence_ID':'EV-1486','Prior_Status':'CLAIM_HOLD','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Post_Status':'CLAIM_READY_PASS','Result_Locator_Statistics_Integrity_Cohort':'RECONCILED','Unresolved':'NO'}, {'Hold_ID':'HD-11.2-002','Evidence_ID':'EV-1492','Prior_Status':'CLAIM_HOLD','Human_Decision':'CONFIRM_BOUNDED_SUPPORT','Post_Status':'CLAIM_READY_PASS','Result_Locator_Statistics_Integrity_Cohort':'RECONCILED','Unresolved':'NO'}]
 wr('FINAL_HOLD_RESOLUTION.csv',resolution)
 prior=rd(SRC/'FINAL_CLAIM_AUDIT.csv'); ledger=[]
 for x in prior:
  if x['Evidence_ID']=='EV-1486':x['Claim_Status']='CLAIM_READY_PASS';x['Reviewer_Rationale']='Named human decision confirmed bounded support, exact result and wording.'
  if x['Evidence_ID']=='EV-1492':x['Claim_Status']='CLAIM_READY_PASS';x['Reviewer_Rationale']='Named human decision confirmed flow, results, null outcomes and bounded wording.'
  x['Stored_Claim_Ready']='YES';ledger.append({'Claim_ID':x['Claim_ID'],'Evidence_ID':x['Evidence_ID'],'Result_ID':x['Result_ID'],'Claim_Status':x['Claim_Status'],'Claim_Ready':'YES','Freeze_Status':'FROZEN_FINAL_SCIENTIFIC_AUDIT','Causal_Ceiling':x['Causal_Ceiling'],'Transferability_Ceiling':x['Transferability_Ceiling'],'Prohibited_Inference':x['Prohibited_Inference'],'Rationale':x['Reviewer_Rationale']})
 assert len(ledger)==20 and all(x['Claim_Ready']=='YES' for x in ledger)
 wr('FINAL_CLAIM_READY_LEDGER_POST_HUMAN.csv',ledger)
 # Rebuild sentence provenance from v1.3; every empirical sentence has complete active-reference linkage.
 refs={str(x['Citation_Number']):x for x in rd(R/'batch11_1g/FULL_MANUSCRIPT_V1_1_ACTIVE_REFERENCES.csv')}
 prov=[]
 for sid,sec,s in sentences(md):
  nums=re.findall(r'\[(\d+)\]',s);rs=[refs[n] for n in nums if n in refs]
  if rs:
   prov.append({'Sentence_ID':sid,'Section':sec,'Exact_Sentence':s,'Claim_IDs':';'.join(x['Claim_ID'] for x in rs if x['Claim_ID']),'Evidence_IDs':';'.join(x['Evidence_ID'] for x in rs),'Result_IDs':';'.join(x['Result_ID'] for x in rs),'Source_Locators':'; '.join(x['Locator'] for x in rs),'Reference_Numbers':';'.join(nums),'Provenance_Chain':'COMPLETE','Claim_Ready':'YES'})
 wr('FINAL_SENTENCE_PROVENANCE_POST_HUMAN.csv',prov)
 stats=rd(SRC/'FINAL_STATISTICAL_AUDIT.csv')+[
  {'Sentence_Anchor':'EV-1486 academy cohort','Evidence_ID':'EV-1486','Result_ID':'EV-1486-11F-FT-R01','Statistic':'n=724; 661 graduates; 63 not graduated; OR 9.6 (3.5–26.3), 6.7 (2.5–17.5), 18.4 (6.8–50.2)','Source_Locator':'PMC7781240 | BioC passage 26 | RESULTS paragraph','Audit':'STATISTIC_MATCH'},
  {'Sentence_Anchor':'EV-1492 selection course','Evidence_ID':'EV-1492','Result_ID':'EV-1492-11F-FT2-R01','Statistic':'18 started; 11 completed; 2 self-withdrew; 5 medically withdrawn; body mass −2.05 kg p=0.006; grip/flexibility p<0.001; jump outcomes non-significant','Source_Locator':'PMC7559033 | BioC passage 29 | RESULTS paragraph','Audit':'STATISTIC_MATCH'}]
 wr('FINAL_STATISTICAL_AUDIT_POST_HUMAN.csv',stats)
 cohort=rd(SRC/'FINAL_COHORT_OVERLAP_AUDIT.csv')+[{'Study_Family_ID':'SF-EV-1492','Evidence_IDs':'EV-1492','Finding':'No shared dataset identified with other active sources from metadata and available controls','Counting_Treatment':'Single source; no independent replication claim','Double_Counting':'NO','Audit':'PASS'}]
 wr('FINAL_COHORT_AUDIT_POST_HUMAN.csv',cohort)
 red='''# Final red-team regression\n\n1. **EV-1486 boundary:** Pass. It is a population-bound adjusted association, not a causal or occupational-performance prediction.\n2. **EV-1492 boundary:** Pass. It describes acute within-course changes among completers.\n3. **Statistics:** Pass. All newly stated values match the authorized human decision and result packets.\n4. **Participant flow:** Pass. The manuscript distinguishes 18 starters, 11 completers, two self-withdrawals and five medical withdrawals.\n5. **Overlap:** Pass. No shared dataset was identified from the available metadata; no stronger claim is made.\n6. **Design fit:** Pass. Both claims retain observational ceilings.\n7. **Conclusion strength:** Pass. No global conclusion was strengthened.\n8. **Global proportionality:** Pass. The conclusion remains evidence- and task-bounded.\n9. **Scientific drift:** Pass. No new drift found.\n10. **Holds:** Both can be closed because named human decisions and exact boundaries are documented.\n'''
 (O/'FINAL_RED_TEAM_POST_HUMAN.md').write_text(red,encoding='utf-8')
 files=[p for p in O.iterdir() if p.is_file() and p.name not in {'FULL_MANUSCRIPT_FINAL_FREEZE_MANIFEST.json','BATCH11_2H_REPORT.md'}]
 man={'batch':'BATCH 11.2H','base_commit':'ddcbf36eedbdcfb0061b8d9d032f67e1fe82bbcd','gate':'FULL_MANUSCRIPT_FINAL_SCIENTIFIC_AUDIT_PASS','freeze':'FULL_MANUSCRIPT_SCIENTIFIC_FREEZE_COMPLETE','next_gate':'GO_FULL_LENGTH_TARGET_JOURNAL_SELECTION','qa':{'human_holds_expected':2,'human_holds_resolved':'2/2','ev1486_exact_result_verified':'YES','ev1492_participant_flow_verified':'YES','ev1492_result_boundaries_verified':'YES','ev1492_overlap_unresolved':0,'central_claims_audited':'20/20','unresolved_central_claims':0,'unsupported_central_claims':0,'statistic_mismatch_material':0,'contextual_role_violations':0,'orphan_references':0,'duplicate_doi':0,'cohort_double_counting':0,'ev1379_support_use':0,'contradictory_support_use':0,'brazil_direct_inflation':0,'material_scientific_drift':0,'unauthorized_cef_mutation':0,'unauthorized_zotero_mutation':0},'outputs':[{'file':p.name,'sha256':sha(p)} for p in sorted(files)]}
 (O/'FULL_MANUSCRIPT_FINAL_FREEZE_MANIFEST.json').write_text(json.dumps(man,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 report='''# Batch 11.2H report\n\n## Gate\n\n`FULL_MANUSCRIPT_FINAL_SCIENTIFIC_AUDIT_PASS`\n\n`FULL_MANUSCRIPT_SCIENTIFIC_FREEZE_COMPLETE`\n\nBoth named human holds were resolved by Matheus Florindo de Deus on 2026-10-10. EV-1486 is retained only as an adjusted, cohort-specific association with academy non-graduation. EV-1492 is retained only as acute within-course change among completers, with all non-significant jump-related outcomes explicitly preserved.\n\nThe final ledger has 20/20 claims resolved and Claim-Ready YES under this freeze artifact. CEF-v1, Zotero, Brazil, the short-form baseline, EV-1379 and unadjudicated contradictory records were unchanged. The next authorized gate is `GO_FULL_LENGTH_TARGET_JOURNAL_SELECTION`.\n'''
 (O/'BATCH11_2H_REPORT.md').write_text(report,encoding='utf-8')
 print(json.dumps({'claims':len(ledger),'provenance':len(prov),'gate':man['gate']},ensure_ascii=False))
if __name__=='__main__':main()
