"""BATCH 10.4H-RP: records technical recovery failure without regenerating scientific artifacts."""
import csv, hashlib, json, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'batch10_4h_rp'; OUT.mkdir(exist_ok=True)
EXPECTED=['International_v0.15-B2-EVIDENCE-FIRST.docx','Brazil_v0.15-B2-EVIDENCE-FIRST.docx','V015_B2_CLAIM_CITATION_MATRIX.csv','V015_B2_SENTENCE_PROVENANCE.csv','V015_B2_WORKING_REFERENCE_SET.csv','V015_B2_RESULT_ID_USE_AUDIT.csv','V015_B2_NULL_RESULT_AUDIT.csv','V015_B2_COHORT_OVERLAP_AUDIT.csv','V015_B2_TRANSFERABILITY_AUDIT.csv','V015_B2_PROTECTED_CLAIM_AUDIT.csv','V015_B2_FRAMEWORK_AUDIT.csv','V015_B2_ABSTRACT_BODY_COHERENCE.csv','V015_B2_CONCLUSION_COHERENCE.csv','V015_B2_REFERENCE_USE_AUDIT.csv','V015_B2_MANUSCRIPT_VIABILITY.csv','V015_B2_HUMAN_REVIEW_QUEUE.csv','BATCH10_4H_R_MANIFEST.json','BATCH10_4H_R_REPORT.md']
def main():
 rows=[]
 for name in EXPECTED:
  rows.append({'Filename':name,'Expected_Source':'Authoritative local batch10_4h_r/, validated delivery ZIP, reachable Git history, or retained Git object','Source_Location':'NOT_FOUND_AFTER_TARGETED_LOCAL_AND_GIT_OBJECT_RECOVERY','Repository_Destination':f'batch10_4h_r/{name}','Size_Bytes':'','SHA256':'','Restoration_Status':'NOT_RESTORED','Issue':'No original artifact or validated package available; regeneration prohibited by BATCH 10.4H-RP scope.','Recovery_Status':'BLOCKED_NEEDS_ORIGINAL_PACKAGE'})
 with (OUT/'BATCH10_4H_R_RESTORATION_LEDGER.csv').open('w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 report='''# BATCH 10.4H-RP — restoration and publication of the authoritative v0.15 B2 package\n\n## Gate\n\n`V015_B2_AUTHORITATIVE_PACKAGE_RESTORATION_BLOCKED`\n\n## Recovery probes\n\nThe following authorized technical sources were checked without reconstructing scientific content:\n\n1. Current checkout: `batch10_4h_r/` absent.\n2. Current tracked Git tree: no files under `batch10_4h_r/`.\n3. Reachable local and remote refs: no history for the required path.\n4. Unreachable local Git commits, trees and text blobs: no matching path or manifest/package metadata.\n5. Local Codex workspace, attachments and ZIP inventory: no validated delivery package or original artifact.\n\n## Result\n\nAll 18 required artifacts remain missing. No destination directory was populated with regenerated manuscripts, CSVs or manifests because doing so would fabricate the prior validated v0.15 B2 package. The restoration ledger lists each expected filename and the exact recovery status.\n\n## Exact unblock\n\nSupply or restore the original validated `batch10_4h_r/` directory or delivery ZIP with its original manifest/hashes. This batch can then copy the originals, validate DOCX/CSV/JSON/Markdown integrity and publish them without changing science.\n'''
 (OUT/'BATCH10_4H_RP_REPORT.md').write_text(report,encoding='utf-8')
 fs=[OUT/'BATCH10_4H_R_RESTORATION_LEDGER.csv',OUT/'BATCH10_4H_RP_REPORT.md']
 m={'batch':'BATCH 10.4H-RP','base_commit':'7f1dfbf2880c9db1aba75fd68a880f2a2d38ceee','gate':'V015_B2_AUTHORITATIVE_PACKAGE_RESTORATION_BLOCKED','expected_artifacts':18,'restored_artifacts':0,'missing_artifacts':18,'corrupted_artifacts':0,'manifest_hash_mismatches':0,'original_manifest_available':False,'recovery_sources_checked':['current checkout','current Git tree','reachable Git refs','unreachable local Git objects','Codex workspace/attachments/ZIP inventory'],'unauthorized_scientific_changes':0,'Zotero_changes':0,'CEF_v1_changes':0,'v015_scientific_changes':0,'next_action':'Provide original authoritative batch10_4h_r directory or validated delivery ZIP; do not regenerate.', 'artifact_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in fs}}
 (OUT/'BATCH10_4H_R_RESTORATION_MANIFEST.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__':main()
