import csv,json,hashlib,re,zipfile
from pathlib import Path
from docx import Document
from docx.shared import Inches,Pt,RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT,WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

R=Path(__file__).resolve().parents[1]; O=R/'batch11_1'; O.mkdir(exist_ok=True); D='2026-10-10'
def rows(p):
 with open(p,encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def wc(n,fs,rs):
 with open(O/n,'w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fs);w.writeheader();w.writerows(rs)
def hs(p):
 h=hashlib.sha256();
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def cell(c,t,b=False):
 c.text='';p=c.paragraphs[0];r=p.add_run(t);r.bold=b;r.font.size=Pt(8);c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def shade(c,x):
 p=c._tc.get_or_add_tcPr();e=OxmlElement('w:shd');e.set(qn('w:fill'),x);p.append(e)
def main():
 frozen=rows(R/'batch10_4k'/'INTERNATIONAL_FINAL_REFERENCE_SET.csv'); claims=rows(R/'batch11_0c'/'HUMAN_APPROVED_EXPANSION_CLAIM_LIBRARY.csv'); dec={x['Evidence_ID']:x for x in rows(R/'batch11_0c'/'HUMAN_EXPANSION_DECISIONS_FINAL.csv')}; ctx=rows(R/'batch11_0c'/'HUMAN_APPROVED_CONTEXTUAL_EVIDENCE.csv'); integ={x['Evidence_ID']:x for x in rows(R/'batch11_0d'/'EXTERNAL_INTEGRITY_RECHECK_26.csv')}; ident={x['Evidence_ID']:x for x in rows(R/'batch11_0d'/'IDENTITY_VERIFICATION_26.csv')}
 active=[]
 for x in frozen:active.append(dict(Evidence_ID=x['Evidence_ID'],Result_ID=x['Result_IDs'],Claim_ID=x['Claim_IDs_Supported'],Role='FROZEN_BOUNDARY_SUPPORT',Title=x['Title'],DOI=x['DOI'],Authors=x['Authors'],Year=x['Year'],Journal=x['Journal_or_Source'],Locator=x['Source_Locators'],Use='Central bounded claim'))
 for x in claims:
  d=dec[x['Evidence_ID']];i=ident.get(x['Evidence_ID'],{});active.append(dict(Evidence_ID=x['Evidence_ID'],Result_ID=x['Result_ID'],Claim_ID=x['Claim_ID'],Role='HUMAN_APPROVED_EXPANSION_CLAIM_PENDING_FINAL_SCIENTIFIC_AUDIT',Title=d['Title'],DOI=integ[x['Evidence_ID']]['DOI'],Authors=i.get('Authors_From_PubMed','NR — NOT REPORTED'),Year=i.get('Publication_Year','NR — NOT REPORTED'),Journal=i.get('Journal','NR — NOT REPORTED'),Locator='Result packet '+x['Result_ID'],Use='Bounded supporting claim; Claim-Ready NO'))
 for x in ctx:
  if x['Evidence_ID'] in ['EV-0386','EV-1458','EV-0167','EV-0252']:
   d=dec[x['Evidence_ID']];i=ident.get(x['Evidence_ID'],{});active.append(dict(Evidence_ID=x['Evidence_ID'],Result_ID=x['Result_ID'],Claim_ID='',Role='CONTEXTUAL_DISCUSSION_ONLY',Title=d['Title'],DOI=integ[x['Evidence_ID']]['DOI'],Authors=i.get('Authors_From_PubMed','NR — NOT REPORTED'),Year=i.get('Publication_Year','NR — NOT REPORTED'),Journal=i.get('Journal','NR — NOT REPORTED'),Locator='Result packet '+x['Result_ID'],Use='Discussion only; never central claim'))
 for n,x in enumerate(active,1):x['Citation_Number']=n
 wc('FULL_MANUSCRIPT_ACTIVE_REFERENCES.csv',list(active[0]),active); nums={x['Evidence_ID']:x['Citation_Number'] for x in active}
 frozen_text={'RC-INT-SLEEP-01':'Acute caffeine may partially mitigate selected sleep-loss-related decrements in studied military settings; it does not restore sleep, substitute for recovery, or establish benefit for every operational task.','RC-BRA-CVD-01':'In the sampled PMDF cohort of male officers older than 40 years, measured cardiometabolic risk burden supported consideration of surveillance; the cross-sectional study did not identify confirmed role or shift differences.','RC-BRA-SHOOT-01':'In one small police-cadet comparison, shooting score, time, and accuracy coefficient did not differ significantly by the reported stress-symptom grouping.','RC-BRA-SHOOT-02':'In the overlapping police-cadet cohort, the displayed physical-activity and several fitness measures did not show statistically significant correlations with shooting outcomes.'}
 cm=[]
 for x in frozen:
  cid=x['Claim_IDs_Supported'];cm.append(dict(Claim_ID=cid,Claim_Type='FROZEN_CLAIM',Evidence_ID=x['Evidence_ID'],Result_ID=x['Result_IDs'],Section='Results',Revised_Claim=frozen_text[cid],Citation_Number=nums[x['Evidence_ID']],Evidence_Role='BOUNDED_SOURCE_LOCATED',Directness='As documented',Saturation_Status='FROZEN_BASELINE',Limitation='Exact prior boundary preserved.',Final_Wording_Rationale='No wording expansion beyond frozen v0.16 boundary.',Claim_Ready='NO'))
 for x in claims:
  cm.append(dict(Claim_ID=x['Claim_ID'],Claim_Type='HUMAN_APPROVED_EXPANSION_CLAIM',Evidence_ID=x['Evidence_ID'],Result_ID=x['Result_ID'],Section='Results or Discussion',Revised_Claim=x['Human_Approved_Wording'],Citation_Number=nums[x['Evidence_ID']],Evidence_Role='BOUNDED_SUPPORTING_PENDING_FINAL_SCIENTIFIC_AUDIT',Directness=x['Transferability'],Saturation_Status='EXPANSION_CONDITIONAL',Limitation=x['Prohibited_Inference'],Final_Wording_Rationale='Human decision recorded; Claim-Ready remains NO.',Claim_Ready='NO'))
 wc('FULL_MANUSCRIPT_CLAIM_TO_TEXT_MATRIX.csv',list(cm[0]),cm)
 title='Operational Readiness Evidence Boundaries in Tactical and Public Safety Workforces'
 abstract='Operational readiness is often discussed as if it were a unitary and readily measurable attribute. This evidence-informed integrative synthesis instead examines the boundaries of selected evidence across tactical, military, fire-service, and public-safety settings. We used the project fixed evidence universe, result-located extraction packets, design-matched appraisal, an external integrity recheck, and recorded human role decisions to construct a working full manuscript. The active evidence supports bounded statements about sleep-loss mitigation, cardiometabolic surveillance, task-specific performance null findings, measurement properties, injury-risk associations, implementation constraints, and feasibility. It does not validate a global readiness score, establish universal occupational thresholds, or support causal claims from observational or feasibility designs. The resulting framework is a proposed synthesis framework and has not been validated. This working manuscript is designed for final scientific and reference audit; all newly approved expansion claims remain Claim-Ready NO.'
 S={
'Introduction':['Operational readiness is a practical decision problem rather than a single biological construct. It is influenced by the task, setting, personnel, resources, and consequences of error; evidence from one occupational context cannot automatically supply a threshold or intervention rule for another.','This manuscript asks a narrower question: what can result-located studies in selected tactical and public-safety populations support about readiness-related assessment, surveillance, task performance, and implementation, and what do they not permit an organization to infer?','The purpose is an evidence-informed integrative synthesis with explicit boundaries. It is not a systematic review, scoping review, meta-analysis, validated model, or operational protocol.'],
'Methods':['Evidence identification and governance. We used the project versioned evidence universe and did not conduct a new literature search for this reconstruction. Candidate sources entered the working manuscript only after an Evidence ID, Result ID, source locator, appraisal record, integrity record, and documented role decision were available in project ledgers.','Evidence treatment. The manuscript distinguishes bounded supporting evidence from contextual discussion evidence. A source could inform interpretation without becoming a central claim anchor. Results reported as null or non-significant were retained when they materially constrained a proposed inference.','Integrity and traceability. The 26 human-adjudicated records underwent a documented PubMed and Crossref identity and integrity recheck on 2026-10-10. The recheck found 26 identity-confirmed records and no indexed retraction, expression of concern, withdrawal, or correction affecting their recorded use. This is a time-stamped screening result, not a permanent integrity guarantee.','Appraisal and transferability. Each retained result preserves its original study-design limits. Measurement-property studies do not become outcome-prediction studies, feasibility studies do not become effectiveness studies, and cross-sectional associations do not become causal effects. Brazilian transferability is not inferred from foreign tactical samples.','Cohort handling. Potential overlap is treated as a design issue. The two Brazilian police-cadet firearm studies are presented as overlapping rather than as independent replications. The controlled test item FXC7ZY9R is excluded from evidence and was not used.'],
'Results':[
f'Sleep loss and recovery boundaries. In a systematic review and meta-analysis of military studies, acute caffeine partially mitigated selected vigilance, cognition, and military-task decrements associated with sleep loss, while not resolving sleep loss or establishing benefit for every task [{nums["EV-1462"]}]. This bounded result supports conditional mitigation discussion, not a replacement for recovery planning.',
f'A separate implementation study reported that 270 participants used a sleep telehealth platform with app and wearable monitoring and that implementation outcomes were mapped to RE-AIM with mixed stakeholder data [{nums["EV-0183"]}]. It contributes feasibility context rather than operational-readiness or comparative clinical benefit.',
f'A law-enforcement systematic review and meta-analysis is retained as review-level, provisional sleep and work-stress context [{nums["EV-1461"]}]. Its presence does not establish a causal or Brazil-specific readiness claim.',
f'Medical and cardiometabolic readiness boundaries. In the sampled PMDF cohort of male officers older than 40 years, measured cardiometabolic risk burden supported consideration of surveillance; the cross-sectional study did not identify confirmed role or shift differences [{nums["EV-1463"]}]. This result is population-specific and cannot establish that a role, shift, or surveillance program causes a cardiovascular outcome.',
f'In a prospective military cohort, cardiorespiratory fitness was evaluated in relation to physiological responses and dropout during a loaded long-distance march [{nums["EV-0734"]}]. The study does not supply a universal fitness threshold for operational readiness.',
f'A firefighter crossover study found no statistically or clinically significant cardiometabolic or fire-ground performance effect from four weeks of astaxanthin; most inflammatory changes were within treatment groups [{nums["EV-0386"]}]. This null result is retained to prevent a supplementation efficacy inference.',
f'Task-specific assessment and performance. In a Slovenian infantry sample, end-running speed, maximal heart rate, and predicted VO2max from the 30-15 intermittent fitness test had test-retest ICCs of .971, .960, and .975, respectively, and the authors reported validity and usefulness against treadmill and 2-mile run measures [{nums["EV-0667"]}]. The finding supports measurement properties in that sample, not validation for Brazilian policing, combat readiness, or outcome prediction.',
f'In a prospective police-recruit cohort, each one-point composite-fitness increase was associated with lower injury hazard (HR 0.89, 95% CI 0.83–0.95) and with a BARS association (beta 0.21, 95% CI 0.12–0.30) [{nums["EV-0204"]}]. The association does not prove that testing, assignment, or conditioning causes lower injury or better operational performance.',
f'In a military training cohort of 1,407 trainees assessed before and after eight weeks, DXA and circumference data were collected for body-composition comparison [{nums["EV-0586"]}]. This is measurement-comparison evidence rather than evidence that a particular monitoring method improves readiness.',
f'A firefighter Tactical Athlete Resilience Program reported feasibility outcomes, not definitive effectiveness [{nums["EV-0670"]}]. A separate firefighter pilot investigation reported training outcomes but requires replication and controlled effectiveness testing [{nums["EV-0960"]}]. Neither study establishes a definitive operational-performance program effect.',
f'A retrospective tactical-athlete cohort reported associations of sex, military occupation, and rank with anterior cruciate ligament injury risk [{nums["EV-0721"]}]. A cross-sectional study of Swedish soldiers reported occupational exposure and musculoskeletal-complaint associations [{nums["EV-1026"]}]. These data do not establish causal workload effects or prevention efficacy.',
f'In one small Brazilian police-cadet comparison, shooting score, time, and accuracy coefficient did not differ significantly by reported stress-symptom grouping [{nums["EV-1473"]}]. In the overlapping police-cadet cohort, displayed physical-activity and several fitness measures did not show statistically significant correlations with shooting outcomes [{nums["EV-1474"]}]. These null findings constrain any claim that a global stress, activity, or fitness construct predicts firearm performance in this context.',
f'Tactical medicine and implementation context. Interviews with Swedish tactical police medics identified constraints on civilian care, inconsistent healthcare cooperation, and ethical and operational dilemmas [{nums["EV-0103"]}]. The qualitative result describes context; it does not measure patient outcomes, validate training duration, or justify a specific Brazilian scope-of-practice policy.',
f'Police recruits, staff, clinicians, and research experts generated, sorted, and rated injury-prevention priorities; eight broad priority areas emerged from 48 participants [{nums["EV-0068"]}]. Participatory priority-setting does not show that a mapped strategy prevents injury or transfers unchanged to another academy.',
f'Contextual implementation evidence is subordinate to central claims. In two Arizona departments, adjusted probability of rating an AI-generated body-camera review platform appropriate was 21.7 percentage points higher in the feedback department, while feasibility was not significant [{nums["EV-0167"]}]. A convenience-sampled survey of 72 police leaders described complexity, limited tailoring, and low trust of external implementers [{nums["EV-0252"]}]. These observations do not establish organizational effectiveness or generalize to Brazil.'],
'Discussion':['The active evidence supports an evidence-bound view of readiness. The available studies are heterogeneous in population, exposure, outcome, and design, so readiness should not be represented as a single universal score or as a collection of interchangeable proxies.','First, measurement and surveillance need separate justifications. A reproducible fitness measure can be useful within a documented population without establishing an occupational cutoff or predicting task outcomes. Similarly, cross-sectional cardiometabolic burden can motivate consideration of surveillance without identifying causal role, shift, or intervention effects.','Second, task specificity matters. The Brazilian firearm studies provide useful negative constraints: neither reported stress-symptom grouping nor several displayed fitness and activity measures showed significant associations with recorded shooting outcomes. They should not be converted into proof that those factors never matter, but they make global prediction claims indefensible for the recorded context.','Third, intervention language must track design. Feasibility studies establish whether a program can be implemented or studied under stated conditions; they do not by themselves establish effectiveness. Observational injury associations may help target future investigation but cannot demonstrate that modifying one observed factor will prevent injuries.','Fourth, operational systems have implementation constraints. Police-medic interviews and implementation-context studies identify organizational, ethical, and coordination issues that can shape adoption. These studies are useful for questions to ask when transferring an intervention; they are not evidence that a particular policy will produce an outcome in a different jurisdiction.','The framework presented here is therefore a PROPOSED SYNTHESIS FRAMEWORK — NOT YET VALIDATED. It organizes four linked questions: what task and outcome are considered; what source-located evidence bears directly on that question; what design and transferability limits apply; and what decision remains appropriate after uncertainty is explicit. It does not generate scores, prescribe thresholds, or replace clinical, occupational, or command judgment.','Transferability is limited where evidence comes from a single military, police, firefighter, or national system. Brazilian studies add direct context for selected cardiometabolic and firearm-performance boundaries, but they do not validate the framework for Brazilian public safety as a whole. International evidence should be adapted only after local task, regulation, population, and implementation conditions are assessed.'],
'Limitations':['This is an evidence-informed integrative synthesis, not a systematic review, scoping review, or meta-analysis. Selection is constrained by the project pre-existing versioned evidence universe and by result-located extraction packets.','Full-text access and detailed appraisal were not uniform across the wider universe. The external integrity recheck was current at the stated date but cannot rule out future notices or information not indexed by queried sources. Newly retained expansion claims have human role decisions but remain Claim-Ready NO pending final scientific and reference audit.','Several findings are observational, cross-sectional, feasibility-oriented, qualitative, or measurement-specific. Causal inference, universal readiness thresholds, claims of intervention effectiveness, and generalization across countries are outside this manuscript evidentiary scope.','Potentially contradictory records EV-0052, EV-0140, and EV-1066 remain unadjudicated and are not used as support. Integrity-blocked EV-1379 is not used. These protections reduce the risk of converting access or adjudication gaps into positive evidence.'],
'Conclusion':['Selected evidence can inform a cautious, task-specific approach to operational readiness. It supports bounded interpretation of selected measurement, surveillance, performance, feasibility, and implementation findings; it does not validate a global readiness construct or a universal program of assessment and intervention.','The immediate use of this manuscript is as a traceable working synthesis for final scientific and reference audit. Prospective, task-defined, locally governed research is still required before the proposed framework can be evaluated as an operational model.']}
 S['Introduction'].extend([
  'A readiness decision is commonly made at the point where a local organization must decide whether to assess, monitor, train, modify work, or defer a decision. Those actions require different evidence. A monitoring decision can be justified by burden and feasibility, whereas a performance threshold requires a demonstrated relation to a defined task outcome. Conflating these uses is a route to avoidable overclaim.',
  'The distinction matters in tactical and public-safety work because roles differ materially in exposure, equipment, training history, medical access, deployment duration, and legal authority. A result from a recruit academy, firefighter program, infantry unit, or specialized police service may be useful as an analogue, but analogue evidence is not automatically direct evidence for another workforce.',
  'This working reconstruction is deliberately evidence-first. It begins with localized study results and their constraints, then builds only the claims that those results can support. The aim is to make uncertainty visible to readers and to preserve the audit trail needed for later scientific and editorial review.'
 ])
 S['Methods'].extend([
  'The governing unit of evidence was not a title, abstract, or thematic similarity. It was the chain Evidence ID to Result ID to source locator to bounded claim. A source without a sufficiently located result could remain in the project history, but it could not be promoted as a central manuscript anchor. This rule was intended to prevent a broad topic label from substituting for a verified empirical finding.',
  'Human adjudication determined the permitted role of the expansion candidates. That decision did not convert them into Claim-Ready evidence. The operational distinction is preserved throughout the manuscript: a documented human role decision authorizes bounded working use, while final claim readiness requires the later scientific and reference audit.',
  'The external integrity check used PubMed and Crossref identity and notice information. An absence of an indexed notice was recorded as a current screening finding rather than a claim of permanent integrity. This approach also avoids treating a resolver or publisher automation failure as proof of either a problem or a clean record.',
  'No quantitative pooling was performed. The studies use different designs, outcomes, comparison structures, populations, and settings. The synthesis therefore reports patterns of bounded support, null findings, and limitations rather than a combined effect estimate or rank order of interventions.',
  'The manuscript was constructed after the project had formally retained a limited International frozen reference baseline. The baseline wording was preserved where it supplied a direct, result-located boundary. The subsequent expansion adds only sources with recorded human decisions and does not change the frozen CEF-v1 or the underlying Zotero library.'
 ])
 S['Results'].extend([
  f'Body-composition information must also be separated from performance claims. The 1,407-trainee military dataset supports comparison of DXA and circumference-based assessments within basic combat training [{nums["EV-0586"]}]. It does not show that a body-composition measure is a global proxy for operational readiness, that a screening threshold should be adopted, or that a classification changes mission performance.',
  f'The combined injury and physical-performance evidence illustrates why a single fitness narrative is not warranted. The prospective recruit association [{nums["EV-0204"]}] differs in outcome and causal structure from the firefighter feasibility and pilot studies [{nums["EV-0670"]}, {nums["EV-0960"]}], the retrospective ACL-risk associations [{nums["EV-0721"]}], and the cross-sectional Swedish complaint findings [{nums["EV-1026"]}]. Together they support a research and surveillance agenda; they do not establish a shared intervention package or deployment rule.',
  f'Equipment and task context can further change interpretation. A contextual systematic review of body armour described increased workload, lower work capacity, slower functional-task completion, impaired balance or stability, and higher perceived exertion across 16 studies, while marksmanship and some physiological effects remained uncertain [{nums["EV-1458"]}]. This evidence is used only to explain why task-specific outcomes should be specified rather than presumed.',
  f'The firearm results should be read as informative null findings rather than proof of equivalence. The small police-cadet study did not detect differences by the recorded stress-symptom grouping [{nums["EV-1473"]}], and the overlapping cohort did not show significant correlations between several displayed activity or fitness variables and shooting outcomes [{nums["EV-1474"]}]. Limited samples, outcome selection, and overlap mean that the result narrows the proposed claim but cannot settle the wider question of shooting performance determinants.',
  f'Tactical medical readiness is similarly bounded by the available outcome. The Swedish interview study documents how care coordination, civilian-service interfaces, and ethical tensions can be experienced by tactical police medics [{nums["EV-0103"]}]. It is valuable for implementation questions, but it does not provide comparative patient outcomes, a training-effect estimate, or a transferable policy prescription.',
  f'Injury prevention planning may be participatory before it is evaluative. The concept-mapping work with 48 participants identifies priorities created by recruits, police staff, health professionals, and researchers [{nums["EV-0068"]}]. It can inform the content of a local co-design discussion, but no prevention effect is implied by the existence or rating of a priority area.'
 ])
 S['Discussion'].extend([
  'Readiness assessment should therefore begin with the decision being contemplated. If the decision concerns medical surveillance, the relevant evidence concerns burden, risk detection, and the consequences of missed disease. If it concerns a specific task, the relevant evidence must include a task outcome. If it concerns an intervention, the relevant evidence must distinguish feasibility, uptake, fidelity, comparative effectiveness, and safety. A measure that is useful in one of these roles cannot be assumed to meet all of them.',
  'The sleep findings offer a practical example of bounded use. Caffeine may partially mitigate selected decrements under the reviewed military conditions, but it does not restore sleep or replace recovery. A sleep platform may be implementable for a mixed population, but implementation mapping does not establish a readiness benefit. The appropriate organizational conclusion is to define the intended outcome and evaluate local feasibility, safety, and equity rather than to treat either finding as a universal solution.',
  'The cardiometabolic findings likewise support caution. The PMDF study describes risk burden in a specific older male officer cohort, and the march study evaluates a specific military task. These results can justify questions about surveillance and task demands; they cannot justify treating occupation, work shift, or cardiorespiratory fitness as a universal determinant of readiness. The astaxanthin null result reinforces the need to avoid treating a supplement as an occupational-performance intervention without adequate evidence.',
  'The physical and musculoskeletal domain remains a collection of heterogeneous signals. A test-retest ICC addresses repeatability and a comparison with reference tests; a prospective association addresses observed relationships over time; a feasibility study addresses implementation; and a cross-sectional complaint study addresses co-occurrence. The evidence has value only when its design and outcome remain visible in the resulting claim.',
  'The implementation studies also show why evidence transfer requires organizational specification. Feedback may improve an appropriateness rating in one pair of departments while feasibility remains non-significant. Senior personnel may report complexity, low tailoring, and trust concerns in a convenience sample. Such results do not prove that an innovation will work or fail elsewhere, but they make implementation assumptions auditable and encourage a pre-specified local evaluation.',
  'The proposed framework is deliberately modest. It is intended to discipline a synthesis by asking whether the task, claim, evidence, design, and transferability match. It is not a screening instrument, clinical decision rule, certification standard, or substitute for local governance. A prospective study would be required to determine whether use of the framework improves decision quality, safety, equity, or operational outcomes.',
  'For readers working in Brazil, the manuscript provides selected direct Brazilian observations and a transferability warning rather than an imported program. The PMDF cardiometabolic cohort and the police-cadet firearm studies demonstrate that locally generated evidence can identify both observed burdens and null associations. They do not supply national estimates, causal mechanisms, or a validated readiness model for Brazilian public safety institutions.',
  'The most defensible next research steps are task-defined and prospective. They should specify the population, operational task, outcome, measurement method, follow-up, adverse events, implementation conditions, and how a null result will be interpreted. They should also report whether cohorts overlap with previous studies so that apparent evidence density is not created by repeated analyses of the same personnel.'
 ])
 S['Limitations'].extend([
  'The manuscript uses 20 active working references because each has a defined role in a sentence or domain discussion. This is not a claim that the topic is saturated. References were not retained to meet a numerical target, and contextual studies are explicitly separated from central claim anchors.',
  'The broader project retains records that were not used here, including protocol-only records, sources without a sufficiently located result, and sources with unresolved contradictory status. Their exclusion from this manuscript should not be interpreted as scientific refutation. It reflects the evidence threshold chosen for a traceable working reconstruction.'
 ])
 S['Conclusion'].extend([
  'The central contribution is therefore methodological as well as substantive: evidence should be used at the level of the result it reports, the design it used, and the task it studied. This approach leaves some questions unanswered, but it avoids presenting incomplete access, thematic similarity, or a local association as a universal readiness claim.'
 ])
 md=['# '+title,'','**Working manuscript.** Evidence-informed integrative synthesis. Version 1.0 working draft; prepared '+D+'.','','## Abstract','',abstract,'','**Keywords:** operational readiness; tactical athletes; public safety; evidence synthesis; implementation; transferability',''];prov=[]; sid=0
 def provenance(sec,t):
  nonlocal sid
  for z in re.split(r'(?<=[.!?])\s+(?=[A-Z])',t):
   if not z:continue
   sid+=1;ns=re.findall(r'\[(\d+)\]',z); aa=[active[int(n)-1] for n in ns];prov.append(dict(Sentence_ID=f'INT11-S{sid:03d}',Manuscript='International_v1.0',Section=sec,Exact_Sentence=z,Material_Scientific_Sentence='YES' if ns else 'NO',Evidence_IDs=';'.join(a['Evidence_ID'] for a in aa),Result_IDs=';'.join(a['Result_ID'] for a in aa),Reference_Numbers=';'.join(ns),Source_Locator='; '.join(a['Locator'] for a in aa) if aa else 'Project governance / methods ledger',Support_Status='SOURCE_LOCATED' if aa else 'PROJECT_GOVERNANCE',Claim_Ready='NO',Human_Final_Review='PENDING'))
 for sec,ps in S.items():
  md+=['## '+sec,'']
  for p in ps:md += [p,''];provenance(sec,p)
 md+=['## References','']
 for a in active:md.append(f"{a['Citation_Number']}. {a['Authors']}. {a['Title']}. {a['Journal']} ({a['Year']}). doi:{a['DOI'] or 'not indexed in PubMed'}.")
 (O/'International_v1.0-FULL-MANUSCRIPT-WORKING.md').write_text('\n'.join(md)+'\n',encoding='utf-8');wc('SENTENCE_LEVEL_PROVENANCE.csv',list(prov[0]),prov)
 chars=[]
 for a in active:
  d=dec.get(a['Evidence_ID'],{});chars.append(dict(Citation_Number=a['Citation_Number'],Evidence_ID=a['Evidence_ID'],Result_ID=a['Result_ID'],Title=a['Title'],Domain=d.get('Domain','frozen baseline'),Population=d.get('Population','As documented in prior freeze'),Sample=d.get('Sample','NR — NOT REPORTED'),Design=d.get('Design','As documented in prior freeze'),Exact_Result=d.get('Exact_Result','Frozen claim ledger'),Role=a['Role'],Transferability=d.get('Transferability','Limited as documented'),Integrity_Status=integ.get(a['Evidence_ID'],{}).get('Final_Integrity_Status','FROZEN_TECHNICAL_RECONCILIATION')))
 wc('FULL_MANUSCRIPT_STUDY_CHARACTERISTICS.csv',list(chars[0]),chars)
 domains=[]
 for n,ids in [('Sleep and recovery',['EV-1462','EV-0183','EV-1461']),('Medical and cardiometabolic',['EV-1463','EV-0734','EV-0386']),('Measurement physical and musculoskeletal',['EV-0667','EV-0204','EV-0586','EV-0670','EV-0960','EV-0721','EV-1026']),('Task specific firearm performance',['EV-1473','EV-1474']),('Tactical medicine and implementation',['EV-0103','EV-0068','EV-0167','EV-0252'])]:domains.append(dict(Domain=n,Active_Evidence_IDs=';'.join(ids),Core_Claim_Count=sum(c['Evidence_ID'] in ids for c in cm),Contextual_Count=sum(a['Evidence_ID'] in ids and a['Role']=='CONTEXTUAL_DISCUSSION_ONLY' for a in active),Synthesis='Bounded and design-specific; no universal threshold or causal program conclusion.',Certainty_Ceiling='SOME_CONCERNS / design-specific',Status='WORKING_SYNTHESIS_PENDING_FINAL_SCIENTIFIC_AUDIT'))
 wc('FULL_MANUSCRIPT_DOMAIN_SYNTHESIS.csv',list(domains[0]),domains)
 null=[]
 frozen_null={'EV-1473':('EV-1473-R02','Shooting score, time, and accuracy coefficient did not differ significantly by reported stress-symptom grouping.'),'EV-1474':('EV-1474-R02','Displayed physical-activity and several fitness measures did not show statistically significant correlations with shooting outcomes.')}
 for e in ['EV-0386','EV-1473','EV-1474','EV-0167']:
  x=next((x for x in ctx if x['Evidence_ID']==e),None) or dec.get(e)
  rid,res=(x['Result_ID'],x['Exact_Result']) if x else frozen_null[e]
  null.append(dict(Evidence_ID=e,Result_ID=rid,Null_Result='YES',Exact_Result=res,Manuscript_Use='Retained as a boundary or discussion constraint',Suppression='NO'))
 wc('FULL_MANUSCRIPT_NULL_RESULT_AUDIT.csv',list(null[0]),null)
 cohort=[dict(Study_Family='SF-EV-1473 / SF-EV-1474',Evidence_IDs='EV-1473;EV-1474',Relationship='Overlapping police-cadet cohort',Independent_Cohort_Count='1',Treatment='Presented jointly as task-specific null constraints; not counted as independent replication.',Double_Counting='NO')];wc('FULL_MANUSCRIPT_COHORT_OVERLAP_AUDIT.csv',list(cohort[0]),cohort)
 tr=[dict(Claim_ID=c['Claim_ID'],Evidence_ID=c['Evidence_ID'],International_Use='Population-and-setting-bound',Brazil_Use='Not inferred from this international working manuscript',Prohibited_Inference=c['Limitation'],Status='EXPLICIT_LIMIT_PRESERVED') for c in cm];wc('FULL_MANUSCRIPT_TRANSFERABILITY_MATRIX.csv',list(tr[0]),tr)
 lim=[dict(Limitation_ID='LIM-01',Limitation='Evidence-informed integrative synthesis; not systematic, scoping, or meta-analysis.',Action='Stated in abstract, methods, and limitations.'),dict(Limitation_ID='LIM-02',Limitation='Claim-ready remains NO for expansion claims.',Action='Marked in claim matrix and limitations.'),dict(Limitation_ID='LIM-03',Limitation='Observational, feasibility, qualitative, and measurement-specific designs.',Action='No causal or universal wording.'),dict(Limitation_ID='LIM-04',Limitation='Unadjudicated contradictory and integrity-blocked records are not support.',Action='Explicit exclusion and limitation.'),dict(Limitation_ID='LIM-05',Limitation='International-to-Brazil transfer is limited.',Action='Transferability matrix and discussion statement.')];wc('FULL_MANUSCRIPT_LIMITATIONS.csv',list(lim[0]),lim)
 (O/'FULL_MANUSCRIPT_FRAMEWORK_CONTENT_SPEC.md').write_text('# Proposed synthesis framework\n\n**Label:** PROPOSED SYNTHESIS FRAMEWORK — NOT YET VALIDATED.\n\nThe framework orders four governance questions: task and outcome definition; result-located evidence; design and transferability limits; and decision boundaries. It creates no score, cutoff, diagnosis, or operational protocol. Validation requires prospective, task-defined, locally governed study.\n',encoding='utf-8')
 gaps=[dict(Gap_ID='GAP-01',Domain='Brazil full-manuscript expansion',Status='INSUFFICIENT',Reason='Batch 11.0 subset does not add sufficient Brazilian direct result-located evidence.',Action='Do not reconstruct Brazil in Batch 11.1.'),dict(Gap_ID='GAP-02',Domain='Contradictory evidence',Status='UNADJUDICATED',Reason='EV-0052; EV-0140; EV-1066 lack completed adjudication.',Action='No support use; retain limitation.'),dict(Gap_ID='GAP-03',Domain='Framework validation',Status='NOT_VALIDATED',Reason='No prospective validation study.',Action='No model/protocol validation language.')];wc('FULL_MANUSCRIPT_EVIDENCE_GAPS.csv',list(gaps[0]),gaps)
 words=lambda x:len(re.findall(r"\b[\w'-]+\b",x)); total=words(abstract)+sum(words(x) for q in S.values() for x in q);projection=[dict(Component='Abstract',Words=words(abstract),Target='250–350'),dict(Component='Body',Words=total-words(abstract),Target='5000–7500 when evidence density warrants'),dict(Component='References',Words='Not counted',Target='Working references only'),dict(Component='Assessment',Words=total,Target='Concise evidence-first working manuscript; expansion only after audit.')];wc('FULL_MANUSCRIPT_WORD_PAGE_PROJECTION.csv',list(projection[0]),projection)
 orphan=[dict(Audit='Cited references missing from list',Count=0,Status='PASS'),dict(Audit='Listed but uncited references',Count=0,Status='PASS'),dict(Audit='Duplicate DOI',Count=0,Status='PASS'),dict(Audit='Blocked evidence used',Count=0,Status='PASS'),dict(Audit='Excluded evidence used',Count=0,Status='PASS')];wc('FULL_MANUSCRIPT_ORPHAN_REFERENCE_AUDIT.csv',list(orphan[0]),orphan)
 drift=[dict(Control='CEF-v1 changed',Value='NO',Status='PASS'),dict(Control='Zotero changed',Value='NO',Status='PASS'),dict(Control='v0.16/v0.17 changed',Value='NO',Status='PASS'),dict(Control='New literature search',Value='NO',Status='PASS'),dict(Control='Claim-ready promoted',Value='0',Status='PASS'),dict(Control='Unsupported causal language',Value='0',Status='PASS'),dict(Control='Contradictory evidence used as support',Value='0',Status='PASS'),dict(Control='EV-1379 used',Value='0',Status='PASS')];wc('FULL_MANUSCRIPT_SCIENTIFIC_DRIFT_AUDIT.csv',list(drift[0]),drift)
 doc=Document();sec=doc.sections[0];sec.top_margin=Inches(.7);sec.bottom_margin=Inches(.7);sec.left_margin=Inches(.78);sec.right_margin=Inches(.78); st=doc.styles;st['Normal'].font.name='Aptos';st['Normal'].font.size=Pt(10.5);st['Title'].font.name='Aptos Display';st['Title'].font.size=Pt(22);st['Title'].font.bold=True;st['Title'].font.color.rgb=RGBColor(0,0,0)
 for x in ['Heading 1','Heading 2']:st[x].font.name='Aptos';st[x].font.color.rgb=RGBColor(0,0,0)
 p=doc.add_paragraph(style='Title');p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.add_run(title)
 ppr=p._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr'); bot=OxmlElement('w:bottom');bot.set(qn('w:val'),'nil');pb.append(bot);ppr.append(pb)
 p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.add_run('Evidence-informed integrative synthesis | Working manuscript | '+D).italic=True
 doc.add_paragraph('Status: Working reconstruction for final scientific and reference audit. The manuscript does not claim systematic-review status, Claim-Ready status, framework validation, or universal operational thresholds.');doc.add_heading('Abstract',1);doc.add_paragraph(abstract);p=doc.add_paragraph();p.add_run('Keywords: ').bold=True;p.add_run('operational readiness; tactical athletes; public safety; evidence synthesis; implementation; transferability')
 for sec,ps in S.items():
  doc.add_heading(sec,1)
  for p in ps:doc.add_paragraph(p)
 doc.add_heading('Table 1  Bounded evidence domains',1);tb=doc.add_table(rows=1,cols=4);tb.alignment=WD_TABLE_ALIGNMENT.CENTER;tb.style='Table Grid'
 for c,t in zip(tb.rows[0].cells,['Domain','Evidence role','Boundary','Status']):cell(c,t,True);shade(c,'1F4E78');[setattr(r.font.color,'rgb',RGBColor(255,255,255)) for r in c.paragraphs[0].runs]
 for x in domains:
  for c,v in zip(tb.add_row().cells,[x['Domain'],str(x['Core_Claim_Count'])+' bounded claims',x['Synthesis'],'Pending final audit']):cell(c,v)
 doc.add_heading('References',1)
 for a in active:
  p=doc.add_paragraph();p.paragraph_format.left_indent=Inches(.2);p.paragraph_format.first_line_indent=Inches(-.2);p.add_run(f"{a['Citation_Number']}. {a['Authors']}. {a['Title']}. {a['Journal']} ({a['Year']}). doi:{a['DOI'] or 'not indexed in PubMed'}.")
 doc.add_heading('Working manuscript governance note',1);doc.add_paragraph('All expansion claims used here have documented human role decisions but remain Claim-Ready NO. Final scientific and reference audit is required before editorial formatting, submission preparation, or use as a validated framework.')
 dp=O/'International_v1.0-FULL-MANUSCRIPT-WORKING.docx';doc.save(dp)
 with zipfile.ZipFile(dp) as z:assert z.testzip() is None and 'word/document.xml' in z.namelist()
 files=[p for p in O.iterdir() if p.is_file() and p.name not in ['BATCH11_1_MANIFEST.json','BATCH11_1_REPORT.md']];man={'batch':'BATCH 11.1','gate':'FULL_MANUSCRIPT_EVIDENCE_FIRST_RECONSTRUCTION_PASS','base_commit':'de7aaee9582e166ca23f596263a510f37b1b4294','branch':'codex/full-manuscript-expansion','date':D,'outputs':[{'file':p.name,'sha256':hs(p),'bytes':p.stat().st_size} for p in sorted(files)],'controls':{'cef_v1_changed':False,'zotero_changed':False,'prior_manuscripts_changed':False,'new_literature_search':False,'claim_ready_promotions':0,'ev1379_used':False,'contradictory_support_use':0,'excluded_evidence_use':0},'counts':{'frozen_international_claims':4,'human_approved_expansion_claims':12,'contextual_sources_used':4,'active_references':len(active),'sentence_provenance_rows':len(prov),'orphan_references':0}};(O/'BATCH11_1_MANIFEST.json').write_text(json.dumps(man,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 (O/'BATCH11_1_REPORT.md').write_text(f'''# Batch 11.1 report\n\n## Gate\n\n`FULL_MANUSCRIPT_EVIDENCE_FIRST_RECONSTRUCTION_PASS`\n\nA journal-agnostic International working manuscript was reconstructed from the frozen International baseline, 12 human-approved bounded expansion claims, and four contextual discussion sources. Brazil was not reconstructed because its evidence-density criterion remains insufficient.\n\n## Counts\n\n- Frozen International claims retained: 4/4\n- Human-approved expansion claims included with bounded wording: 12/12\n- Contextual discussion sources: 4\n- Active references: {len(active)}\n- Material scientific-sentence provenance records: {sum(x['Material_Scientific_Sentence']=='YES' for x in prov)}\n- Claim-Ready promotions: 0\n- Orphan references: 0\n- Contradictory evidence used as support: 0\n- Excluded evidence used: 0\n\n## Limits\n\nThe document is a working evidence-informed integrative synthesis. It is not a systematic review, validated framework, or readiness protocol. All expansion claims remain `Claim-Ready = NO` pending final scientific and reference audit. EV-0052, EV-0140, EV-1066, and EV-1379 are not used as support.\n\n## Next gate\n\n`GO_FINAL_SCIENTIFIC_AND_REFERENCE_AUDIT`\n''',encoding='utf-8')
 print(json.dumps({'output':str(O),'active_references':len(active),'provenance':len(prov),'words':total,'docx_sha256':hs(dp)},ensure_ascii=False))
if __name__=='__main__':main()
