"""Records the BATCH 10.4H-R publication reconciliation without fabricating v0.15 artifacts."""
import hashlib, json, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'batch10_4i'; OUT.mkdir(exist_ok=True)
EXPECTED=['International_v0.15-B2-EVIDENCE-FIRST','Brazil_v0.15-B2-EVIDENCE-FIRST','V015_B2_CLAIM_CITATION_MATRIX.csv','V015_B2_SENTENCE_PROVENANCE.csv','V015_B2_WORKING_REFERENCE_SET.csv','V015_B2_RESULT_ID_USE_AUDIT.csv','V015_B2_NULL_RESULT_AUDIT.csv','V015_B2_COHORT_OVERLAP_AUDIT.csv','V015_B2_TRANSFERABILITY_AUDIT.csv','V015_B2_PROTECTED_CLAIM_AUDIT.csv','V015_B2_FRAMEWORK_AUDIT.csv','V015_B2_ABSTRACT_BODY_COHERENCE.csv','V015_B2_CONCLUSION_COHERENCE.csv','V015_B2_REFERENCE_USE_AUDIT.csv','V015_B2_MANUSCRIPT_VIABILITY.csv','V015_B2_HUMAN_REVIEW_QUEUE.csv','BATCH10_4H_R_MANIFEST.json','BATCH10_4H_R_REPORT.md']
def main():
 local=ROOT/'batch10_4h_r'
 local_exists=local.exists()
 tracked=subprocess.check_output(['git','ls-tree','-r','--name-only','HEAD','batch10_4h_r'],cwd=ROOT,text=True).splitlines()
 report=f'''# BATCH 10.4H-R — GitHub reconciliation\n\n## Finding\n\n`V015_FINAL_SCIENTIFIC_AUDIT_BLOCKED`\n\nThe required `batch10_4h_r/` directory is absent from both the current checkout and the tracked tree at `HEAD`. Consequently, neither B2 v0.15 manuscript nor any required v0.15 B2 matrix can be authenticated against GitHub.\n\n## Controls performed\n\n- Branch: `codex/deep-evidence-batch10-4b`\n- HEAD checked by Git: {subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()}\n- Local `batch10_4h_r/` exists: {'YES' if local_exists else 'NO'}\n- Files tracked under `batch10_4h_r/`: {len(tracked)}\n- Expected reconstruction artifacts checked: {len(EXPECTED)}; present: 0; absent: {len(EXPECTED)}.\n\n## Consequence\n\nNo claim, sentence, citation, reference-use, manuscript-viability or human-review reduction audit was produced. Creating the mandatory scientific-audit CSVs without their authorities would fabricate an audit trail.\n\n## Exact unblock condition\n\nPublish or restore the complete, validated `batch10_4h_r/` artifact set on this branch, including both v0.15 B2 manuscripts, all V015_B2 matrices, report and manifest. Then rerun BATCH 10.4I from the restored commit.\n'''
 (OUT/'BATCH10_4H_R_GITHUB_RECONCILIATION.md').write_text(report,encoding='utf-8')
 files=[OUT/'BATCH10_4H_R_GITHUB_RECONCILIATION.md']
 manifest={'batch':'BATCH 10.4I','gate':'V015_FINAL_SCIENTIFIC_AUDIT_BLOCKED','reason':'BATCH10_4H_R_GITHUB_RECONCILIATION: authoritative v0.15 B2 reconstruction artifact set absent locally and from current Git tree.','head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'branch':subprocess.check_output(['git','branch','--show-current'],cwd=ROOT,text=True).strip(),'batch10_4h_r_local_exists':local_exists,'batch10_4h_r_tracked_file_count':len(tracked),'expected_authority_artifact_count':len(EXPECTED),'authorities_present':0,'scientific_claims_audited':0,'citations_audited':0,'human_review_items_reduced':0,'reference_freeze_executed':0,'Zotero_changed':0,'CEF_v1_changed':0,'v015_content_changed':0,'next_action':'Restore or publish the complete validated batch10_4h_r artifact set, then rerun BATCH 10.4I.','artifact_sha256':{x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in files}}
 (OUT/'BATCH10_4I_MANIFEST.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 (OUT/'BATCH10_4I_REPORT.md').write_text('# BATCH 10.4I — final scientific audit\n\n`V015_FINAL_SCIENTIFIC_AUDIT_BLOCKED`\n\nSee [BATCH10_4H_R_GITHUB_RECONCILIATION.md](BATCH10_4H_R_GITHUB_RECONCILIATION.md). The required v0.15 B2 authorities are absent, so no scientific audit was simulated.\n',encoding='utf-8')
if __name__=='__main__': main()
