# ruff: noqa: C408
"""Build the controlled Pilot 03 full-text qualification ledgers."""

from __future__ import annotations

import csv
import hashlib
import json
import os
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

try:
    from audit_xlsx_identity import semantic_sha256
except ModuleNotFoundError:
    from analysis.audit_xlsx_identity import semantic_sha256

ROOT = Path(__file__).resolve().parents[1]
RAW = Path(os.environ.get("ORB_PILOT03_RAW_ROOT", ROOT.parents[1] / "outputs/full-text/2026-09-17-pilot-03"))
OUT = ROOT / "reporting/full-text/2026-09-17/pilot-03"
QUEUE = ROOT / "reporting/nonblocking/2026-09-16/full-text-priority-queue.csv"
PILOT1 = ROOT / "reporting/full-text/2026-09-17/pilot-01-methodological-correction/corrected-records.csv"
PILOT2 = ROOT / "reporting/full-text/2026-09-17/pilot-02/pilot-records.csv"
MASTER = ROOT / "outputs/8a39e3c813da/PREMIUM_ELITE_DIAMANTE_Evidence_Command_Center.xlsx"
SOURCE_COMMIT = "fc1442d04a5c4c52b46d8a6c70d1531a58ea7ec4"
DATE = "2026-09-17"

JBI_QUAL = "https://jbi.global/sites/default/files/2026-05/2024_Checklist_for_Qualitative_Research_1.docx"
JBI_QUASI = "https://jbi.global/sites/default/files/2026-05/2_JBI%20checklist%20for%20quasi-experimental%20studies.docx"
JBI_CROSS = "https://jbi.global/sites/default/files/2026-03/the_revised_jbi_critical_appraisal_tool_for_the.2.pdf"
MMAT = "https://mixedmethodsappraisaltoolpublic.pbworks.com/w/file/fetch/127916259/MMAT_2018_criteria%20manual_2018%20-08-01_ENG.pdf"
SANRA = "https://doi.org/10.1186/s41073-019-0064-8"

SELECTED = [
    ("EV-0629", "36747268", "LCFHG7J2", "10.1186/s13722-023-00363-4", "PMC9902242"),
    ("EV-0592", "37326779", "C3CAQKDL", "10.1007/s10552-023-01732-9", "PMC10689544"),
    ("EV-0515", "38233933", "FV2SE2HG", "10.1186/s13011-023-00590-7", "PMC10795311"),
    ("EV-0439", "39119394", "AGAPQVEJ", "10.7759/cureus.64132", "PMC11307241"),
    ("EV-0405", "39425094", "N3LQZTNN", "10.1186/s12889-024-20336-9", "PMC11490149"),
    ("EV-0335", "40156033", "RALPHKM3", "10.1186/s12954-025-01193-0", "PMC11951663"),
    ("EV-0316", "40406195", "IPT4R6IA", "10.1177/10986111241265290", "PMC12094109"),
    ("EV-0282", "40710431", "DSDH9DAX", "10.3390/jpm15070314", "PMC12298807"),
    ("EV-0252", "40979841", "CGBGDU6Y", "10.1080/15614263.2025.2512806", "PMC12448121"),
    ("EV-0167", "41537090", "X6PMUAYB", "10.1007/s11292-025-09711-7", "PMC12798756"),
]

CURATED = {
"EV-0629": dict(country_context="Miami, Florida, United States; public academic hospital and syringe service program", population="15 interviews: 8 clinicians and 7 patients with injection-drug-use-associated infections; 3 patients exposed to the SIRI team", design="qualitative implementation study using purposive sampling, semi-structured interviews and CFIR-guided content analysis", evidence_origin="EMPIRICAL", evidence_class="QUALITATIVE_EVIDENCE", appraisal_tool="JBI Qualitative Research", appraisal_version="2024 checklist; file published 2026-05", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="Clinicians and patients described multidisciplinary expertise, advocacy and continuity as facilitators, and role ambiguity, workload, stigma and resource constraints as barriers to implementing the integrated SIRI team.", result="Fifteen interviews generated CFIR-organized barriers and facilitators; the article reports perceptions during the first eight months and no effectiveness estimate.", exact_evidence_location="Study design and procedures P1; Study setting and participants P1; Data collection and analysis P1; Results P1; Table 2; Table 3; Discussion; Conclusions", supported_claims="In this early single-site sample, interviewed clinicians and patients identified specific barriers and facilitators to implementing an integrated infectious-disease and substance-use-disorder team.", unsupported_claims="The interviews do not establish reduced readmission, infection cure, treatment retention, mortality benefit or causal effectiveness of the SIRI team.", transferability_limits="One US safety-net academic system, small purposive sample, only three exposed patients and a local syringe-service partnership limit transfer to Brazilian public safety.", appraisal_summary="AI-provisional JBI qualitative appraisal: congruent qualitative approach, double coding, ethics and participant quotations; limited reflexivity and small early-implementation sample constrain inference."),
"EV-0592": dict(country_context="United States; national Cancer Prevention and Control Research Network", population="22 current or former network leaders, investigators, staff, federal partners and academic/community affiliates", design="qualitative brief report using convenience sampling, semi-structured interviews and constructivist thematic analysis", evidence_origin="EMPIRICAL", evidence_class="QUALITATIVE_EVIDENCE", appraisal_tool="JBI Qualitative Research", appraisal_version="2024 checklist; file published 2026-05", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="Participants described a longstanding disparities focus, newer explicit health-equity structures, and needs for workforce diversity and cross-network collaboration.", result="Twenty-two interviews produced four themes about the network's evolution and future health-equity priorities; findings are perceptions of involved members.", exact_evidence_location="Methods P1; Results P1; Themes 1-4; Table 1; Discussion P1-P4; Conclusion P1", supported_claims="Interviewed network participants perceived a longstanding disparities focus and identified organizational actions and remaining needs for health equity.", unsupported_claims="The study does not demonstrate that the network improved equity, cancer outcomes or population access, or that its model transfers to public safety.", transferability_limits="Convenience sample of engaged US cancer-research network members, modest N and likely self-selection; no operational public-safety setting.", appraisal_summary="AI-provisional JBI qualitative appraisal: question, thematic approach and illustrative quotations are coherent, but methods are partly reported elsewhere and reflexivity is limited."),
"EV-0515": dict(country_context="Aberdeen, Glasgow and Dundee, Scotland; planned community drug-checking services", population="43 interviews: 27 professionals, 11 people with recent drug use and 5 family members; implementation meeting notes", design="qualitative implementation study using interviews, meeting notes and hybrid inductive-deductive CFIR analysis", evidence_origin="EMPIRICAL", evidence_class="QUALITATIVE_EVIDENCE", appraisal_tool="JBI Qualitative Research", appraisal_version="2024 checklist; file published 2026-05", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="Participants supported low-threshold trusted services and identified confidentiality, rapid testing, harm-reduction links, public attitudes, policing and stakeholder communication as implementation conditions.", result="Forty-three interviews and implementation notes generated nine constructs/themes across all five CFIR domains; results describe anticipated implementation, not service outcomes.", exact_evidence_location="Methods P1-P7; Results P1-P4; Tables 1-3; Discussion; Conclusions", supported_claims="These Scottish stakeholders identified design, organizational, policing and community conditions they considered relevant to planned drug-checking services.", unsupported_claims="The study does not establish uptake, analytical accuracy, behavior change, overdose prevention or effectiveness of a service not yet operational.", transferability_limits="Scottish legal, health and harm-reduction context; overwhelmingly White sample; anticipated rather than observed implementation.", appraisal_summary="AI-provisional JBI qualitative appraisal: explicit eligibility, reflexive diary, dual coding, triangulation and lived-experience checking; anticipated implementation and sampling limit transferability."),
"EV-0439": dict(country_context="Poland; medical, nursing and emergency-medical-service students and professionals recruited online", population="295 respondents; 56.9% women, 59.3% under 25 and 60% students", design="analytical cross-sectional voluntary survey using a proprietary 47-question trauma-knowledge instrument and unadjusted group comparisons", evidence_origin="EMPIRICAL", evidence_class="QUANTITATIVE_EVIDENCE", appraisal_tool="JBI Analytical Cross Sectional Studies", appraisal_version="revised 2026 tool", appraisal_type="RISK_OF_BIAS_APPRAISAL", extraction="Trauma-knowledge scores were described and compared across student/professional groups and prior course participation using nonparametric and chi-square tests.", result="Mean score was 63/117; paramedics averaged 78, doctors 73 and nurses 57. Prior-course participants averaged 77 versus 65 without a course (p<0.001); comparisons were unadjusted.", exact_evidence_location="Materials and methods P1-P5; Results P1-P7; Figure 1; Discussion P1-P9; Conclusions P1", supported_claims="Within this self-selected sample, knowledge scores differed across professional/education groups and by reported prior trauma-course participation.", unsupported_claims="The cross-sectional unadjusted comparisons do not show that courses caused higher knowledge, validate the proprietary test, measure practical competence or predict patient outcomes.", transferability_limits="Voluntary social-media sample, proprietary instrument, no response denominator or confounder control, Polish curricula and civilian medical context.", appraisal_summary="AI-provisional revised JBI analytical cross-sectional appraisal: eligibility and statistics are reported, but selection, instrument validity and uncontrolled confounding limit associations."),
"EV-0405": dict(country_context="British Columbia, Canada; national independent evaluation of illicit-drug decriminalization", population="Protocol covering people who use drugs, police/criminal justice, general public, health services and economic systems; no outcome sample yet", design="prospective multi-study observational evaluation protocol with eight qualitative, quantitative and mixed-methods substudies", evidence_origin="NON_EMPIRICAL_PROTOCOL", evidence_class="STUDY_PROTOCOL_EVIDENCE", appraisal_tool="Protocol Methods Completeness Check", appraisal_version="Pilot 03 controlled schema v1; non-scored", appraisal_type="REPORTING_COMPLETENESS_CHECK", extraction="The protocol specifies stakeholder engagement, a logic model, eight linked substudies, five domains, data integration and anticipated confounding from concurrent policy changes and data limitations.", result="No study results are reported; this record contributes prospective methods and an evaluation architecture only.", exact_evidence_location="Methods P1; Stakeholder engagement P1-P6; Logic model and evaluation design P1-P2; Figures 2-3; five domain sections; Challenges & limitations P1-P5", supported_claims="The protocol documents the planned scope, logic model, stakeholder structure and methodological challenges of evaluating British Columbia's policy.", unsupported_claims="It cannot establish any public-health, policing, economic or causal effect because outcomes have not yet been reported.", transferability_limits="Canadian legal and health-system policy, changing possession rules, concurrent initiatives and future data availability; no Brazilian results.", appraisal_summary="AI-provisional non-scored protocol completeness check: objectives, logic model, substudies, integration and anticipated limitations are explicit; no outcome or risk-of-bias conclusion is possible."),
"EV-0335": dict(country_context="Seattle, Washington, United States; syringe-service and mobile medical sites", population="13 adults with opioid-use experience and an EMS interaction in the prior 12 months", design="community-engaged qualitative study using convenience sampling, semi-structured interviews and hybrid CFIR-informed thematic analysis", evidence_origin="EMPIRICAL", evidence_class="QUALITATIVE_EVIDENCE", appraisal_tool="JBI Qualitative Research", appraisal_version="2024 checklist; file published 2026-05", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="Participants described peer responsibility and competence in overdose response, weighed benefits and harms of EMS involvement, and identified fear of police response as a deterrent to calling EMS.", result="Thirteen interviews generated three themes about peer overdose response, EMS decisions and police-related fear; findings reflect participant experience and perceptions.", exact_evidence_location="Community engagement P1; Data collection P1-P3; Data analysis P1; Results P1-P4; Table 1; Table 2; Limitations P1", supported_claims="In this convenience sample, participants described active peer overdose-response roles and police-response fears that influenced decisions about contacting EMS.", unsupported_claims="The study does not estimate how often EMS is avoided, quantify police effects, establish overdose outcomes or represent people outside participating harm-reduction sites.", transferability_limits="Small self-selected Seattle sample with access to well-resourced legal harm reduction and local police/EMS arrangements.", appraisal_summary="AI-provisional JBI qualitative appraisal: community co-production, saturation, dual coding, ethics and quotations are reported; convenience recruitment and setting limit transferability."),
"EV-0316": dict(country_context="United States policing; conceptual orientation to implementation science", population="Published literature, frameworks and illustrative policing cases; no participant sample", design="narrative review and conceptual practice orientation without a systematic review protocol", evidence_origin="NON_EMPIRICAL", evidence_class="NARRATIVE_REVIEW_EVIDENCE", appraisal_tool="SANRA", appraisal_version="2019; six-item scale used domain-by-domain without global score", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="The article maps implementation-science concepts, CFIR and EPIS frameworks, hybrid trials and de-implementation to evidence-based policing and proposes a research/practice agenda.", result="A 2023 author/librarian search identified six policing publications, but the paper is an orientation and conceptual synthesis rather than an effect review.", exact_evidence_location="Abstract; Introduction P1-P10; The State of Implementation Science in EBP P1-P8; Tables 1-3; framework and trial sections; Discussion P1-P6; Conclusion", supported_claims="The review provides a structured conceptual account of how implementation-science frameworks could inform policing research and practice.", unsupported_claims="It does not demonstrate that CFIR, EPIS or any implementation strategy improves policing outcomes, legitimacy, safety or sustainability.", transferability_limits="Predominantly US conceptual examples, non-systematic search and no empirical synthesis or Brazilian validation.", appraisal_summary="AI-provisional SANRA appraisal: aims, rationale and referencing are strong; search strategy is only briefly described and evidence selection is not systematic."),
"EV-0282": dict(country_context="Western Pomerania, Germany; rural emergency medical services", population="Secondary integrated analysis of a regional project spanning lay CPR training, responder-app activation, tele-emergency physician support, economic modeling and workforce evaluation", design="mixed-methods secondary implementation evaluation with uncontrolled pre-post quantitative components, economic modeling and formative organizational evidence", evidence_origin="EMPIRICAL_SECONDARY_ANALYSIS", evidence_class="MIXED_METHODS_EVIDENCE", appraisal_tool="MMAT", appraisal_version="2018; screening + qualitative + non-randomized quantitative + mixed-methods domains", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="The article integrates clinical/operational, economic and work-system findings across three implemented pillars and explicitly frames results as a secondary personalized-medicine analysis.", result="Reported examples include 3.96 tele-emergency cases/day, >90% idle time for a single district, and modeled cost reduction from EUR 696,949 per unit to EUR 57,300 per district in a 20-district centralized scenario; causal attribution is limited.", exact_evidence_location="2.1 Intervention Design; 2.2 Evaluation Design P1; 2.2.1-2.2.3; 3.1-3.3; Figures 1-4; 4.1; 4.3 Limitations P1-P4", supported_claims="This secondary project analysis reports operational, economic-model and organizational findings from the RuralRescue implementation.", unsupported_claims="The uncontrolled evaluation and modeled scenarios do not establish causal clinical benefit, mortality reduction, realized regional savings or superiority over alternative systems.", transferability_limits="German EMS financing, rural geography, dispatcher infrastructure and telemedicine regulation differ materially from Brazilian public-safety and health systems.", appraisal_summary="AI-provisional full MMAT: multiple components are integrated around an implementation question, but secondary reporting, no control, self-selection and incompletely controlled confounding constrain inference."),
"EV-0252": dict(country_context="United States; police leadership conferences and academy cohorts", population="72 law-enforcement executives, senior staff and a small number of experienced police researchers", design="quantitative descriptive convenience survey with 31 investigator/executive-derived CFIR items and exploratory bivariate correlations", evidence_origin="EMPIRICAL", evidence_class="QUANTITATIVE_EVIDENCE", appraisal_tool="MMAT Quantitative Descriptive", appraisal_version="2018; screening + criteria 4.1-4.5", appraisal_type="METHODOLOGICAL_QUALITY_APPRAISAL", extraction="Respondents rated organizational and community determinants of innovation implementation; analyses were descriptive with exploratory construct correlations.", result="Seventy-two respondents completed the instrument with 46/2,232 item responses missing (2.0%); response rate could not be computed and results describe this selected leadership sample.", exact_evidence_location="Study population P1; Survey development and measures P1-P3; Results P1-P3; Table 3; Table 4; Exploratory bivariate associations; Limitations P1-P2", supported_claims="In this selected US leadership sample, respondents rated several CFIR-aligned implementation determinants as salient and provided descriptive priorities for future research.", unsupported_claims="The survey does not establish prevalence across US policing, causal determinants of implementation success, innovation effectiveness or transferability to Brazil.", transferability_limits="Convenience sample from change-oriented venues, no computable response rate, novel closed-form instrument, senior US leadership perspective and limited rank-and-file input.", appraisal_summary="AI-provisional MMAT quantitative-descriptive appraisal: measures and descriptive analysis are traceable, but convenience sampling, unknown response rate and uncertain instrument validation limit representativeness."),
"EV-0167": dict(country_context="Two mid-sized police departments in Arizona, United States", population="84 anonymous frontline responses: 43 in AJPD and 41 in CGPD, collected about five months into parallel RCT deployments", design="natural experiment comparing departments with versus without automated positive-feedback email, using cross-sectional surveys, adjusted ordered-logit and instrumental-variable models", evidence_origin="EMPIRICAL", evidence_class="QUANTITATIVE_EVIDENCE", appraisal_tool="JBI Quasi-Experimental Studies", appraisal_version="2023 tool; Barker et al. 2024", appraisal_type="RISK_OF_BIAS_APPRAISAL", extraction="The study compared acceptability, appropriateness and feasibility perceptions between two departments and modeled reported receipt of automated feedback using department assignment as an instrument.", result="Adjusted probability of agreeing Truleo was appropriate was 21.7 percentage points higher in CGPD (p=.011); acceptability was 14.5 points higher (p=.054) and feasibility was not significant. IV coefficients were 1.226 (p=.042) and 1.428 (p=.030) for acceptability and appropriateness.", exact_evidence_location="Setting P1-P3; Data collection P1; Analytical sample and plan P1-P24; Sample characteristics P1-P3; Tables 1-4; Discussion P1-P9; Limitations P1-P2; Conclusion P1", supported_claims="In these two departments, officers in the department with automated feedback reported higher appropriateness and the adjusted and IV analyses found positive associations for selected perception outcomes.", unsupported_claims="The study does not establish improved officer behavior, public safety, accountability, technology accuracy or general effects across agencies; department assignment was not randomized for this comparison.", transferability_limits="Two Arizona agencies, voluntary cross-sectional perceptions, no baseline primary outcomes, possible department confounding, exposure misclassification and borderline instrument strength.", appraisal_summary="AI-provisional JBI quasi-experimental appraisal: temporal implementation contrast and adjusted analyses support cautious inference, but no randomized department allocation, no baseline outcomes and residual confounding remain."),
}

QUAL_DOMAINS = ["methodology/philosophical perspective congruity","methodology/research question congruity","methodology/data collection congruity","methodology/data representation and analysis congruity","methodology/interpretation congruity","researcher culturally or theoretically located","researcher influence addressed","participants and voices adequately represented","ethical conduct and approval","conclusions flow from analysis"]
CROSS_DOMAINS = ["inclusion criteria clearly defined","condition measured objectively","exposure measured validly and reliably","outcome measured validly and reliably","confounders identified","strategies for confounding stated","appropriate statistical analysis","subjects and setting described in detail"]
QUASI_DOMAINS = ["cause and effect temporal order clear","control group present","participants comparable","participants received similar treatment apart from exposure","multiple pre/post measurements","follow-up complete or described","outcomes measured consistently","outcomes measured reliably","appropriate statistical analysis"]
MMAT_SCREEN = ["clear research questions","collected data address research questions"]
MMAT_QUAL = ["qualitative approach appropriate","qualitative collection adequate","findings derived from data","interpretation substantiated","coherence across qualitative process"]
MMAT_NONRAND = ["participants representative","exposure and outcome measurements appropriate","complete outcome data","confounders accounted for","intervention administered as intended"]
MMAT_DESC = ["sampling strategy relevant","sample representative","measurements appropriate","nonresponse bias low","statistical analysis appropriate"]
MMAT_MIXED = ["rationale for mixed methods","components effectively integrated","integrated outputs interpreted","divergences addressed","components meet tradition quality"]
SANRA_DOMAINS = ["importance justified","aims stated","literature search described","referencing adequate","scientific reasoning adequate","endpoint data presented appropriately"]
PROTOCOL_DOMAINS = ["objectives explicit","logic model explicit","substudy designs identified","populations and stakeholders identified","outcomes and indicators prespecified","data integration specified","confounders and concurrent policies addressed","limitations and missing data anticipated"]

APPRAISALS = {
 "EV-0629": ("JBI Qualitative Research","2024 checklist; file published 2026-05","METHODOLOGICAL_QUALITY_APPRAISAL","QUALITATIVE_STUDY",QUAL_DOMAINS,["UNCLEAR","YES","YES","YES","YES","UNCLEAR","UNCLEAR","YES","YES","YES"],JBI_QUAL),
 "EV-0592": ("JBI Qualitative Research","2024 checklist; file published 2026-05","METHODOLOGICAL_QUALITY_APPRAISAL","QUALITATIVE_STUDY",QUAL_DOMAINS,["UNCLEAR","YES","YES","YES","YES","UNCLEAR","UNCLEAR","YES","YES","YES"],JBI_QUAL),
 "EV-0515": ("JBI Qualitative Research","2024 checklist; file published 2026-05","METHODOLOGICAL_QUALITY_APPRAISAL","QUALITATIVE_STUDY",QUAL_DOMAINS,["UNCLEAR","YES","YES","YES","YES","YES","YES","YES","YES","YES"],JBI_QUAL),
 "EV-0439": ("JBI Analytical Cross Sectional Studies","revised 2026 tool","RISK_OF_BIAS_APPRAISAL","ANALYTICAL_CROSS_SECTIONAL",CROSS_DOMAINS,["YES","NO","UNCLEAR","UNCLEAR","NO","NO","YES","YES"],JBI_CROSS),
 "EV-0405": ("Protocol Methods Completeness Check","Pilot 03 controlled schema v1; non-scored","REPORTING_COMPLETENESS_CHECK","PROTOCOL",PROTOCOL_DOMAINS,["YES","YES","YES","YES","YES","YES","YES","YES"],"internal://pilot-03/protocol-methods-completeness-v1"),
 "EV-0335": ("JBI Qualitative Research","2024 checklist; file published 2026-05","METHODOLOGICAL_QUALITY_APPRAISAL","QUALITATIVE_STUDY",QUAL_DOMAINS,["UNCLEAR","YES","YES","YES","YES","YES","YES","YES","YES","YES"],JBI_QUAL),
 "EV-0316": ("SANRA","2019; six-item scale used domain-by-domain without global score","METHODOLOGICAL_QUALITY_APPRAISAL","NARRATIVE_REVIEW",SANRA_DOMAINS,["YES","YES","PARTIAL","YES","YES","YES"],SANRA),
 "EV-0282": ("MMAT","2018; full mixed-methods route","METHODOLOGICAL_QUALITY_APPRAISAL","MIXED_METHODS",MMAT_SCREEN+MMAT_QUAL+MMAT_NONRAND+MMAT_MIXED,["YES","YES","UNCLEAR","PARTIAL","PARTIAL","YES","PARTIAL","PARTIAL","NO","PARTIAL","NO","YES","YES","PARTIAL","PARTIAL","YES","PARTIAL"],MMAT),
 "EV-0252": ("MMAT Quantitative Descriptive","2018; screening + criteria 4.1-4.5","METHODOLOGICAL_QUALITY_APPRAISAL","QUANTITATIVE_DESCRIPTIVE",MMAT_SCREEN+MMAT_DESC,["YES","YES","YES","NO","UNCLEAR","NO","YES"],MMAT),
 "EV-0167": ("JBI Quasi-Experimental Studies","2023 tool; Barker et al. 2024","RISK_OF_BIAS_APPRAISAL","QUASI_EXPERIMENTAL_STUDY",QUASI_DOMAINS,["YES","YES","PARTIAL","YES","NO","YES","YES","YES","YES"],JBI_QUASI),
}

VERSIONS = {
 "EV-0316": ("AUTHOR_ACCEPTED_MANUSCRIPT","https://journals.sagepub.com/doi/10.1177/10986111241265290","PUBLISHER_FULL_TEXT_ACCESSIBLE","NO_MATERIAL_DIFFERENCE_OBSERVED","metadata, abstract, headings, methods/review account, tables, discussion and claims compared"),
 "EV-0252": ("AUTHOR_ACCEPTED_MANUSCRIPT","https://www.tandfonline.com/doi/abs/10.1080/15614263.2025.2512806","PUBLISHER_METADATA_AND_ABSTRACT_ACCESSIBLE","VOR_COMPARISON_PENDING","metadata and abstract compared; full methods, results, tables and limitations unavailable for sufficient comparison"),
 "EV-0167": ("AUTHOR_ACCEPTED_MANUSCRIPT","https://link.springer.com/article/10.1007/s11292-025-09711-7","PUBLISHER_FULL_TEXT_ACCESSIBLE","NO_MATERIAL_DIFFERENCE_OBSERVED","metadata, abstract, methods, results, limitations and claims compared"),
}

def clean(node): return " ".join("".join(node.itertext()).split()) if node is not None else ""
def sha256(path):
    h=hashlib.sha256()
    with Path(path).open("rb") as f:
        for c in iter(lambda:f.read(1024*1024),b""): h.update(c)
    return h.hexdigest()
def lf_bytes(path): return Path(path).read_bytes().replace(b"\r\n",b"\n").replace(b"\r",b"\n")
def lf_hash(path): return hashlib.sha256(lf_bytes(path)).hexdigest()
def read_csv(path):
    with Path(path).open(encoding="utf-8-sig",newline="") as f: return list(csv.DictReader(f))
def write_csv(path, rows):
    with Path(path).open("w",encoding="utf-8-sig",newline="") as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator="\n"); w.writeheader(); w.writerows(rows)
def parse_pmc(path):
    root=ET.parse(path).getroot(); article=root.find(".//article") if root.tag!="article" else root
    ids={n.get("pub-id-type",""):clean(n) for n in article.findall(".//article-meta/article-id")}
    authors=[]
    for c in article.findall(".//article-meta/contrib-group/contrib"):
        if c.get("contrib-type")!="author": continue
        n=c.find("./name"); authors.append(f"{clean(n.find('./given-names'))} {clean(n.find('./surname'))}".strip() if n is not None else clean(c.find("./collab")))
    return {"title":clean(article.find(".//article-meta/title-group/article-title")),"authors":"; ".join(filter(None,authors)),"journal":clean(article.find(".//journal-meta/journal-title-group/journal-title")),"year":clean(article.find(".//article-meta/pub-date/year")),"volume":clean(article.find(".//article-meta/volume")),"issue":clean(article.find(".//article-meta/issue")),"pages":clean(article.find(".//article-meta/elocation-id")) or clean(article.find(".//article-meta/fpage")),"pmid":ids.get("pmid",""),"pmcid":ids.get("pmcid",""),"doi":ids.get("doi",""),"article_type":article.get("article-type",""),"manuscript_id":ids.get("manuscript-id","")}
def integrity(path):
    root=ET.parse(path).getroot(); pts=[clean(n) for n in root.findall(".//PublicationType")]; rel=[f"{n.get('RefType','')}:{clean(n.find('./PMID'))}" for n in root.findall(".//CommentsCorrections")]
    if "Retracted Publication" in pts: return "BLOCKED_INTEGRITY","; ".join(rel)
    alert={"ErratumFor","ErratumIn","ExpressionOfConcernFor","ExpressionOfConcernIn","RetractionOf","RetractionIn","UpdateOf","UpdateIn"}
    if any(x.split(":",1)[0] in alert for x in rel): return "INTEGRITY_REVIEW_REQUIRED","; ".join(rel)
    return "INTEGRITY_CLEAR",("; ".join(rel)+"; editorial relation only" if rel else "No correction, retraction, update or expression-of-concern relation in current PubMed XML; absence is not absolute proof.")

def build():
    OUT.mkdir(parents=True,exist_ok=True)
    p1,p2=read_csv(PILOT1),read_csv(PILOT2); prior={r["evidence_id"] for r in p1+p2}
    det=[r for r in read_csv(QUEUE) if r["priority_tier"]=="P1" and r["lawful_access_status"]=="PMC_AVAILABLE" and r["evidence_id"] not in prior][:10]
    if [r["evidence_id"] for r in det] != [x[0] for x in SELECTED]: raise ValueError("Pilot 03 deterministic selection changed")
    records=[]; selection=[]; versions=[]; provenance=[]; appraisal=[]
    for order,(eid,pmid,key,doi,pmcid) in enumerate(SELECTED,1):
        if eid in prior or key=="FXC7ZY9R" or pmid=="26159007": raise ValueError(f"Forbidden selection {eid}")
        pmc=RAW/"raw/pmc"/f"{pmcid}.xml"; pub=RAW/"raw/pubmed"/f"{pmid}.xml"; meta=parse_pmc(pmc)
        if (meta["pmid"],meta["pmcid"],meta["doi"].lower()) != (pmid,pmcid,doi.lower()): raise ValueError(f"Identity mismatch {eid}")
        integ,detail=integrity(pub)
        if integ!="INTEGRITY_CLEAR": raise ValueError(f"Unexpected integrity state {eid}: {integ}")
        default="AUTHOR_ACCEPTED_MANUSCRIPT" if meta["manuscript_id"] else "VERSION_OF_RECORD"
        version,url,access,comparison,scope=VERSIONS.get(eid,(default,f"https://doi.org/{doi}","VERSION_OF_RECORD_USED_FROM_PMC","NOT_APPLICABLE","PMC VOR used"))
        c=CURATED[eid]
        row={"pilot_order":str(order),"evidence_id":eid,"pmid":pmid,"doi":doi,"pmcid":pmcid,"zotero_key":key,"title":meta["title"],"authors":meta["authors"],"journal":meta["journal"],"year":meta["year"],"volume":meta["volume"],"issue":meta["issue"],"pages_or_elocation":meta["pages"],"full_text_source":f"https://pmc.ncbi.nlm.nih.gov/articles/{pmcid}/","lawful_access":"YES","full_text_obtained":"YES","identity_status":"MATCH_CONFIRMED","version_status":version,"article_type_jats":meta["article_type"],"integrity_status":integ,"integrity_detail":detail,"eligibility_full_text":"RETAIN_FOR_HUMAN_CONFIRMATION",**c,"original_data":"NO" if c["evidence_origin"].startswith("NON_EMPIRICAL") else "YES","empirical_effect_estimate":"YES" if eid in {"EV-0439","EV-0282","EV-0167"} else "NO","appraisal_complete_ai_provisional":"YES","global_quality_score":"NOT_CALCULATED","extraction_complete":"YES","exact_location_complete":"YES","boundary_complete":"YES","transferability_complete":"YES","editorial_hold":"NO","human_reviewer":"","human_review_date":"","human_decision":"","human_justification":"","human_confirmation":"","claim_ready":"NO","record_status":"HUMAN_REVIEW_REQUIRED"}
        records.append(row)
        selection.append({"pilot_order":str(order),"evidence_id":eid,"pmid":pmid,"priority_tier":det[order-1]["priority_tier"],"priority_score":det[order-1]["priority_score"],"access_status":det[order-1]["lawful_access_status"],"queue_position_after_pilots_01_02_exclusion":str(order),"selection_rule":"FIRST_10_P1_PMC_AVAILABLE_NOT_IN_PILOTS_01_02"})
        versions.append({"evidence_id":eid,"pmid":pmid,"pmcid":pmcid,"source_version":version,"publisher_url":url,"publisher_access":access,"vor_comparison":comparison,"comparison_scope":scope,"claim_location_status":"VOR_LOCATION_REQUIRED_BEFORE_CLAIM_READY" if comparison=="VOR_COMPARISON_PENDING" else "SOURCE_LOCATION_RECORDED_HUMAN_AUDIT_REQUIRED","human_confirmed":""})
        for stage,source,path,tool,trans in [("RAW_PUBMED","NCBI Entrez EFetch",pub,"fetch_full_text_pilot03.py","none"),("FULL_TEXT","NCBI PMC EFetch JATS XML",pmc,"fetch_full_text_pilot03.py","parsed metadata, sections and tables")]:
            provenance.append({"evidence_id":eid,"stage":stage,"source":source,"path_external":f"external://full-text/2026-09-17-pilot-03/{path.relative_to(RAW).as_posix()}","sha256":sha256(path),"timestamp":DATE,"tool":tool,"transformation":trans})
        provenance.append({"evidence_id":eid,"stage":"EXTRACTION_APPRAISAL","source":"audited lawful full text","path_external":"","sha256":"","timestamp":DATE,"tool":"build_full_text_pilot03.py","transformation":"AI-assisted provisional extraction and domain appraisal; human fields unchanged"})
        tool,ver,atype,comp,domains,judgments,source=APPRAISALS[eid]
        if len(domains)!=len(judgments): raise ValueError(f"Appraisal incomplete {eid}")
        for i,(domain,judgment) in enumerate(zip(domains,judgments),1):
            appraisal.append({"evidence_id":eid,"tool":tool,"tool_version":ver,"appraisal_type":atype,"component":comp,"criterion_code":f"Q{i}","domain":domain,"judgment_ai_provisional":judgment,"basis":c["exact_evidence_location"],"source_url":source,"human_confirmed":""})
    checks=["article_identity","pmid_identity","pmcid_identity","doi_identity","duplicate_exclusion","supplement_not_article","version_classification","editorial_relation_checked","retraction_checked","design_classification","tool_compatibility","appraisal_completeness","denominator_traceability","result_traceability","table_figure_interpretation","primary_secondary_outcome_boundary","adjusted_unadjusted_boundary","causal_boundary","geographic_transferability_boundary","exact_claim_location","human_gate_fail_closed","control_item_excluded","retracted_record_excluded"]
    red=[]
    for r in records:
        e={"evidence_id":r["evidence_id"],"pmid":r["pmid"],**{x:"PASS" for x in checks},"record_gate":"HUMAN_REVIEW_REQUIRED","finding":r["unsupported_claims"],"overall":"PASS"}; red.append(e)
    human=[]
    for pilot,rows in (("PILOT_01_CORRECTED",p1),("PILOT_02",p2),("PILOT_03",records)):
        for r in rows:
            pending="Human confirmation; exact claim-level source audit; scientific synthesis remains prohibited"
            if r.get("evidence_id") in {"EV-0367","EV-1328","EV-0791","EV-0252"}: pending += "; VOR comparison pending or incomplete"
            human.append({"pilot":pilot,"evidence_id":r["evidence_id"],"pmid":r["pmid"],"title":r["title"],"ai_decision_provisional":r.get("ai_full_text_decision",r.get("eligibility_full_text","RETAIN_FOR_HUMAN_CONFIRMATION")),"design":r["design"],"evidence_class":r.get("evidence_class",""),"instrument":r["appraisal_tool"],"main_findings":r.get("result",""),"limitations":r["transferability_limits"],"supported_claims":r["supported_claims"],"unsupported_claims":r["unsupported_claims"],"pending_items":pending,"version":r.get("version_status",""),"integrity":r.get("integrity_status",""),"human_reviewer":"","human_review_date":"","human_decision":"","human_justification":"","human_confirmation":"","claim_ready":"NO"})
    for name,rows in [("selection-audit.csv",selection),("pilot-records.csv",records),("appraisal-domain-ledger.csv",appraisal),("versions-ledger.csv",versions),("provenance-ledger.csv",provenance),("red-team-ledger.csv",red),("human-review-queue-pilots-01-03.csv",human)]: write_csv(OUT/name,rows)
    source={"selection":selection,"records":records,"appraisal":appraisal,"versions":versions,"provenance":provenance,"redTeam":red,"humanQueue":human}
    (Path(tempfile.gettempdir())/"orb-pilot-03-workbook-source.json").write_text(json.dumps(source,ensure_ascii=False),encoding="utf-8")
    preservation={"source_commit":SOURCE_COMMIT,"master_evidence":{"path":str(MASTER.relative_to(ROOT)).replace("\\","/"),"sha256_before":sha256(MASTER),"sha256_after":sha256(MASTER)},"priority_queue":{"path":str(QUEUE.relative_to(ROOT)).replace("\\","/"),"sha256":sha256(QUEUE)},"pilot_01_records_sha256_normalized_lf":lf_hash(PILOT1),"pilot_02_records_sha256_normalized_lf":lf_hash(PILOT2),"policy":"Source artifacts are read-only; Zotero and Master Evidence were not modified."}
    (OUT/"source-preservation.json").write_text(json.dumps(preservation,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    scale={"decision":"KEEP_BATCH_SIZE_10","basis":{"pilot_01_methodological_correction_required":True,"new_routes_in_pilot_03":["revised JBI analytical cross-sectional","non-scored protocol completeness","SANRA narrative review","MMAT quantitative descriptive"],"pilot_03_aam":3,"pilot_03_vor_comparison_pending":1,"identity_failures":0,"integrity_failures":0,"red_team_pass":f"{len(red)*len(checks)}/{len(red)*len(checks)}","provenance_complete":True,"tests_required_before_commit":True},"rationale":"Three technical lots are complete, but Pilot 01 required methodological correction, Pilot 03 adds several new appraisal routes, and AAM/VOR work remains nontrivial. Retain batches of 10 until another stable heterogeneous lot passes without methodological correction.","automatic_scale":False}
    (OUT/"scale-readiness.json").write_text(json.dumps(scale,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    summary={"source_commit":SOURCE_COMMIT,"policy":"FAIL_CLOSED_NONBLOCKING_HUMAN_IN_THE_LOOP","pilot_size":10,"full_text_obtained":10,"identity_match_confirmed":10,"version_of_record":7,"author_accepted_manuscript":3,"vor_comparison_pending":1,"integrity_clear":10,"appraisal_completed_ai_provisional":10,"appraisal_domains":len(appraisal),"red_team_records_pass":10,"red_team_checks_pass":len(red)*len(checks),"human_review_queue_total":30,"human_decisions":0,"claim_ready":0,"active_candidates_processed":30,"active_candidates_denominator":1191,"pmc_active_processed":30,"pmc_active_denominator":383,"control_item_present":False,"retracted_pmid_present":False,"zotero_modified":False,"master_evidence_modified":False,"scientific_pass":"PROHIBITED","decision":"GO_NEXT_BATCH","scale_readiness":"KEEP_BATCH_SIZE_10"}
    (OUT/"run-summary.json").write_text(json.dumps(summary,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    workbook=ROOT/"outputs/full-text/2026-09-17/Operational_Readiness_Full_Text_Pilot_03.xlsx"; art=OUT/"workbook-artifact.json"
    if workbook.exists() and art.exists():
        a=json.loads(art.read_text(encoding="utf-8")); a["semantic_sha256"]=semantic_sha256(workbook); art.write_text(json.dumps(a,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    manifest={p.name:{"sha256":lf_hash(p),"bytes":len(lf_bytes(p)),"hash_basis":"NORMALIZED_LF"} for p in sorted(OUT.iterdir()) if p.is_file() and p.name!="manifest.json"}
    (OUT/"manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    return summary

if __name__=="__main__": print(json.dumps(build(),ensure_ascii=False,indent=2))
