import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'batch10_4e';A=R/'batch10_4d';D={'HUMAN_DECISION':'KEEP_CURRENT','HUMAN_REVIEWER':'Matheus Florindo de Deus','HUMAN_REVIEW_DATE':'2026-10-06','HUMAN_RATIONALE':'After final comparative review of the current verified reference architecture and EV-1462, the current reference was retained because EV-1462 provides only partial and task-dependent evidence regarding caffeine during sleep deprivation and does not offer sufficient incremental claim fit to justify replacement without risking overstatement.'}
def rd(p):
 with p.open(encoding='utf-8-sig',newline='') as h:return list(csv.DictReader(h))
def wr(p,f,x):
 with p.open('w',encoding='utf-8',newline='') as h:w=csv.DictWriter(h,fieldnames=f);w.writeheader();w.writerows(x)
def main():
 names=['claim alignment','population directness','tactical/occupational relevance','study design','sample/evidence-base adequacy','outcome alignment','methodological quality','risk of bias','statistical informativeness','recency','generalizability','Brazil relevance','international relevance','incremental value','overlap/redundancy','integrity/provenance','citation fitness','suitability for exact manuscript wording']
 cur=['Supports active Brazilian shift-nutrition/vigilance claims.','Brazilian military police on shifts.','Direct police context.','Cross-sectional.','22 and 34 officers, limitations explicit.','Intake, meal timing, vigilance.','Bounded descriptive use.','No integrity block, noncausal wording.','Answers active claims.','2025/2026.','Bounded Brazil context.','Direct.','Bounded adaptation.','Preserves exact claims.','Distinct current roles.','Versioned QA clear.','Cited in both manuscripts.','Matches current wording.']
 ev=['PARTIAL_SUPPORT for absent caffeine/sleep claim.','Military or military-related sleep-loss populations.','Military operational context.','Systematic review/meta-analysis.','7 trials; aggregate N NR.','Vigilance, cognition, military tasks; not nutrition/shift claims.','AMSTAR2 LOW.','1 low, 5 some concerns, 1 high RoB.','SMD .73 vigilance, .54 cognition, .45 military task; task-dependent.','2026.','Moderately direct military; indirect Brazil police.','No direct validation.','Potentially contextual only.','New sentence required, no replacement gain.','Possible topic overlap, no cohort duplicate.','FT3R official route; no notice on versioned page, not database-wide clearance.','Uncited; human pending.','Must state partial mitigation, never restoration/prevention.']
 c=[{'Comparison_ID':'HR010-REPL-EV-1462','Dimension_Number':i+1,'Dimension':n,'Current_Reference_Set':'EV-1471 (Ref 3) + EV-1472 (Ref 4)','Current_Evidence':cur[i],'EV1462_Evidence':ev[i],'Finding_Favors':'CURRENT' if n not in {'recency','integrity/provenance'} else 'TIE','Source':'FT3R official provenance; FT4 extraction/appraisal; HR001 mapping; v0.13 reference audit','Final_Classification':'KEEP_CURRENT'} for i,n in enumerate(names)];wr(O/'HR010_REPLACEMENT_COMPARISON.csv',list(c[0]),c)
 x=[{'Claim_ID':'BR-NUTRITION-VIGILANCE','Manuscript':'Both','Section':'Nutrition and Schedule Load','Current_Wording':'Specific shift-related intake/vigilance association; no dietary causality.','Current_Citation':'EV-1471 / Ref 3','EV1462_Support':'NO_DIRECT_SUPPORT','Decision':'KEEP_CURRENT'},{'Claim_ID':'BR-CHRONONUTRITION-SHIFT','Manuscript':'Both','Section':'Nutrition and Schedule Load','Current_Wording':'Shift-associated meal timing and intake patterns; no prescription/performance effect.','Current_Citation':'EV-1472 / Ref 4','EV1462_Support':'NO_DIRECT_SUPPORT','Decision':'KEEP_CURRENT'},{'Claim_ID':'INT-SLEEP-CAFFEINE-MITIGATION','Manuscript':'International','Section':'NOT_PRESENT_AS_SUPPORTING_SECTION','Current_Wording':'NOT PRESENT AS A SUPPORTING CLAIM IN V0.13.','Current_Citation':'No assigned citation','EV1462_Support':'PARTIAL_SUPPORT; military settings only; requires a new narrowed sentence','Decision':'KEEP_CURRENT'}];wr(O/'HR010_CLAIM_IMPACT.csv',list(x[0]),x)
 over=[{'Control':'Caffeine solves/restores/prevents sleep-loss impairment','International':'0','Brazil':'0','Result':'PASS; claim absent and no support promotion'},{'Control':'Partial/task-dependent mitigation distinguished from restoration','International':'YES','Brazil':'YES','Result':'PASS'},{'Control':'Military-to-Brazil automatic transfer','International':'0','Brazil':'0','Result':'PASS'}];wr(O/'HR010_CAFFEINE_SLEEP_OVERCLAIM_AUDIT.csv',list(over[0]),over)
 p=[{'Evidence_ID':'EV-1462','Identity':'DOI 10.3389/fnut.2026.1893033; Frontiers in Nutrition 2026','Authorized_Route':'https://www.frontiersin.org/articles/10.3389/fnut.2026.1893033/full','Full_Text':'FT3R identity-verified final publisher route; HTTP 200; SHA256 34858223495881e39b82c514075dda586f179037f2069893d97b4f2764a27947','Invalid_Route':'FT3 shared PMCID/XML association rejected and not used','Integrity':'No notice observed on versioned page; not database-wide clearance','Result':'PROVENANCE_REMEDIATED_FT4'}];wr(O/'HR010_PROVENANCE_RECHECK.csv',list(p[0]),p)
 rec={'Review_ID':'HR-010','Evidence_ID':'EV-1462','Replacement_Relationship':'DETERMINISTIC: EV-1471; EV-1472','Final_Classification':'KEEP_CURRENT',**D,'Current_References_Retained':'EV-1471 (Ref 3); EV-1472 (Ref 4)','EV1462_Use':'Not promoted as support or replacement; no manuscript change.','Final_Reference_Freeze':'NO'};wr(O/'HR010_HUMAN_DECISION_RECORD.csv',list(rec),[rec])
 qp=A/'FINAL_HUMAN_REVIEW_QUEUE.csv';q=rd(qp)
 for r in q:
  if r['Review_ID']=='HR-010':r.update(D)
 wr(qp,list(q[0]),q);mp=A/'BATCH10_4D_MANIFEST.json';m=json.loads(mp.read_text());m['files'][qp.name]=hashlib.sha256(qp.read_bytes()).hexdigest();m.setdefault('human_adjudication_updates',{})['HR-010']={'evidence_id':'EV-1462','decision':'KEEP_CURRENT','reviewer':'Matheus Florindo de Deus','review_date':'2026-10-06','scope':'Retain EV-1471/EV-1472; no caffeine-support promotion.'};mp.write_text(json.dumps(m,indent=2)+'\n')
 (O/'HR010_REPORT.md').write_text('# HR-010 — EV-1462 final reference decision\n\nFT3R/FT4 confirm the official publisher route and reject the invalid shared PMCID/XML association. EV-1462 is a seven-trial military caffeine/sleep-loss meta-analysis (AMSTAR 2 LOW) with partial, task-dependent effects only. It does not replace the active Brazilian shift-nutrition claims of EV-1471/EV-1472. `KEEP_CURRENT` was conditionally authorized and recorded. No caffeine-restoration claim, manuscript change, Zotero/CEF-v1 mutation or final reference freeze occurred.\n\nGate: `HR010_ADJUDICATION_COMPLETE` and `HUMAN_ADJUDICATION_COMPLETE`; next authorized gate only: `BATCH 10.4F — FINAL REFERENCE FREEZE + CLAIM/CITATION RECONCILIATION`.\n')
if __name__=='__main__':main()
