import csv, json, hashlib, re, datetime
from pathlib import Path
from docx import Document

R=Path(__file__).resolve().parents[1]
OUT=R/'batch11_3'; OUT.mkdir(exist_ok=True)
DATE='2026-10-11'
DOCX=R/'batch11_2h/International_v1.3-FINAL-SCIENTIFIC-FREEZE.docx'
MD=R/'batch11_2h/International_v1.3-FINAL-SCIENTIFIC-FREEZE.md'

def write_csv(name, rows, fields=None):
    fields=fields or list(rows[0])
    with (OUT/name).open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
def sha(path): return hashlib.sha256(path.read_bytes().replace(b'\r\n', b'\n')).hexdigest()
def words(s): return len(re.findall(r"\b[\w’'-]+\b",s))
def score(row):
    weights={'Scope_Fit':.22,'Type_Fit':.18,'Tactical_Fit':.14,'Length_Fit':.12,'Evidence_Fit':.12,'Visibility':.10,'Practicality':.05,'Cost_Access':.03,'Burden':.04}
    return round(sum(float(row[k])*weights[k] for k in weights)*10,1)

before={'docx_sha256':sha(DOCX),'markdown_sha256':sha(MD)}
md=MD.read_text(encoding='utf-8'); doc=Document(DOCX)
abstract=re.search(r'## Abstract\n\n(.*?)(?=\n\n\*\*Keywords)',md,re.S).group(1)
pre_refs=md.split('## References')[0]
body=pre_refs[pre_refs.index('## Introduction'):]
counts={'Abstract_Words':words(abstract),'Body_Words':words(body),'Total_DOCX_Words':words('\n'.join(p.text for p in doc.paragraphs)),'References':len(re.findall(r'^\d+\. ',md,re.M)),'Tables':len(doc.tables),'Figures':0,'Framework':'PROPOSED SYNTHESIS FRAMEWORK — NOT YET VALIDATED','Rendered_Pages':11,'Supplementary_Material':'NONE_CURRENTLY'}

urls={
'JOH':'https://academic.oup.com/joh/pages/author-guidelines',
'OM':'https://academic.oup.com/occmed/pages/author-guidelines',
'MM':'https://academic.oup.com/milmed/pages/General_Instructions',
'FPH':'https://www.frontiersin.org/journals/public-health/sections/digital-public-health/for-authors/article-types',
'JSOM':'https://jsom.scholasticahq.com/for-authors',
'BMJMH':'https://militaryhealth.bmj.com/pages/authors',
'JSAMS':'https://www.elsevier.com/journals/journal-of-science-and-medicine-in-sport/1440-2440/guide-for-authors',
'MMR':'https://link.springer.com/journal/40779/submission-guidelines',
'SHW':'https://www.sciencedirect.com/journal/safety-and-health-at-work',
'JOHP':'https://www.apa.org/pubs/journals/ocp/submit',
}
long=[
 {'Journal':'Journal of Occupational Health','Publisher':'Oxford University Press / Japan Society for Occupational Health','Official_URL':urls['JOH'],'Screen_Status':'FULLY_AUDITED_TOP3','Reason':'Direct occupational-health scope; explicit review category compatible with the frozen manuscript.'},
 {'Journal':'Occupational Medicine','Publisher':'Oxford University Press / Society of Occupational Medicine','Official_URL':urls['OM'],'Screen_Status':'FULLY_AUDITED_TOP3','Reason':'Qualitative review route and occupational-practitioner audience fit the evidence-governance framing.'},
 {'Journal':'Military Medicine','Publisher':'Oxford University Press / AMSUS','Official_URL':urls['MM'],'Screen_Status':'FULLY_AUDITED_TOP3','Reason':'Explicit review-article route and strong tactical/military audience, with manageable length adjustment later.'},
 {'Journal':'Frontiers in Public Health','Publisher':'Frontiers','Official_URL':urls['FPH'],'Screen_Status':'FULLY_AUDITED_TOP5','Reason':'Full-length Review category can accommodate the manuscript but public-health breadth and APC lower priority.'},
 {'Journal':'Journal of Special Operations Medicine','Publisher':'Special Operations Medical Association','Official_URL':urls['JSOM'],'Screen_Status':'FULLY_AUDITED_TOP5','Reason':'Official review category and tactical-medicine audience, but the broader occupational focus creates desk-fit risk.'},
 {'Journal':'BMJ Military Health','Publisher':'BMJ','Official_URL':urls['BMJMH'],'Screen_Status':'EXCLUDED_INITIAL','Reason':'The self-initiated review route is not confirmed; the author page separates Invited Review and Systematic Review.'},
 {'Journal':'Journal of Science and Medicine in Sport','Publisher':'Elsevier / Sports Medicine Australia','Official_URL':urls['JSAMS'],'Screen_Status':'EXCLUDED_ARTICLE_TYPE_MISMATCH','Reason':'Non-systematic reviews are invitation-only; systematic/scoping/meta-analysis route is incompatible with the frozen design.'},
 {'Journal':'Military Medical Research','Publisher':'Elsevier / KeAi','Official_URL':urls['MMR'],'Screen_Status':'NOT_ADVANCED','Reason':'Potential scope fit, but current review-category requirements were not sufficiently verified in this audit.'},
 {'Journal':'Safety and Health at Work','Publisher':'Elsevier / Occupational Safety and Health Research Institute','Official_URL':urls['SHW'],'Screen_Status':'NOT_ADVANCED','Reason':'Potential occupational-safety fit; no current official detailed review requirements verified here.'},
 {'Journal':'Journal of Occupational Health Psychology','Publisher':'American Psychological Association','Official_URL':urls['JOHP'],'Screen_Status':'NOT_ADVANCED','Reason':'Psychology-centered audience is too narrow for the cross-domain tactical and medical-readiness manuscript.'},
]
write_csv('FULL_LENGTH_JOURNAL_LONG_LIST.csv',long)

# Top-five data is deliberately conservative: unknown values are not inferred.
top=[
 {'Rank':1,'Journal':'Journal of Occupational Health','Publisher':'Oxford University Press / Japan Society for Occupational Health','Official_URL':urls['JOH'],'Scope':'Broad occupational health, workers, occupational-health practices and related issues.','Compatible_Category':'Review Article','Article_Type_Compatible':'YES','Word_Limit':'6000','Abstract_Limit':'250 structured','Reference_Limit':'No limit','Table_Figure_Limit':'6','Supplementary':'Supported','Language':'English','Citation_Style':'Journal style; final verification required','Abstract_Structure':'Objectives; Methods; Results; Conclusions','APC_Model':'MANDATORY_APC','APC_Current':'Amount dynamically quoted by OUP selector; exact rate not independently reproducible without author/institution inputs','APC_Status':'CURRENT_AMOUNT_NOT_VERIFIED','Indexing':'MEDLINE/PubMed/PMC VERIFIED via NLM Catalog','Integrity':'JOURNAL_INTEGRITY_PASS','Review_Model':'Single-anonymized','Main_Risk':'Must present the frozen synthesis as a review/evaluation, not as a systematic review; add required Key Points at adaptation.','Required_Modifications':'Journal formatting only: structured abstract, Key Points, declarations, title page.','Desk_Risk':'LOW','Scope_Fit':10,'Type_Fit':10,'Tactical_Fit':8,'Length_Fit':10,'Evidence_Fit':9,'Visibility':9,'Practicality':8,'Cost_Access':5,'Burden':7},
 {'Rank':2,'Journal':'Occupational Medicine','Publisher':'Oxford University Press / Society of Occupational Medicine','Official_URL':urls['OM'],'Scope':'Occupational medicine and occupational-health practice.','Compatible_Category':'Qualitative review route described under review guidance','Article_Type_Compatible':'YES_WITH_EDITORIAL_CHECK','Word_Limit':'5000','Abstract_Limit':'250 structured','Reference_Limit':'70','Table_Figure_Limit':'6','Supplementary':'Up to 10 files','Language':'English','Citation_Style':'Journal style; final verification required','Abstract_Structure':'Background; Aims; Methods; Results; Conclusions','APC_Model':'OPTIONAL_OA','APC_Current':'No standard-licence charge; optional-OA amount requires OUP selector','APC_Status':'CURRENT_OPTIONAL_AMOUNT_NOT_VERIFIED','Indexing':'PubMed VERIFIED; MEDLINE status not independently rechecked in this batch','Integrity':'JOURNAL_INTEGRITY_PASS','Review_Model':'Not stated in guideline extract','Main_Risk':'Title/category wording and search-method paragraph require editorial-fit confirmation; scope must foreground occupational-health implications.','Required_Modifications':'Journal formatting only: structured abstract, teaser, key learning points, search-method paragraph, declarations.','Desk_Risk':'LOW','Scope_Fit':10,'Type_Fit':9,'Tactical_Fit':7,'Length_Fit':10,'Evidence_Fit':9,'Visibility':8,'Practicality':9,'Cost_Access':9,'Burden':7},
 {'Rank':3,'Journal':'Military Medicine','Publisher':'Oxford University Press / AMSUS','Official_URL':urls['MM'],'Scope':'Federal and international health professionals; military medicine and policy/practice.','Compatible_Category':'Review Article (narrative reviews acknowledged)','Article_Type_Compatible':'YES','Word_Limit':'4000','Abstract_Limit':'250–500 structured summary','Reference_Limit':'40','Table_Figure_Limit':'4','Supplementary':'Supported','Language':'English','Citation_Style':'Journal style; final verification required','Abstract_Structure':'Introduction; Materials and Methods; Results; Conclusions','APC_Model':'OPTIONAL_OA_PLUS_SUBMISSION_FEE','APC_Current':'USD 125 non-member submission fee; optional-OA amount requires OUP selector','APC_Status':'SUBMISSION_FEE_VERIFIED_OA_AMOUNT_NOT_VERIFIED','Indexing':'PubMed VERIFIED; MEDLINE status not independently rechecked in this batch','Integrity':'JOURNAL_INTEGRITY_PASS','Review_Model':'Single-anonymized','Main_Risk':'Current 4205-word body exceeds 4000-word cap by 205 words; police/firefighter breadth may dilute federal-medicine framing.','Required_Modifications':'Later editorial adaptation: modest ≤205-word reduction, structured summary, title page and declarations.','Desk_Risk':'MODERATE','Scope_Fit':8,'Type_Fit':9,'Tactical_Fit':10,'Length_Fit':7,'Evidence_Fit':8,'Visibility':9,'Practicality':7,'Cost_Access':7,'Burden':7},
 {'Rank':4,'Journal':'Frontiers in Public Health','Publisher':'Frontiers','Official_URL':urls['FPH'],'Scope':'Public-health journal; selected author-guideline page explicitly supports Review articles.','Compatible_Category':'Review','Article_Type_Compatible':'YES_WITH_SECTION_CONFIRMATION','Word_Limit':'12000','Abstract_Limit':'Not separately stated in selected guideline extract','Reference_Limit':'Not stated','Table_Figure_Limit':'Not stated for Review in selected extract','Supplementary':'Supported','Language':'English','Citation_Style':'Frontiers style; final verification required','Abstract_Structure':'Abstract; Introduction; subsections; Discussion','APC_Model':'MANDATORY_APC','APC_Current':'CHF 3,150 listed by Frontiers fee page for Frontiers in Public Health; category/section confirmation required','APC_Status':'VERIFIED_JOURNAL_LEVEL','Indexing':'MEDLINE/PubMed/PMC VERIFIED via NLM Catalog','Integrity':'JOURNAL_INTEGRITY_PASS','Review_Model':'Peer reviewed; model not separately recorded','Main_Risk':'Public-health section fit may be broader than the manuscript; mandatory APC and section-level article-type confirmation needed.','Required_Modifications':'Later editorial adaptation only; retain Review rather than Mini Review.','Desk_Risk':'MODERATE','Scope_Fit':7,'Type_Fit':9,'Tactical_Fit':6,'Length_Fit':10,'Evidence_Fit':8,'Visibility':9,'Practicality':7,'Cost_Access':3,'Burden':7},
 {'Rank':5,'Journal':'Journal of Special Operations Medicine','Publisher':'Special Operations Medical Association','Official_URL':urls['JSOM'],'Scope':'Emergency medicine in military, tactical, wilderness and austere environments.','Compatible_Category':'Review','Article_Type_Compatible':'YES_WITH_LIMITS_PENDING','Word_Limit':'Not stated on official landing page; full requirements PDF needed before choice','Abstract_Limit':'Not stated on landing page','Reference_Limit':'Not stated on landing page','Table_Figure_Limit':'Not stated on landing page','Supplementary':'Not verified','Language':'English','Citation_Style':'Not verified','Abstract_Structure':'Not verified','APC_Model':'APC_UNCLEAR','APC_Current':'Not verified','APC_Status':'NOT_VERIFIED','Indexing':'NOT_VERIFIED in this audit','Integrity':'JOURNAL_INTEGRITY_PASS','Review_Model':'Peer-review minimum 90 days stated','Main_Risk':'Clinical/tactical-medicine scope may be too narrow for readiness governance across police, firefighters and military.','Required_Modifications':'Would require author-requirements review before any human selection; no manuscript changes proposed.','Desk_Risk':'HIGH','Scope_Fit':6,'Type_Fit':6,'Tactical_Fit':10,'Length_Fit':5,'Evidence_Fit':6,'Visibility':4,'Practicality':5,'Cost_Access':5,'Burden':5},
]
for r in top:r['Weighted_Fit_Score']=score(r)
write_csv('TOP5_JOURNAL_COMPARISON.csv',top)
write_csv('FULL_LENGTH_JOURNAL_ELIGIBILITY_AUDIT.csv',[{'Journal':r['Journal'],'Eligibility':'ELIGIBLE' if int(r['Rank'])<=4 else 'CONDITIONAL','Mini_Review_Reversion':'PROHIBITED','Systematic_Review_Mislabeling':'PROHIBITED','Article_Type_Status':r['Article_Type_Compatible'],'Scientific_Freeze_Mutation':'0','Rationale':r['Main_Risk']} for r in top])
write_csv('CURRENT_AUTHOR_GUIDELINES_AUDIT.csv',[{'Journal':r['Journal'],'Official_URL':r['Official_URL'],'Access_Date':DATE,'Article_Type':r['Compatible_Category'],'Word_Limit':r['Word_Limit'],'Abstract_Limit':r['Abstract_Limit'],'Reference_Limit':r['Reference_Limit'],'Table_Figure_Limit':r['Table_Figure_Limit'],'Declarations':'See requirement-gap matrix','Verification':'OFFICIAL_GUIDELINE_VERIFIED' if int(r['Rank'])<=3 else 'OFFICIAL_PAGE_VERIFIED_LIMITS_PARTIAL'} for r in top])
write_csv('ARTICLE_TYPE_COMPATIBILITY.csv',[{'Journal':r['Journal'],'Frozen_Design':'Evidence-informed integrative synthesis with explicit evidence-governance framework','Candidate_Type':r['Compatible_Category'],'Compatible':r['Article_Type_Compatible'],'Systematic_Review_Claim_Required':'NO','Mislabeling_Risk':'NO' if r['Article_Type_Compatible'].startswith('YES') else 'YES','Decision':'RETAIN_FOR_COMPARISON' if int(r['Rank'])<=4 else 'CONDITIONAL_ONLY'} for r in top]+[{'Journal':'Journal of Science and Medicine in Sport','Frozen_Design':'Evidence-informed integrative synthesis with explicit evidence-governance framework','Candidate_Type':'Review Articles','Compatible':'NO','Systematic_Review_Claim_Required':'YES_OR_INVITATION','Mislabeling_Risk':'YES','Decision':'EXCLUDE_ARTICLE_TYPE_MISMATCH'}])
index=[
 {'Journal':'Journal of Occupational Health','PubMed_MEDLINE':'VERIFIED','Scopus':'NOT_VERIFIED','Web_of_Science':'NOT_VERIFIED','DOAJ':'NOT_VERIFIED','Evidence_URL':'https://www.ncbi.nlm.nih.gov/nlmcatalog/9616320','Access_Date':DATE},
 {'Journal':'Occupational Medicine','PubMed_MEDLINE':'PUBMED_VERIFIED_MEDLINE_NOT_RECHECKED','Scopus':'NOT_VERIFIED','Web_of_Science':'NOT_VERIFIED','DOAJ':'NOT_APPLICABLE_HYBRID','Evidence_URL':'https://pubmed.ncbi.nlm.nih.gov/40726323/','Access_Date':DATE},
 {'Journal':'Military Medicine','PubMed_MEDLINE':'PUBMED_VERIFIED_MEDLINE_NOT_RECHECKED','Scopus':'NOT_VERIFIED','Web_of_Science':'NOT_VERIFIED','DOAJ':'NOT_APPLICABLE_HYBRID','Evidence_URL':'https://pubmed.ncbi.nlm.nih.gov/42692423/','Access_Date':DATE},
 {'Journal':'Frontiers in Public Health','PubMed_MEDLINE':'VERIFIED','Scopus':'NOT_VERIFIED','Web_of_Science':'NOT_VERIFIED','DOAJ':'NOT_VERIFIED','Evidence_URL':'https://www.ncbi.nlm.nih.gov/nlmcatalog/101616579','Access_Date':DATE},
 {'Journal':'Journal of Special Operations Medicine','PubMed_MEDLINE':'NOT_VERIFIED','Scopus':'NOT_VERIFIED','Web_of_Science':'NOT_VERIFIED','DOAJ':'NOT_VERIFIED','Evidence_URL':urls['JSOM'],'Access_Date':DATE},]
write_csv('JOURNAL_INDEXING_VERIFICATION.csv',index)
apc=[{'Journal':r['Journal'],'Model':r['APC_Model'],'Current_Cost':r['APC_Current'],'Verification_Status':r['APC_Status'],'Waiver_Discount':'See official publisher policy; no eligibility assumed','Source_URL':r['Official_URL'],'Access_Date':DATE} for r in top]
write_csv('JOURNAL_APC_AUDIT.csv',apc)
metrics=[{'Journal':'BMJ Military Health','Metric':'Impact Factor','Value':'1.7','Metric_Year':'Current value displayed on official journal page accessed '+DATE,'Source_URL':'https://militaryhealth.bmj.com/','Status':'VERIFIED_BUT_JOURNAL_NOT_ADVANCED'},{'Journal':'BMJ Military Health','Metric':'CiteScore','Value':'3.6','Metric_Year':'Current value displayed on official journal page accessed '+DATE,'Source_URL':'https://militaryhealth.bmj.com/','Status':'VERIFIED_BUT_JOURNAL_NOT_ADVANCED'}]+[{'Journal':r['Journal'],'Metric':'Current metric','Value':'NOT_RECORDED','Metric_Year':'N/A','Source_URL':r['Official_URL'],'Status':'NOT_VERIFIED_NOT_USED_IN_RANKING'} for r in top]
write_csv('JOURNAL_METRICS_VERIFICATION.csv',metrics)
write_csv('JOURNAL_INTEGRITY_SCREEN.csv',[{'Journal':r['Journal'],'Publisher_or_Official_Site_Verified':'YES','Author_Guideline_or_Official_Article_Page':'YES','Indexing_or_Publisher_Traceability':'YES' if r['Journal']!='Journal of Special Operations Medicine' else 'PARTIAL','Deceptive_Practice_Signal':'NONE_IDENTIFIED_IN_SCOPE_OF_THIS_AUDIT','Result':'JOURNAL_INTEGRITY_PASS'} for r in top])
write_csv('TOP3_JOURNAL_DEEP_FIT_AUDIT.csv',[{'Rank':r['Rank'],'Journal':r['Journal'],'Positioning':'A bounded, evidence-informed integrative synthesis of operational-readiness evidence across tactical and public-safety workforces, emphasizing transferability and evidence governance.','Advantage':('Direct occupational-health review category with 6000-word capacity.' if r['Rank']==1 else 'Occupational-medicine readership and explicit qualitative-review route.' if r['Rank']==2 else 'Direct tactical and military readership with an explicit narrative-review route.'),'Principal_Risk':r['Main_Risk'],'Editorial_Changes_Later':r['Required_Modifications'],'Cost':r['APC_Current'],'Desk_Rejection_Risk':r['Desk_Risk'],'Recommendation':('BEST_SCIENTIFIC_FIT' if r['Rank']==1 else 'STRONG_ALTERNATIVE' if r['Rank']==2 else 'CONSERVATIVE_PRACTICAL_ALTERNATIVE')} for r in top[:3]])
write_csv('DESK_REJECTION_RISK_MATRIX.csv',[{'Journal':r['Journal'],'Risk':r['Desk_Risk'],'Scope_Mismatch':r['Main_Risk'],'Type_Mismatch':'LOW' if r['Article_Type_Compatible'].startswith('YES') else 'HIGH','Length_Status':'WITHIN_LIMIT' if r['Journal']!='Military Medicine' else '205_WORD_REDUCTION_NEEDED','Novelty_Risk':'MODERATE—position contribution as bounded cross-domain synthesis, not first-ever claim','Mitigation':'Use frozen evidence-governance framing and never call it systematic unless formally redesigned.'} for r in top])
req=[]
for r in top[:3]:
    req.append({'Journal':r['Journal'],'Requirement':'Word count','Current_Manuscript':str(counts['Body_Words'])+' body words','Target':r['Word_Limit'],'Gap':'NONE' if r['Journal']!='Military Medicine' else 'REDUCE_UP_TO_205_WORDS_LATER','Allowed_Now':'NO_MANUSCRIPT_EDIT'})
    req.append({'Journal':r['Journal'],'Requirement':'Abstract','Current_Manuscript':str(counts['Abstract_Words'])+' unstructured','Target':r['Abstract_Limit'],'Gap':'RESTRUCTURE_LATER','Allowed_Now':'NO_MANUSCRIPT_EDIT'})
    req.append({'Journal':r['Journal'],'Requirement':'Declarations/title page','Current_Manuscript':'Not journal-packaged','Target':'Journal-specific submission package','Gap':'CREATE_LATER','Allowed_Now':'NO_MANUSCRIPT_EDIT'})
write_csv('MANUSCRIPT_TO_JOURNAL_REQUIREMENT_GAP.csv',req)
queue=[{'Rank':r['Rank'],'Journal':r['Journal'],'Key_Rationale':r['Advantage'] if 'Advantage' in r else r['Scope'],'APC':r['APC_Current'],'Indexing':next(x['PubMed_MEDLINE'] for x in index if x['Journal']==r['Journal']),'Article_Type':r['Compatible_Category'],'Word_Limit':r['Word_Limit'],'Major_Risk':r['Main_Risk'],'HUMAN_SELECTION':'','Human_Reviewer':'','Human_Selection_Date':'','Human_Rationale':''} for r in top[:3]]
write_csv('TARGET_JOURNAL_HUMAN_DECISION_QUEUE.csv',queue)
red='''# Journal selection red team\n\n## Rank 1 — Journal of Occupational Health\nThe editor could reject it if the operational-readiness framing appears too diffuse across occupations. The explicit Review Article category is compatible; the manuscript must remain a review/evaluation rather than imply a systematic search. The framework is acceptable only as proposed and unvalidated. The 28 references and current length are within published limits.\n\n## Rank 2 — Occupational Medicine\nThe central risk is category interpretation: the official guidance describes a qualitative review route while its heading uses “Systematic Reviews”. A presubmission query is prudent. The manuscript fits the 5,000-word/70-reference limits but should foreground occupational clinical implications.\n\n## Rank 3 — Military Medicine\nThe main desk risks are breadth beyond military/federal medicine and the 4,000-word cap. The official guidance acknowledges narrative reviews, but the body would need a modest later reduction. No claim should be reclassified as systematic solely for this outlet.\n\n## Cross-cutting finding\nNo outlet was selected automatically. The v1.3 manuscript, claims, CEF-v1, Zotero, Brazil, and reference set were not altered.\n'''
(OUT/'JOURNAL_SELECTION_RED_TEAM.md').write_text(red,encoding='utf-8')
# Snapshot and reproducibility checks.
after={'docx_sha256':sha(DOCX),'markdown_sha256':sha(MD)}
assert before==after
manifest={'batch':'BATCH 11.3','access_date':DATE,'base_commit':'e0bf16c91bce66389f1f2144bbc3f1de5e0d9e67','gate':'FULL_LENGTH_TARGET_JOURNAL_FIT_AUDIT_PASS','next_gate':'GO_TARGET_JOURNAL_HUMAN_SELECTION','manuscript_snapshot':before,'manuscript_facts':counts,'qa':{'journals_initially_screened':10,'journals_fully_audited':5,'top5':5,'top3':3,'official_author_guideline_verification_top3':'3/3','article_type_compatibility_top3':'3/3','current_apc_verified_top3':'0/3 exact amounts; model/status 3/3','indexing_verified_top3':'3/3 PubMed or MEDLINE evidence','integrity_screen_pass_top3':'3/3','manuscript_scientific_mutations':0,'claim_mutations':0,'cef_mutations':0,'zotero_mutations':0,'brazil_mutations':0,'human_selection_populated':0}}
files=[]
for p in sorted(OUT.iterdir()):
    if p.is_file() and p.name not in {'BATCH11_3_MANIFEST.json','BATCH11_3_REPORT.md'}: files.append({'file':p.name,'sha256':sha(p)})
manifest['outputs']=files
(OUT/'BATCH11_3_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
report=f'''# Batch 11.3 report\n\n## Decision\n\n`FULL_LENGTH_TARGET_JOURNAL_FIT_AUDIT_PASS`\n\n`GO_TARGET_JOURNAL_HUMAN_SELECTION`\n\n## Recommendation\n\nRank 1 is **Journal of Occupational Health**. Its official Review Article category permits 6,000 words, a 250-word structured abstract, unlimited references, and six tables/figures. The frozen body has {counts['Body_Words']} words, {counts['References']} references, no tables, and no figures, so no scientific compression is required for fit.\n\nRank 2 is **Occupational Medicine**; its qualitative-review guidance allows 5,000 words and 70 references, but a presubmission category query is recommended. Rank 3 is **Military Medicine**; it accepts narrative reviews but its 4,000-word cap requires a later editorial reduction of up to {counts['Body_Words']-4000} words.\n\nNo journal was selected. No manuscript, claim, CEF-v1, Zotero, Brazil, or reference mutation occurred.\n'''
(OUT/'BATCH11_3_REPORT.md').write_text(report,encoding='utf-8')
print(json.dumps({'body_words':counts['Body_Words'],'journals':len(long),'top5':len(top),'top3':3,'snapshot_unchanged':before==after},indent=2))
