"""Batch 10.4H-GAP: targeted result extraction from pre-versioned eligible candidates."""
import csv,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'batch10_4h_gap'; OUT.mkdir(exist_ok=True)
def read(p):
 with (ROOT/p).open(encoding='utf-8-sig',newline='') as h:return list(csv.DictReader(h))
def write(n,f,rows):
 with (OUT/n).open('w',encoding='utf-8',newline='') as h:
  w=csv.DictWriter(h,fieldnames=f,extrasaction='ignore');w.writeheader();w.writerows(rows)
def main():
 source={r['Evidence_ID']:r for r in read('batch10_4b/ft1/artifacts/PMC100_FULL_TEXT_EXTRACTION.csv')}
 app={r['Evidence_ID']:r for r in read('batch10_4b/ft1/artifacts/PMC100_APPRAISAL_LEDGER.csv')}
 old=read('batch10_4g/NEW_CLAIM_LIBRARY.csv')
 specs=[
 ('RC-GAP-INT-NUTR-01','EV-0426','EV-0426-GAP-R01','In a systematic review of 16 controlled military studies, dietary-supplement findings were inconsistent and mostly modest, and the authors judged practical field-performance guidance inadequate.','SUPPORTING_CLAIM','International only','Nutrition / supplementation','Results 3 and Table 3; Limitations 4.4; Conclusions 5.','Systematic review of randomized and quasi-experimental controlled trials','Military personnel','CRITICALLY_LOW_CONFIDENCE','Does not justify a general supplementation protocol, causal field-readiness claim, or direct transfer to Brazilian public safety.'),
 ('RC-GAP-INT-NUTR-02','EV-0521','EV-0521-GAP-R01','In 30 male firefighters receiving protein-carbohydrate regimens, adding creatine was associated with larger improvements in rescue and forcible-entry task times; several other tasks and total time showed no group-time interaction.','SUPPORTING_CLAIM','International only','Nutrition / supplementation','Results 4; Table 1; Figures 2-3; Conclusions 6.','Randomized parallel-group double-blind controlled trial','30 male firefighters','SOME_CONCERNS','Does not show that protein/carbohydrate alone caused benefit, that every occupational task improved, or that results generalize to female firefighters or Brazilian agencies.'),
 ('RC-GAP-INT-PHYS-01','EV-0204','EV-0204-GAP-R01','In 216 recruits followed for 12 months at one Chinese police academy, higher graduation-stage composite fitness was associated with higher supervisor-rated job performance and lower musculoskeletal-injury hazard; the cohort does not establish a causal effect of testing or conditioning.','SUPPORTING_CLAIM','International only','Physical fitness / academy readiness','Results Table 1 and multivariable regression results; Limitations.','Prospective cohort','216 followed recruits at one Chinese police academy','SOME_CONCERNS','Does not prove that fitness testing, assignment, or conditioning causes lower injury or better performance.'),
 ('RC-GAP-INT-MEAS-01','EV-0667','EV-0667-GAP-R01','Among 34 Slovenian infantry personnel, end-running speed, maximal heart rate and predicted VO2max from the 30-15 intermittent fitness test showed test-retest ICCs of 0.971, 0.960 and 0.975, respectively; this does not validate a readiness score or operational prediction in other populations.','SUPPORTING_CLAIM','International only','Physical fitness / academy readiness','Results and Table 2; Tables 3-5; Conclusion.','Within-subject test-retest and criterion-validity study','34 Slovenian infantry members','SOME_CONCERNS','Does not validate the test for Brazilian policing, establish combat readiness, or prove outcome prediction beyond this small infantry cohort.')]
 extracted=[]; claims=[]; integrity=[]; appraisal=[]
 for cid,eid,rid,claim,strength,eligible,domain,locator,design,pop,quality,boundary in specs:
  s=source[eid];a=app[eid]
  extracted.append({'Evidence_ID':eid,'Result_ID':rid,'Title':s['Title'],'PMID':s['PMID'],'PMCID':s['PMCID'],'DOI':s['DOI'],'Full_Text_Source':s['Full_Text_Source'],'Source_Locator':locator,'Exact_Result':s['Relevant_Result'],'Study_Design':design,'Population':pop,'Result_Extraction_Status':'EXTRACTED_FROM_PREVIOUSLY_VERSIONED_LAWFUL_FULL_TEXT','Human_Confirmation':'PENDING'})
  claims.append({'Reconstruction_Claim_ID':cid,'Exact_Proposed_Claim':claim,'Evidence_ID':eid,'Result_ID':rid,'Source_Locator':locator,'Support_Type':strength,'Population':pop,'Design':design,'Certainty':f'AI-provisional; {quality}; human confirmation pending','Transferability':'International source; no automatic Brazil transfer.','International_Eligible':'YES','Brazil_Eligible':'NO','Proposed_Section':domain,'Eligibility_for_Reconstruction':'CONDITIONAL_PENDING_HUMAN_REVIEW','Claim_Boundary':boundary})
  appraisal.append({'Evidence_ID':eid,'Result_ID':rid,'Appraisal_Instrument':a['Appraisal_Instrument'],'Appraisal_Overall_AI':a['Appraisal_Overall_AI'],'Appraisal_Rationale':a['Appraisal_Rationale'],'Decision':'CONDITIONAL_RESULT_LEVEL_USE_ONLY','Human_Confirmation':'PENDING'})
  integrity.append({'Evidence_ID':eid,'PMID':s['PMID'],'PMCID':s['PMCID'],'Integrity_Status':'NO_NOTICE_OBSERVED_ON_OFFICIAL_PUBMED_PAGE_2026-10-08_NOT_DATABASE_WIDE_CLEARANCE','Source':'Official PubMed page; pre-versioned lawful PMC full text','Decision':'No automatic final-reference promotion; human review pending.'})
 write('GAP_CLOSURE_RESULT_EXTRACTION.csv',list(extracted[0]),extracted);write('GAP_CLOSURE_NEW_CLAIMS.csv',list(claims[0]),claims);write('GAP_CLOSURE_APPRAISAL_LEDGER.csv',list(appraisal[0]),appraisal);write('GAP_CLOSURE_INTEGRITY_LEDGER.csv',list(integrity[0]),integrity)
 # Preserve history: write updated views, do not overwrite Batch 10.4G originals.
 allclaims=old+[{k:v for k,v in c.items() if k in old[0]} for c in claims]
 write('UPDATED_RECONSTRUCTION_CLAIM_LIBRARY.csv',list(old[0]),allclaims)
 gaps=read('batch10_4g/RECONSTRUCTION_GAP_MATRIX.csv')
 for g in gaps:
  if g['Domain']=='Nutrition / supplementation':
   g.update({'Evidence_Available':'Two result-located international sources: one military systematic review and one firefighter trial; contradictory dietary-fat HIGH evidence remains unresolved.','Result_ID_Count':'2','Independent_Cohort_Count':'2','Evidence_Quality':'AI-provisional; critical-low to some-concerns appraisal; human confirmation pending','Gap':'YES','Action':'DISCUSSION_ONLY'})
  if g['Domain']=='Physical fitness / academy readiness':
   g.update({'Evidence_Available':'One Chinese prospective police cohort and one Slovenian infantry measurement study; contradictory HIGH evidence remains unresolved.','Result_ID_Count':'2','Independent_Cohort_Count':'2','Evidence_Quality':'AI-provisional; some-concerns appraisal; human confirmation pending','Gap':'YES','Action':'NARROW'})
 write('UPDATED_RECONSTRUCTION_GAP_MATRIX.csv',list(gaps[0]),gaps)
 inv=read('batch10_4g/RECONSTRUCTION_EVIDENCE_INVENTORY.csv')
 for row in inv:
  if row['Evidence_ID'] in {x['Evidence_ID'] for x in claims}:
   row['Result_Level_Data_Available']='YES';row['Eligibility_for_Reconstruction']='CONDITIONAL_RESULT_LEVEL_USE_PENDING_HUMAN_REVIEW';row['Provenance']=row['Provenance']+'; Batch10_4H-GAP'
 write('UPDATED_RECONSTRUCTION_EVIDENCE_INVENTORY.csv',list(inv[0]),inv)
 remaining=[{'Domain':'Nutrition / supplementation','Remaining_Gap':'EV-0140 contradictory HIGH remains unadjudicated; Brazilian direct evidence absent.','Needed':'Lawful full text/adjudication of EV-0140 and independent Brazil-relevant result-located evidence.'},{'Domain':'Physical fitness / academy readiness','Remaining_Gap':'EV-0052 and EV-1066 contradictory HIGH remain unadjudicated; no Brazilian prospective replication.','Needed':'Lawful full-text adjudication and independent Brazil-relevant prospective evidence.'},{'Domain':'Hydration / heat','Remaining_Gap':'No reconstruction-ready result packet.','Needed':'Targeted lawful full text with result-level extraction.'},{'Domain':'Brazil evidence density','Remaining_Gap':'New recovery added no Brazil-eligible result-located source.','Needed':'Independent Brazilian public-safety studies with result-level provenance.'}]
 write('GAP_CLOSURE_REMAINING_GAPS.csv',list(remaining[0]),remaining)
 report='''# BATCH 10.4H-GAP — targeted evidence gap closure\n\n## Decision\n\n`TARGETED_GAP_CLOSURE_INSUFFICIENT`\n\n## What advanced\n\nFour already-versioned, lawful full-text sources were extracted at result level: EV-0426, EV-0521, EV-0204 and EV-0667. They add four bounded, International-only, AI-provisional claims. No candidate was promoted to a final reference or Claim-Ready.\n\n## Why the gate remains insufficient\n\nThe recovered sources improve nutrition and physical/academy evidence boundaries, but do not resolve the three access-limited contradictory HIGH records (EV-0052, EV-0140 and EV-1066), the hydration/heat gap, or the deficit of independent Brazilian result-located evidence. The v0.15 manuscripts remain unchanged.\n\n## Controls\n\n- No new broad search, Zotero write, CEF-v1 change, manuscript change, reference freeze or automatic promotion occurred.\n- All four claims have Evidence_ID, Result_ID and locator.\n- Null findings in EV-0426 and EV-0521 are retained in the claim boundaries.\n- Human confirmation remains pending.\n'''
 (OUT/'BATCH10_4H_GAP_REPORT.md').write_text(report,encoding='utf-8')
 outputs=[p for p in OUT.iterdir() if p.is_file() and p.name!='BATCH10_4H_GAP_MANIFEST.json']
 m={'batch':'BATCH 10.4H-GAP','gate':'TARGETED_GAP_CLOSURE_INSUFFICIENT','targeted_candidates_reviewed':4,'new_result_ids':4,'new_bounded_claims':4,'claim_chains_complete':'4/4','new_final_references':0,'new_claim_ready':0,'blocked_evidence_support':0,'source_insufficient_evidence_promoted':0,'rejected_pmcid_reused':0,'cohort_double_counting':0,'null_suppression':0,'CEF_v1_changes':0,'Zotero_changes':0,'v015_changes':0,'human_review':'PENDING','deterministic_regeneration':'python analysis/build_batch10_4h_gap.py','artifact_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in outputs}}
 (OUT/'BATCH10_4H_GAP_MANIFEST.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__':main()
