"""Build the editorial-only Batch 10.5A journal-fit audit."""
import csv, hashlib, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'batch10_5a'; FREEZE=ROOT/'batch10_4k'
DATE='2026-10-09'; BASE='43e0141e7874035f9d091dea3e58f32b1cd71b58'; U='NOT_STATED_IN_OFFICIAL_SOURCES_CAPTURED'
F=['Candidate_ID','Manuscript','Journal','Publisher','Country','ISSN','Scope','Candidate_Article_Type','Article_Type_Definition','Maximum_Words','Minimum_Words','Abstract_Limit','Reference_Limit','Figure_Table_Limit','Required_Manuscript_Structure','Language','Citation_Reference_Style','Blind_Review_Requirements','Title_Page_Requirements','ORCID_Requirements','AI_Disclosure_Requirements','Ethics_Declaration_Requirements','Data_Availability_Requirements','Funding_Declaration','Conflict_of_Interest_Declaration','Author_Contribution_Requirement','Supplementary_Material_Policy','Preprint_Policy','Simultaneous_Submission_Policy','APC_Class','APC_Value','APC_Currency','APC_Waiver_Discount','Open_Access_Model','Submission_Status','Indexing','DOI_Issuance','Submission_Portal','Official_Timing','Editorial_Integrity','Primary_Official_URL','Access_Date','Official_Evidence_Keys','Evidence_Paraphrase','Scope_Fit','Article_Type_Fit','Word_Count_Fit','Methodological_Fit','Audience_Fit','Evidence_Density_Fit','Reference_Limit_Fit','Publication_Accessibility','Cost_Fit','Indexing_Visibility','Raw_Score','Penalty','Final_Score','Fit_Status','Hard_Exclusion','Editorial_Red_Flags']
S={
'FSAL_ABOUT':('Frontiers in Sports and Active Living','https://www.frontiersin.org/journals/sports-and-active-living/about','Official facts: eISSN 2624-9367; scope includes sports/physical activity; lists DOAJ, PubMed, PMC, ESCI and Scopus.'),
'FSAL_TYPES':('Frontiers in Sports and Active Living','https://www.frontiersin.org/journals/sports-and-active-living/for-authors/article-types','Mini Review is a focused review limited to 3,000 words and two figures/tables.'),
'FSAL_FEES':('Frontiers in Sports and Active Living','https://www.frontiersin.org/journals/sports-and-active-living/for-authors/publishing-fees','Gold OA; B-type articles CHF 2,195; fee support routes stated.'),
'FSAL_CHECKLIST':('Frontiers in Sports and Active Living','https://www.frontiersin.org/journals/sports-and-active-living/for-authors/submission-checklist','Ethics/data declarations are generated through submission answers; contribution-to-field statement ≤200 words; funding required.'),
'FPH_ABOUT':('Frontiers in Public Health','https://www.frontiersin.org/journals/public-health/about','Scope requires public-health relevance; specialty fit needs confirmation.'),
'FPH_TYPES':('Frontiers in Public Health','https://www.frontiersin.org/journals/public-health/for-authors/article-types','Articles are peer reviewed, DOI-assigned and subject to COPE/ICMJE; systematic-review requirements distinct from Mini Review.'),
'FPH_FEES':('Frontiers in Public Health','https://www.frontiersin.org/journals/public-health/for-authors/publishing-fees','Gold OA; B-type articles CHF 2,500; support/discount links available.'),
'JOH_GUIDE':('Journal of Occupational Health','https://academic.oup.com/joh/pages/author-guidelines','Review Article max 6,000 words, 250-word structured abstract, no reference limit, max six tables/figures; AI disclosure and OA waiver routes.'),
'JOH_HOME':('Journal of Occupational Health','https://academic.oup.com/joh/','Official journal page: online ISSN 1348-9585; OUP/JSOH; submission and OA agreement path.'),
'OCCMED':('Occupational Medicine','https://academic.oup.com/occmed/pages/Submission_Online','Qualitative review category max 5,000 words/70 refs/six tables-figures; requires search-method paragraph; target decision after peer review within seven weeks.'),
'OCCMED_AUTHOR':('Occupational Medicine','https://academic.oup.com/occmed/pages/author-guidelines','International occupational-health scope; double-anonymized peer review; online submission; submitting-author ORCID.'),
'RBSP':('Revista Brasileira de Segurança Pública','https://revista.forumseguranca.org.br/rbsp/about/submissions','Official page says the journal is not accepting submissions now; 5,000–10,000-word range; double-blind; ABNT author-date.'),
'RBSO':('Revista Brasileira de Saúde Ocupacional','https://scielo.br/journal/rbso/about/?ilang=pt_BR','Review restricted to systematic/meta/scoping/bibliometric review with prior protocol; Essay max 4,500 words/40 refs.'),
'RBMT':('Revista Brasileira de Medicina do Trabalho','https://new.scielo.br/journal/rbmt/about/?ilang=pt_BR','Peer-reviewed OA ANAMT journal; accepts Review, Opinion, Special Article and Brief Communication.'),
'CSP':('Cadernos de Saúde Pública','https://scielo.br/journal/csp/about/?ilang=pt_BR','Essay max 8,000 words; Perspective max 2,500; no submission/evaluation/publication fee; no simultaneous submission.'),
'RBEPID':('Revista Brasileira de Epidemiologia','https://scielo.br/journal/rbepid/about/?ilang=en','Theoretical essays/opinion papers max 3,400 words, narrative abstract max 250; continuous OA and ScholarOne submission.'),
'MILMED':('Military Medicine','https://academic.oup.com/milmed/pages/General_Instructions','Review Articles integrate literature to guide policy/practice: max 4,000 words, four tables/figures and 250–500-word structured summary; narrative reviews have a distinct non-systematic route.'),
'BMJMH':('BMJ Military Health','https://militaryhealth.bmj.com/pages/authors','Official authors page lists invited and systematic reviews, peer-review and data-sharing policies, APC/waiver information, ORCID and a 26-day median first decision with review.'),
'BRJP':('Brazilian Journal of Pain','https://www.brjp.org.br/instructions','Does not accept narrative/interactive reviews since June 2024; accepts systematic review/meta-analysis and original work, with blind manuscript and title page.'),
'RBAFS':('Revista Brasileira de Atividade Física & Saúde','https://rbafs.org.br/RBAFS/diretrizes','Current guidelines require author/ORCID, conflict/funding/contribution information; original and review formats require objective, methods, results and conclusion in the abstract.'),
}
def cand(**k):
 d={x:U for x in F}; d.update(k); sc=['Scope_Fit','Article_Type_Fit','Word_Count_Fit','Methodological_Fit','Audience_Fit','Evidence_Density_Fit','Reference_Limit_Fit','Publication_Accessibility','Cost_Fit','Indexing_Visibility']; d['Raw_Score']=sum(map(int,(d[x] for x in sc))); d['Final_Score']=d['Raw_Score']-int(d['Penalty']); return d
def C(id,ms,j,typ,maxw,score,pen,fit,hard,url,keys,why,flags,**k):
 return cand(Candidate_ID=id,Manuscript=ms,Journal=j,Candidate_Article_Type=typ,Maximum_Words=maxw,Scope_Fit=score[0],Article_Type_Fit=score[1],Word_Count_Fit=score[2],Methodological_Fit=score[3],Audience_Fit=score[4],Evidence_Density_Fit=score[5],Reference_Limit_Fit=score[6],Publication_Accessibility=score[7],Cost_Fit=score[8],Indexing_Visibility=score[9],Penalty=pen,Fit_Status=fit,Hard_Exclusion=hard,Primary_Official_URL=url,Access_Date=DATE,Official_Evidence_Keys=keys,Evidence_Paraphrase=why,Editorial_Red_Flags=flags,Editorial_Integrity='EDITORIAL_INTEGRITY_PASS',**k)
I=[
C('INT-01','International','Frontiers in Sports and Active Living','Mini Review','3000',(5,5,5,5,5,5,5,5,1,5),0,'EDITORIALLY_COMPATIBLE','NO',S['FSAL_TYPES'][1],'FSAL_ABOUT; FSAL_TYPES; FSAL_FEES; FSAL_CHECKLIST','Mini Review fits the 1,627-word evidence-boundary International without expansion.','APC; specialty-section confirmation needed.',Publisher='Frontiers Media SA',Country='Switzerland',ISSN='2624-9367',Scope='Sports, physical activity and active living; tactical/occupational-performance section fit required.',Article_Type_Definition='Focused review of a current aspect or recent development.',Minimum_Words='NOT_STATED',Figure_Table_Limit='2 combined',Required_Manuscript_Structure='Abstract; Introduction; subsections; Discussion.',Language='English',Citation_Reference_Style='Frontiers style',Blind_Review_Requirements='Transparent peer review',AI_Disclosure_Requirements='Frontiers AI policy applies; exact text deferred.',Ethics_Declaration_Requirements='Submission declaration when applicable.',Data_Availability_Requirements='Submission questions generate statement when applicable.',Funding_Declaration='Required at submission.',Author_Contribution_Requirement='Required at submission.',APC_Class='APC_REQUIRED',APC_Value='2195',APC_Currency='CHF',APC_Waiver_Discount='Institutional partnership and eligible fee support.',Open_Access_Model='Gold OA',Submission_Status='OPEN_PORTAL_AVAILABLE',Indexing='DOAJ; PubMed; PMC; Web of Science ESCI; Scopus (official journal facts).',DOI_Issuance='YES',Submission_Portal='Frontiers online submission'),
C('INT-02','International','Journal of Occupational Health','Review Article','6000',(5,5,5,5,4,5,5,5,2,4),0,'EDITORIALLY_COMPATIBLE','NO',S['JOH_GUIDE'][1],'JOH_GUIDE; JOH_HOME','The review definition accommodates bounded evaluation/commentary; 1,627 words/four refs fit.','Dynamic APC quote and external indexing need confirmation before selection.',Publisher='Oxford University Press for Japan Society for Occupational Health',Country='United Kingdom / Japan',ISSN='1348-9585 (online)',Scope='Broad occupational health and workplace safety.',Article_Type_Definition='Review, evaluation or commentary of research reports on a specific theme.',Minimum_Words='NOT_STATED',Abstract_Limit='250 structured',Reference_Limit='No limit',Figure_Table_Limit='6',Required_Manuscript_Structure='Structured abstract; keywords; key points; review text.',Language='English',Citation_Reference_Style='AMA after acceptance; readable at submission.',AI_Disclosure_Requirements='AI use disclosed in cover letter and Methods/Acknowledgements.',Funding_Declaration='Full funding under separate subheading.',Conflict_of_Interest_Declaration='Required.',Author_Contribution_Requirement='Review Article exempted.',APC_Class='APC_REQUIRED',APC_Value='DYNAMIC_QUOTE_REQUIRED',APC_Currency='USD (official calculator)',APC_Waiver_Discount='LMIC waiver/discount and Read-and-Publish routes.',Open_Access_Model='Fully OA',Submission_Status='OPEN_PORTAL_AVAILABLE',Submission_Portal='OUP online submission'),
C('INT-03','International','Frontiers in Public Health','Mini Review','3000',(3,5,5,5,4,5,5,5,1,5),2,'CONDITIONAL_EDITORIAL_COMPATIBILITY','NO',S['FPH_TYPES'][1],'FPH_ABOUT; FPH_TYPES; FPH_FEES','Compatible only with specialty-level confirmation of public-health framing.','Scope/specialty confirmation; APC.',Publisher='Frontiers Media SA',Country='Switzerland',ISSN='2296-2565',Scope='Public health; needs specialty-section alignment.',Article_Type_Definition='Frontiers B-type focused review; exact availability depends on specialty.',Minimum_Words='NOT_STATED',Figure_Table_Limit='2 combined',Language='English',Citation_Reference_Style='Frontiers style',Blind_Review_Requirements='Transparent peer review',APC_Class='APC_REQUIRED',APC_Value='2500',APC_Currency='CHF',APC_Waiver_Discount='Institutional partnership and eligible fee support.',Open_Access_Model='Gold OA',Submission_Status='OPEN_PORTAL_AVAILABLE',DOI_Issuance='YES',Submission_Portal='Frontiers online submission'),
C('INT-04','International','Occupational Medicine','Qualitative review category','5000',(5,4,5,4,5,4,5,3,3,4),2,'CONDITIONAL_EDITORIAL_COMPATIBILITY','NO',S['OCCMED'][1],'OCCMED; OCCMED_AUTHOR','Substance compatible only if editors accept existing evidence-identification text as the required search-method paragraph.','Potentially confusing article label; editor precheck; British English/double anonymous.',Publisher='Oxford University Press for Society of Occupational Medicine',Country='United Kingdom',ISSN='0962-7480; 1471-8405',Scope='International occupational health and safety.',Article_Type_Definition='Officially labelled Systematic Reviews but stated qualitative rather than systematic.',Minimum_Words='NOT_STATED',Abstract_Limit='250 structured',Reference_Limit='70',Figure_Table_Limit='6',Required_Manuscript_Structure='Introduction; search-method paragraph; review; teaser; key learning points.',Language='English (British spelling)',Citation_Reference_Style='Vancouver',Blind_Review_Requirements='Double-anonymized',ORCID_Requirements='Submitting author required.',Funding_Declaration='Separate Funding section.',APC_Class='APC_OPTIONAL',APC_Value='NOT_STATED',APC_Currency='NOT_STATED',Open_Access_Model='Hybrid',Submission_Status='OPEN_PORTAL_AVAILABLE',Submission_Portal='OUP online submission',Official_Timing='Target decision after peer review within 7 weeks'),
C('INT-05','International','TSAC Report','Unverified professional report','NOT_CONFIRMED',(4,0,0,0,4,0,0,0,0,0),15,'HARD_EXCLUDE','YES','https://www.nsca.com/education/articles/tsac-report/','','Current official granular scholarly requirements/peer-review status not established.','Current article type and requirements not verified; do not select.',Publisher='National Strength and Conditioning Association',Country='United States',Scope='Tactical strength and conditioning professional education.',Submission_Status='NOT_CONFIRMED',APC_Class='APC_UNKNOWN'),
C('INT-06','International','Military Medicine','Narrative Review','4000',(5,4,5,4,5,4,5,3,3,4),1,'CONDITIONAL_EDITORIAL_COMPATIBILITY','NO',S['MILMED'][1],'MILMED','Military-health scope and a documented non-systematic narrative-review route fit the frozen manuscript without expansion.','Military rather than public-safety population; non-member USD 125 submission fee; structured summary required.',Publisher='Oxford University Press for AMSUS',Country='United States / United Kingdom',ISSN='0026-4075; 1930-613X',Scope='Military and operational medicine/health.',Article_Type_Definition='Narrative review may be less methodologically stringent than other review types; Review Articles integrate current literature for policy/practice.',Minimum_Words='NOT_STATED',Abstract_Limit='250–500 structured summary',Figure_Table_Limit='4',Required_Manuscript_Structure='Title page; structured summary; main text; data availability statement.',Language='English',Citation_Reference_Style='NLM-style journal abbreviations; DOI where present.',Blind_Review_Requirements='Single-anonymized',Title_Page_Requirements='Required title page with author, guarantor, funding, COI, contribution and data details.',AI_Disclosure_Requirements='AI use disclosed in cover letter and Methods/Acknowledgements; AI cannot be author.',Ethics_Declaration_Requirements='Ethics/IRB statement when applicable.',Data_Availability_Requirements='Required.',Funding_Declaration='Required on title page.',Conflict_of_Interest_Declaration='Required.',Author_Contribution_Requirement='Required.',APC_Class='APC_OPTIONAL',APC_Value='125 submission fee for non-members; OA charge if chosen',APC_Currency='USD',APC_Waiver_Discount='Society/OA discount routes stated.',Open_Access_Model='Hybrid',Submission_Status='OPEN_PORTAL_AVAILABLE',DOI_Issuance='YES',Submission_Portal='Editorial Manager'),
C('INT-07','International','BMJ Military Health','Invited Review / Systematic Review','NOT_STATED',(5,1,0,0,5,2,0,4,2,4),12,'HARD_EXCLUDE','YES',S['BMJMH'][1],'BMJMH','Scope is strong, but the official author page exposes Invited Review and Systematic Review, not a verified freely-submittable non-systematic short-form route.','Invited/systematic review categories do not fit frozen design; no verified short-form route.',Publisher='BMJ',Country='United Kingdom',ISSN='2633-3767',Scope='Military health research, reviews and commentary.',Article_Type_Definition='Official author page lists Invited Review and Systematic Review.',Submission_Status='OPEN_PORTAL_AVAILABLE',APC_Class='APC_UNKNOWN',Open_Access_Model='Hybrid/Plan-S policy',Official_Timing='Median 26 days to first decision with review')]

B=[
C('BRA-01','Brazil','Revista Brasileira de Saúde Ocupacional','Ensaio','4500',(5,5,5,5,5,5,5,4,4,4),0,'EDITORIALLY_COMPATIBLE','NO',S['RBSO'][1],'RBSO','Essay is compatible. Review Article is excluded because it requires systematic/meta/scoping/bibliometric review and prior protocol.','Use Essay only; APC not explicitly stated on captured page.',Publisher='Fundacentro / SciELO',Country='Brazil',ISSN='0303-7657; 2317-6369',Scope='Worker safety and health / occupational health.',Article_Type_Definition='Circumscribed scientific reflection that may defend a position and deepen discussion.',Minimum_Words='NOT_STATED',Abstract_Limit='200 words in two languages',Reference_Limit='40',Required_Manuscript_Structure='Essay with bilingual abstracts; current declarations apply.',Language='Portuguese, Spanish or English',Open_Access_Model='SciELO open access',Submission_Status='OPEN_PORTAL_AVAILABLE',APC_Class='APC_UNKNOWN',Indexing='SciELO official platform',Submission_Portal='SciELO journal submission route'),
C('BRA-02','Brazil','Cadernos de Saúde Pública','Ensaio','8000',(3,5,5,5,3,5,5,5,5,5),0,'EDITORIALLY_COMPATIBLE','NO',S['CSP'][1],'CSP','Compatible non-systematic essay, no APC, but broader collective-health audience.','Public-health framing; article is short but no minimum stated.',Publisher='Escola Nacional de Saúde Pública Sergio Arouca, Fundação Oswaldo Cruz / SciELO',Country='Brazil',ISSN='0102-311X; 1678-4464',Scope='Collective health/public health.',Article_Type_Definition='Original text that develops an argument on a well-defined topic.',Minimum_Words='NOT_STATED',Figure_Table_Limit='5 illustrations',Language='Portuguese, English or Spanish',Simultaneous_Submission_Policy='Prohibited',APC_Class='NO_APC',APC_Value='0',APC_Currency='BRL',APC_Waiver_Discount='Not applicable',Open_Access_Model='Open access',Submission_Status='OPEN_PORTAL_AVAILABLE',Indexing='SciELO official platform',Submission_Portal='CSP online submission'),
C('BRA-03','Brazil','Revista Brasileira de Medicina do Trabalho','Artigo de Revisão','6000',(5,4,5,4,5,5,5,5,5,4),1,'CONDITIONAL_EDITORIAL_COMPATIBILITY','NO',S['RBMT'][1],'RBMT','Strong work-medicine scope and non-APC route; granular current template must be reconfirmed only after selection.','Current granular review/format requirements need reconfirmation; review label must not imply systematic review.',Publisher='Associação Nacional de Medicina do Trabalho (ANAMT)',Country='Brazil',ISSN='NOT_STATED_ON_CAPTURED_PAGE',Scope='Occupational/work medicine and related fields.',Article_Type_Definition='Critical and ordered literature assessment in occupational/work health.',Minimum_Words='NOT_STATED',Abstract_Limit='250 unstructured (author-instruction route)',Language='Portuguese and English publication stated',Citation_Reference_Style='Vancouver (author-instruction route)',APC_Class='NO_APC',APC_Value='0',APC_Currency='BRL',APC_Waiver_Discount='Not applicable',Open_Access_Model='Open access',Submission_Status='OPEN_PORTAL_AVAILABLE',Indexing='Official journal page reports PMC, Scopus, LILACS, Latindex, EBSCO and DOAJ',DOI_Issuance='YES',Submission_Portal='GNPapers'),
C('BRA-04','Brazil','Revista Brasileira de Epidemiologia','Theoretical essay / opinion paper','3400',(3,4,5,4,3,4,5,5,5,4),1,'CONDITIONAL_EDITORIAL_COMPATIBILITY','NO',S['RBEPID'][1],'RBEPID','Length/type fit, but epidemiology is not the central disciplinary audience.','Secondary scope; editor precheck needed.',Publisher='Associação Brasileira de Saúde Coletiva (ABRASCO) / SciELO',Country='Brazil',ISSN='1415-790X; 1980-5497',Scope='Epidemiology and related fields.',Article_Type_Definition='Reflection, methodological analysis or theoretical discussion.',Minimum_Words='NOT_STATED',Abstract_Limit='250 narrative',Required_Manuscript_Structure='Narrative abstract; title page; CRediT contributions.',Language='Portuguese, English or Spanish',Author_Contribution_Requirement='CRediT required.',APC_Class='NO_APC',APC_Value='0',APC_Currency='BRL',Open_Access_Model='Continuous open access',Submission_Status='OPEN_PORTAL_AVAILABLE',Indexing='SciELO official platform',Submission_Portal='ScholarOne'),
C('BRA-05','Brazil','Revista Brasileira de Segurança Pública','Critical literature review / original article','10000',(5,3,0,3,5,3,4,0,5,2),20,'HARD_EXCLUDE','YES',S['RBSP'][1],'RBSP','Very strong scope but official page says not accepting submissions and requires 5,000–10,000 words.','CURRENTLY_NOT_SUBMITTABLE; 5,000-word minimum; long stated timing.',Publisher='Fórum Brasileiro de Segurança Pública',Country='Brazil',ISSN='1981-1659',Scope='Brazilian public security and related social/applied sciences.',Article_Type_Definition='Theoretical research and critical literature reviews accepted.',Minimum_Words='5000',Required_Manuscript_Structure='Anonymous manuscript; Portuguese and English abstract; author metadata in system.',Language='Portuguese, English or Spanish',Citation_Reference_Style='ABNT NBR 6023:2002; author-date',Blind_Review_Requirements='Double-blind',ORCID_Requirements='Required for publication',Ethics_Declaration_Requirements='Human research ethics if applicable.',Funding_Declaration='Funding institution if applicable.',Author_Contribution_Requirement='Requested/justified for multiple authors.',Preprint_Policy='Preprints conflict with double-blind evaluation.',Simultaneous_Submission_Policy='Prohibited',APC_Class='NO_APC',APC_Value='0',APC_Currency='BRL',Open_Access_Model='Journal website access',Submission_Status='CURRENTLY_NOT_SUBMITTABLE',Submission_Portal='OJS portal presently closed',Official_Timing='Initial assessment up to 30d; review avg 60d; publication ~18 months'),
C('BRA-06','Brazil','Revista de Saúde Pública','Unverified compatible type','NOT_CONFIRMED',(3,0,0,0,3,0,0,0,0,4),15,'HARD_EXCLUDE','YES','https://www.scielo.br/journal/rsp/about/?ilang=pt_BR','','Current compatible short-form category was not established from current official capture.','Current compatible category/limits not verified; do not select.',Publisher='Faculdade de Saúde Pública, Universidade de São Paulo / SciELO',Country='Brazil',ISSN='0034-8910; 1518-8787',Scope='Public health.',Submission_Status='NOT_CONFIRMED',APC_Class='APC_UNKNOWN',Indexing='SciELO presence'),
C('BRA-07','Brazil','Brazilian Journal of Pain','Narrative Review','4000',(2,0,5,0,2,1,5,4,3,3),12,'HARD_EXCLUDE','YES',S['BRJP'][1],'BRJP','The only directly relevant musculoskeletal slice cannot represent the frozen multi-domain public-safety manuscript; narrative reviews are expressly not accepted.','Narrative reviews not accepted since June 2024; scope too narrow; systematic review would distort science.',Publisher='Sociedade Brasileira para o Estudo da Dor',Country='Brazil',ISSN='2595-0118',Scope='Pain-related research.',Article_Type_Definition='Original articles, systematic review/meta-analysis, short communications and other pain-specific formats; narrative reviews not accepted.',Minimum_Words='NOT_STATED',Figure_Table_Limit='6',Required_Manuscript_Structure='Blind manuscript plus title page; open-science compliance form.',Language='Portuguese/English (confirm article-type language at formatting)',Blind_Review_Requirements='Blind manuscript required.',Title_Page_Requirements='Title, authors, affiliations, ORCID, funding, COI, ethics and preprint details.',ORCID_Requirements='Required on title page.',Author_Contribution_Requirement='CRediT required.',Funding_Declaration='Required.',Conflict_of_Interest_Declaration='Required.',Ethics_Declaration_Requirements='Required when applicable.',Preprint_Policy='Encouraged under stated conditions.',APC_Class='APC_UNKNOWN',Submission_Status='OPEN_PORTAL_AVAILABLE',Submission_Portal='BrJP platform'),
C('BRA-08','Brazil','Revista Brasileira de Atividade Física & Saúde','Review Article','NOT_STATED',(3,2,0,1,3,2,0,4,4,3),10,'HARD_EXCLUDE','YES',S['RBAFS'][1],'RBAFS','Physical-activity scope is only one contextual element, and the captured review/original format requires conventional objective-methods-results-conclusion reporting not supplied by the frozen synthesis.','Scope/evidence-density mismatch; review-method fit not established; do not reshape science.',Publisher='Sociedade Brasileira de Atividade Física e Saúde',Country='Brazil',ISSN='2175-0491',Scope='Physical activity and health.',Article_Type_Definition='Original/review formats use required structured content; current compatible non-systematic short form not established.',Minimum_Words='NOT_STATED',Abstract_Limit='250 for original/review; 150 special sections',Required_Manuscript_Structure='Title page, manuscript type, title, unstructured abstract with objective/methods/results/conclusion for original/review.',Language='Portuguese and English elements required.',Citation_Reference_Style='Numeric superscript',Title_Page_Requirements='Author, affiliation, ORCID, word counts, COI, funding and contribution information.',ORCID_Requirements='Required.',Funding_Declaration='Required.',Conflict_of_Interest_Declaration='Required.',Author_Contribution_Requirement='Required.',APC_Class='APC_UNKNOWN',Open_Access_Model='Journal website access',Submission_Status='OPEN_PORTAL_AVAILABLE')]

def write(name,fields,data):
 with (OUT/name).open('w',encoding='utf-8',newline='') as h: w=csv.DictWriter(h,fieldnames=fields,extrasaction='raise'); w.writeheader(); w.writerows(data)
def sh(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 OUT.mkdir(exist_ok=True)
 for n,x in {'International_v0.16-B2-SCIENTIFIC-FROZEN.docx':'0abe30789f6f395a7b67d8f2b87ae893befb4b3eed810c5b252492ae0753cfd2','Brazil_v0.16-B2-SCIENTIFIC-FROZEN.docx':'bcedc42658c3c624e40747c623652500280ce45f1ad1000d22fdb30438e2f486'}.items(): assert sh(FREEZE/n)==x
 write('INTERNATIONAL_JOURNAL_CANDIDATES.csv',F,I); write('BRAZIL_JOURNAL_CANDIDATES.csv',F,B)
 efields=['Evidence_Key','Journal','Official_URL','Access_Date','Evidence_Paraphrase','URL_Status']; write('JOURNAL_CURRENT_GUIDELINE_EVIDENCE.csv',efields,[dict(Evidence_Key=k,Journal=v[0],Official_URL=v[1],Access_Date=DATE,Evidence_Paraphrase=v[2],URL_Status='OFFICIAL_URL_CAPTURED') for k,v in S.items()])
 allr=I+B; cf=['Candidate_ID','Manuscript','Scientific_Type_Internal','Journal_Submission_Type','Mapping_Rationale','Compatibility_Status','Hard_Exclusion','No_Science_Change_Required','Reason']; write('JOURNAL_ARTICLE_TYPE_COMPATIBILITY.csv',cf,[dict(Candidate_ID=r['Candidate_ID'],Manuscript=r['Manuscript'],Scientific_Type_Internal='Evidence-informed integrative synthesis',Journal_Submission_Type=r['Candidate_Article_Type'],Mapping_Rationale=r['Article_Type_Definition'],Compatibility_Status=r['Fit_Status'],Hard_Exclusion=r['Hard_Exclusion'],No_Science_Change_Required='YES' if r['Hard_Exclusion']=='NO' else 'NO',Reason=r['Editorial_Red_Flags']) for r in allr])
 wf=['Candidate_ID','Manuscript','Manuscript_Body_Words','Journal_Minimum_Words','Journal_Maximum_Words','Word_Count_Status','Expansion_Required','Official_Basis']; write('JOURNAL_WORD_LIMIT_COMPATIBILITY.csv',wf,[dict(Candidate_ID=r['Candidate_ID'],Manuscript=r['Manuscript'],Manuscript_Body_Words='1627' if r['Manuscript']=='International' else '1879',Journal_Minimum_Words=r['Minimum_Words'],Journal_Maximum_Words=r['Maximum_Words'],Word_Count_Status='INCOMPATIBLE_BELOW_MINIMUM' if r['Candidate_ID']=='BRA-05' else ('COMPATIBLE' if r['Hard_Exclusion']=='NO' else 'UNVERIFIED'),Expansion_Required='YES' if r['Candidate_ID']=='BRA-05' else 'NO',Official_Basis=r['Official_Evidence_Keys']) for r in allr])
 af=['Candidate_ID','Journal','APC_Class','APC_Value','APC_Currency','Waiver_Discount','Open_Access_Model','Cost_Fit','Official_URL','Access_Date']; write('JOURNAL_APC_AND_ACCESS.csv',af,[dict(Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],APC_Class=r['APC_Class'],APC_Value=r['APC_Value'],APC_Currency=r['APC_Currency'],Waiver_Discount=r['APC_Waiver_Discount'],Open_Access_Model=r['Open_Access_Model'],Cost_Fit=r['Cost_Fit'],Official_URL=r['Primary_Official_URL'],Access_Date=DATE) for r in allr])
 xf=['Candidate_ID','Journal','PubMed_MEDLINE','PubMed_Central','Scopus','Web_of_Science','SciELO','DOAJ','Indexing_Evidence_Status','Official_URL','Access_Date']
 def ix(r):
  s=r['Indexing']; return dict(Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],PubMed_MEDLINE='YES_OFFICIAL_JOURNAL_CLAIM' if 'PubMed' in s else 'NOT_INDEPENDENTLY_VERIFIED',PubMed_Central='YES_OFFICIAL_JOURNAL_CLAIM' if 'PMC' in s else 'NOT_INDEPENDENTLY_VERIFIED',Scopus='YES_OFFICIAL_JOURNAL_CLAIM' if 'Scopus' in s else 'NOT_INDEPENDENTLY_VERIFIED',Web_of_Science='YES_OFFICIAL_JOURNAL_CLAIM' if 'Web of Science' in s else 'NOT_INDEPENDENTLY_VERIFIED',SciELO='YES_OFFICIAL_PLATFORM' if 'SciELO' in s else 'NOT_INDEPENDENTLY_VERIFIED',DOAJ='YES_OFFICIAL_JOURNAL_CLAIM' if 'DOAJ' in s else 'NOT_INDEPENDENTLY_VERIFIED',Indexing_Evidence_Status='OFFICIAL_SOURCE_CAPTURED_WITH_LIMITATIONS',Official_URL=r['Primary_Official_URL'],Access_Date=DATE)
 write('JOURNAL_INDEXING_AUDIT.csv',xf,[ix(r) for r in allr])
 sf=['Candidate_ID','Journal','Submission_Status','Submission_Portal','Simultaneous_Submission_Policy','Preprint_Policy','Official_Timing','Editorial_Integrity','Official_URL','Access_Date','Notes']; write('JOURNAL_SUBMISSION_STATUS.csv',sf,[dict(Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],Submission_Status=r['Submission_Status'],Submission_Portal=r['Submission_Portal'],Simultaneous_Submission_Policy=r['Simultaneous_Submission_Policy'],Preprint_Policy=r['Preprint_Policy'],Official_Timing=r['Official_Timing'],Editorial_Integrity=r['Editorial_Integrity'],Official_URL=r['Primary_Official_URL'],Access_Date=DATE,Notes=r['Editorial_Red_Flags']) for r in allr])
 rf=['Candidate_ID','Journal','Red_Flag','Severity','Action_Required','Hard_Exclusion']; write('JOURNAL_EDITORIAL_RED_FLAGS.csv',rf,[dict(Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],Red_Flag=f,Severity='HIGH' if r['Hard_Exclusion']=='YES' else 'MEDIUM',Action_Required='DO_NOT_SELECT' if r['Hard_Exclusion']=='YES' else 'CONFIRM_AT_TARGET_FORMATTING',Hard_Exclusion=r['Hard_Exclusion']) for r in allr for f in r['Editorial_Red_Flags'].split('; ')])
 inf=['Candidate_ID','Journal','Publisher_Identity','Editorial_Transparency','Peer_Review_Policy','Ethics_Retraction_Correction_Policy','Indexing_Evidence','Integrity_Status','Official_Basis']; write('JOURNAL_EDITORIAL_INTEGRITY_AUDIT.csv',inf,[dict(Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],Publisher_Identity=r['Publisher'],Editorial_Transparency='OFFICIAL_JOURNAL_OR_PUBLISHER_PAGE_CAPTURED',Peer_Review_Policy=r['Blind_Review_Requirements'],Ethics_Retraction_Correction_Policy='OFFICIAL_POLICY_CAPTURED_OR_REQUIRES_FORMATTING_CONFIRMATION',Indexing_Evidence=r['Indexing'],Integrity_Status=r['Editorial_Integrity'],Official_Basis=r['Official_Evidence_Keys']) for r in allr])
 def ranking(rows):
  return sorted([r for r in rows if r['Hard_Exclusion']=='NO'],key=lambda r:int(r['Final_Score']),reverse=True)[:3]
 ir,br=ranking(I),ranking(B); qf=['Rank','Candidate_ID','Journal','Final_Score_50','Fit_Status','Candidate_Article_Type','APC','Indexing_Visibility','Principal_Advantages','Principal_Risks','Selection_Eligibility']
 def rr(rows): return [dict(Rank=n,Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],Final_Score_50=r['Final_Score'],Fit_Status=r['Fit_Status'],Candidate_Article_Type=r['Candidate_Article_Type'],APC=f"{r['APC_Class']} {r['APC_Value']} {r['APC_Currency']}",Indexing_Visibility=r['Indexing'],Principal_Advantages=r['Evidence_Paraphrase'],Principal_Risks=r['Editorial_Red_Flags'],Selection_Eligibility='YES' if r['Fit_Status']=='EDITORIALLY_COMPATIBLE' else 'YES_CONDITIONAL') for n,r in enumerate(rows,1)]
 write('INTERNATIONAL_JOURNAL_RANKING.csv',qf,rr(ir));write('BRAZIL_JOURNAL_RANKING.csv',qf,rr(br))
 tf=['Manuscript','Target_Role','Candidate_ID','Journal','Journal_Submission_Type','Score_50','Status','Human_Selection_Required','Reason']; targets=[]
 for m,rs in [('International',ir),('Brazil',br)]: targets += [dict(Manuscript=m,Target_Role=role,Candidate_ID=r['Candidate_ID'],Journal=r['Journal'],Journal_Submission_Type=r['Candidate_Article_Type'],Score_50=r['Final_Score'],Status=r['Fit_Status'],Human_Selection_Required='YES',Reason=r['Evidence_Paraphrase']) for role,r in zip(['PRIMARY_TARGET_RECOMMENDED','BACKUP_TARGET_1','BACKUP_TARGET_2'],rs)]
 write('PRIMARY_AND_BACKUP_TARGETS.csv',tf,targets)
 hf=['Decision_ID','Manuscript','Approved_Human_Strategy','Candidate','Score','Article_Type','APC','Indexing','Advantages','Risks','AI_Recommendation','HUMAN_DECISION','HUMAN_RATIONALE','HUMAN_REVIEWER','HUMAN_REVIEW_DATE','Decision_Status']
 def hrow(d,m,rs): return dict(Decision_ID=d,Manuscript=m,Approved_Human_Strategy='SHORT_FORM',Candidate=' | '.join(r['Journal'] for r in rs),Score=' | '.join(str(r['Final_Score'])+'/50' for r in rs),Article_Type=' | '.join(r['Candidate_Article_Type'] for r in rs),APC=' | '.join(r['APC_Class']+' '+r['APC_Value']+' '+r['APC_Currency'] for r in rs),Indexing=' | '.join(r['Indexing'] for r in rs),Advantages=' | '.join(r['Evidence_Paraphrase'] for r in rs),Risks=' | '.join(r['Editorial_Red_Flags'] for r in rs),AI_Recommendation=rs[0]['Journal'],HUMAN_DECISION='',HUMAN_RATIONALE='',HUMAN_REVIEWER='',HUMAN_REVIEW_DATE='',Decision_Status='PENDING_HUMAN_SELECTION')
 write('TARGET_JOURNAL_HUMAN_DECISION_QUEUE.csv',hf,[hrow('INT-TARGET-SELECTION','International',ir),hrow('BRA-TARGET-SELECTION','Brazil',br)])
 report=f'''# BATCH 10.5A — current target journal fit audit\n\n**Editorial verification date:** {DATE}\n**Base commit:** `{BASE}`\n\n`TARGET_JOURNAL_FIT_AUDIT_PASS`\n`GO_TARGET_JOURNAL_HUMAN_SELECTION`\n\n## Preserved input\n\n- International: `SHORT_FORM`, 1,627 body words, four frozen references.\n- Brazil: `SHORT_FORM`, 1,879 body words, nine frozen references.\n- Both frozen DOCX SHA-256 values were checked before artifact generation.\n\n## Ranked shortlist\n\n### International\n\n1. **{ir[0]['Journal']} — {ir[0]['Candidate_Article_Type']}** ({ir[0]['Final_Score']}/50). Strongest scope/type/length fit; its CHF 2,195 B-type APC and specialty confirmation remain material.\n2. **{ir[1]['Journal']} — {ir[1]['Candidate_Article_Type']}** ({ir[1]['Final_Score']}/50). Bounded review fit; obtain its live APC quote before selection.\n3. **{ir[2]['Journal']} — {ir[2]['Candidate_Article_Type']}** ({ir[2]['Final_Score']}/50). Conditional on public-health specialty confirmation; CHF 2,500 B-type APC.\n\n### Brazil\n\n1. **{br[0]['Journal']} — {br[0]['Candidate_Article_Type']}** ({br[0]['Final_Score']}/50). Direct occupational-health scope and non-systematic essay category.\n2. **{br[1]['Journal']} — {br[1]['Candidate_Article_Type']}** ({br[1]['Final_Score']}/50). Compatible non-systematic essay and no APC, but broader collective-health audience.\n3. **{br[2]['Journal']} — {br[2]['Candidate_Article_Type']}** ({br[2]['Final_Score']}/50). Strong work-medicine alignment; current granular template must be reconfirmed after selection.\n\n## Exclusions\n\n- **RBSP** is `HARD_EXCLUDE`: its official page says submissions are closed and it has a 5,000-word minimum. No scientific expansion is permitted.\n- **RBSO Review Article** is excluded as a route because it would require a review design not held by the frozen scientific layer. RBSO **Ensaio** remains independently compatible.\n\n## Controls and limits\n\nNo manuscript, claim, Result_ID, reference, Zotero record or CEF-v1 record changed. The audit includes 7 International and 8 Brazil candidates plus a separate editorial-integrity ledger. The human queue has exactly `INT-TARGET-SELECTION` and `BRA-TARGET-SELECTION`, with all human fields blank. Fields not supplied by current official sources are deliberately marked `NOT_STATED_IN_OFFICIAL_SOURCES_CAPTURED`.\n\nNext exact action: the author chooses one International and one Brazil target in `TARGET_JOURNAL_HUMAN_DECISION_QUEUE.csv`; only then may Batch 10.5B begin.\n'''
 (OUT/'BATCH10_5A_REPORT.md').write_text(report,encoding='utf-8')
 files=sorted(p for p in OUT.iterdir() if p.is_file() and p.name!='BATCH10_5A_MANIFEST.json')
 manifest={'batch':'BATCH 10.5A','base_commit':BASE,'editorial_verification_date':DATE,'gate':'TARGET_JOURNAL_FIT_AUDIT_PASS','next_gate':'GO_TARGET_JOURNAL_HUMAN_SELECTION','international_short_form_words':1627,'brazil_short_form_words':1879,'international_candidates':len(I),'brazil_candidates':len(B),'international_compatible_candidates':sum(r['Hard_Exclusion']=='NO' for r in I),'brazil_compatible_candidates':sum(r['Hard_Exclusion']=='NO' for r in B),'human_decision_items':2,'human_decisions_populated':0,'v016_manuscripts_changed':0,'cef_v1_changed':0,'zotero_changed':0,'scientific_claims_changed':0,'result_ids_changed':0,'references_changed':0,'artifact_sha256':{p.name:sh(p) for p in files}}
 (OUT/'BATCH10_5A_MANIFEST.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__': main()
