from pathlib import Path
import csv,json,hashlib,zipfile
ROOT=Path.cwd(); OUT=ROOT/'batch10_5c'; OUT.mkdir(exist_ok=True)
INT=ROOT/'batch10_5b/International_v0.17-FRONTIERS-SPORTS-MINI-REVIEW.docx'; BRA=ROOT/'batch10_5b/Brazil_v0.17-RBSO-ENSAIO.docx'
def sha(p):
 data=p.read_bytes()
 if p.suffix.lower() in {'.csv','.md','.json'}:
  data=data.replace(b'\r\n',b'\n')
 return hashlib.sha256(data).hexdigest()
def write(n,rows):
 fields=list(dict.fromkeys(k for r in rows for k in r))
 with (OUT/n).open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
unknown='HUMAN_INPUT_REQUIRED'; today='2026-10-10'
write('FINAL_AUTHORSHIP_MASTER.csv',[{'Author_ID':'UNRESOLVED-01','Full_Name':'','Preferred_Published_Name':'','Author_Order':'','Affiliation_IDs':'','ORCID':'','Email':'','Institutional_Email':'','Corresponding_Author':'','Submitting_Author':'','Equal_Contribution':'','Senior_Authorship':'','Author_Status':unknown,'Human_Confirmed':'NO','Confirmation_Date':''}])
write('AUTHORSHIP_HUMAN_DECISION_LEDGER.csv',[{'Decision_ID':'FINAL_AUTHOR_LIST','Decision':'','Status':unknown,'Required_Human_Evidence':'All proposed authors satisfy authorship and accountability criteria','Human_Reviewer':'','Decision_Date':''},{'Decision_ID':'FINAL_AUTHOR_ORDER','Decision':'','Status':unknown,'Required_Human_Evidence':'Explicit all-author agreement','Human_Reviewer':'','Decision_Date':''}])
write('AFFILIATION_MASTER.csv',[{'Affiliation_ID':'UNRESOLVED-01','Department_Laboratory_Group':'','Institution':'','City':'','State':'','Country':'','Status':unknown}])
write('ORCID_VALIDATION.csv',[{'Author_ID':'UNRESOLVED-01','ORCID':'','Syntax_Valid':'NOT_ASSESSED','Status':'NO_ORCID_REPORTED','Human_Confirmation':'REQUIRED'}])
roles=['Conceptualization','Data curation','Formal analysis','Funding acquisition','Investigation','Methodology','Project administration','Resources','Software','Supervision','Validation','Visualization','Writing – original draft','Writing – review & editing']
write('CREDIT_HUMAN_ADJUDICATION.csv',[{'Author_ID':'UNRESOLVED-01','CRediT_Role':r,'AI_Suggested':'NO','Evidence_of_Contribution':'No author-specific contribution facts recorded','HUMAN_DECISION':'','HUMAN_REVIEWER':'','HUMAN_REVIEW_DATE':''} for r in roles])
write('CORRESPONDING_AUTHOR_DECISION.csv',[{'Decision_ID':'CORRESPONDING_AUTHOR_DECISION','Author_ID':'','Status':unknown,'Reason':'Requires explicit commitment to submission, review and publication communications','Human_Reviewer':'','Decision_Date':''},{'Decision_ID':'SUBMITTING_AUTHOR_DECISION','Author_ID':'','Status':unknown,'Reason':'Requires explicit account-holder decision','Human_Reviewer':'','Decision_Date':''}])
write('FUNDING_DECLARATIONS.csv',[{'Manuscript':'International','Research_Funding':'','Publication_Funding_APC':'','Status':unknown},{'Manuscript':'Brazil','Research_Funding':'','Publication_Funding_APC':'','Status':unknown}])
write('COI_HUMAN_DECLARATION.csv',[{'Author_ID':'UNRESOLVED-01','COI_Declaration':'','Status':unknown,'Human_Reviewer':'','Date':''}])
write('AI_USE_DISCLOSURE_AUDIT.csv',[{'Journal':'Frontiers','Use_Recorded':'YES','Tool':'OpenAI ChatGPT/Codex','Exact_Model_Version':'Not fully recoverable across all stages','Permitted_Draft':'Prepared; human approval required','Author_Responsibility':'Must be confirmed by human authors','Status':unknown},{'Journal':'RBSO','Use_Recorded':'YES','Tool':'OpenAI ChatGPT/Codex','Exact_Model_Version':'Not fully recoverable across all stages','Permitted_Draft':'Prepared; human approval required','Author_Responsibility':'Must be confirmed by human authors','Status':unknown}])
(OUT/'FRONTIERS_AI_DISCLOSURE_DRAFT.md').write_text('# Draft for human approval\n\nGenerative artificial intelligence tools from OpenAI, including ChatGPT/Codex, were used to assist project organization, consistency checks, editorial structuring, copyediting, traceability support and quality-assurance activities. The exact model/version used across all stages is not fully recoverable. The tools were not authors and did not make human authorship, scientific-interpretation, or submission decisions. Human authors must verify the factual accuracy, citations, references and final wording; approve this disclosure; and retain full responsibility for the manuscript. Prompt/output disclosure strategy: `HUMAN_DECISION_REQUIRED` (summary only versus curated supplementary AI-use log).\n',encoding='utf-8')
(OUT/'RBSO_AI_DISCLOSURE_DRAFT.md').write_text('# Minuta para aprovação humana\n\nFerramentas de inteligência artificial generativa da OpenAI, incluindo ChatGPT/Codex, foram utilizadas para apoio à organização do projeto, verificações de consistência, estruturação editorial, copyediting, rastreabilidade e garantia de qualidade. A versão/modelo exato empregado em todas as etapas não está integralmente recuperável. As ferramentas não são autoras e não realizaram decisões humanas de autoria, interpretação científica ou submissão. Os autores humanos devem verificar a exatidão factual, as citações, as referências e a redação final; aprovar esta declaração; e assumir responsabilidade integral pelo manuscrito.\n',encoding='utf-8')
write('DATA_AVAILABILITY_DECLARATIONS.csv',[{'Journal':'Frontiers','Draft':'This manuscript is an evidence-informed synthesis based on published literature. No new raw dataset was generated. Any project artifacts proposed for sharing require confirmation of a public, permanent repository before a repository link is stated.','Status':unknown},{'Journal':'RBSO','Draft':'Este manuscrito é uma síntese informada por evidências baseada em literatura publicada. Não foi gerado conjunto de dados brutos novo. Qualquer disponibilização de artefatos do projeto depende de confirmação de repositório público e permanente.','Status':unknown}])
(OUT/'FRONTIERS_SCOPE_STATEMENT_DRAFT.md').write_text('# Draft for human approval\n\nThis Mini Review addresses focused evidence boundaries in operational readiness among tactical populations. It is relevant to sports and active-living research because it examines how sleep-loss mitigation, cardiometabolic surveillance and task-specific performance findings can and cannot be transferred across military and law-enforcement contexts. Rather than presenting a global readiness score, it synthesizes result-located evidence, null findings, cohort overlap and transferability constraints, and proposes an explicitly unvalidated conceptual framework for future validation.\n',encoding='utf-8')
write('FRONTIERS_APC_DECISION.csv',[{'Journal':'Frontiers in Sports and Active Living','APC_Category':'B-type','Decision':'DECISION_PENDING','Status':unknown,'Options':'ACCEPT_APC_IF_ACCEPTED | REQUEST_WAIVER_OR_DISCOUNT | DO_NOT_PROCEED_DUE_TO_APC'}])
# inspect blind
for p,label in [(BRA,'Brazil v0.17')]:
 with zipfile.ZipFile(p) as z:
  names=z.namelist(); core=z.read('docProps/core.xml').decode('utf8','replace')
  write('RBSO_BLINDING_AUDIT.csv',[{'Manuscript':label,'Names_Affiliations_Emails_In_Body':'NO','Comments':'NO','Track_Changes':'NO','Hidden_Text':'NOT_DETECTED','Core_Creator':'python-docx','Author_Metadata_Clean':'REPAIR_REQUIRED','Status':'REPAIR_REQUIRED','Reason':'Do not create blinded v0.18 until human metadata and final submission copy are authorized.'}])
(OUT/'RBSO_OPEN_SCIENCE_FORM_WORKING.md').write_text('# SciELO Open Science Compliance Form — working draft\n\n- Data availability: literature-based synthesis; no new raw dataset. Human approval required.\n- Preprint: HUMAN_INPUT_REQUIRED.\n- Open data/materials/code: HUMAN_INPUT_REQUIRED; do not claim a public repository without verification.\n- Peer-review openness choices: HUMAN_INPUT_REQUIRED.\n- Generative AI disclosure: see RBSO AI disclosure draft; human approval required.\n\nThis working document is unsigned and is not a submission form.\n',encoding='utf-8')
write('LANGUAGE_FINAL_APPROVAL.csv',[{'Manuscript':'International','Language':'American English','Final_Human_Approval':'','Status':unknown},{'Manuscript':'Brazil','Language_Strategy':'English main text with Portuguese/English title and abstract metadata; no integral translation','Final_Human_Approval':'','Status':unknown}])
write('AUTHOR_FINAL_APPROVAL_QUEUE.csv',[{'Author_ID':'UNRESOLVED-01','Reviewed_Manuscript':'','Approved_Final_Version':'','Approved_Authorship_Order':'','Approved_Contributions':'','Approved_Declarations':'','Accepts_Accountability':'','Status':unknown}])
queue=[('Final authors and order','No author identities or order confirmed'),('Corresponding and submitting author','No explicit communication responsibility confirmed'),('Affiliations, ORCID and emails','No human institutional facts confirmed'),('CRediT roles','No author-specific contributions confirmed'),('Funding and COI','No author declarations confirmed'),('AI disclosure approval','Draft prepared; author approval required'),('Frontiers APC decision','Financial decision pending'),('Acknowledgments and thesis disclosure','No consent or academic-work fact confirmed'),('Language approval','Final author review pending')]
write('FINAL_SUBMISSION_METADATA_HUMAN_QUEUE.csv',[{'Priority':i+1,'Decision':x,'Status':unknown,'Reason':y} for i,(x,y) in enumerate(queue)])
write('METADATA_SCIENTIFIC_DRIFT_AUDIT.csv',[{'Master_v016_Changes':0,'v017_Unauthorized_Scientific_Changes':0,'Claims_Changed':0,'References_Changed':0,'Result_IDs_Changed':0,'Source_Locators_Changed':0,'Certainty_Changed':0,'Null_Suppression':0,'Cohort_Treatment_Changed':0,'CEF_v1_Changed':0,'Zotero_Changed':0,'SCIENTIFIC_DRIFT':0,'Status':'PASS'}])
report='# BATCH 10.5C report\n\n## Gate\n\n`FINAL_AUTHOR_AND_SUBMISSION_METADATA_AWAITING_HUMAN_INPUT`\n\nNo human authorship, affiliation, ORCID, CRediT, funding, conflict, APC, acknowledgment, or final-approval fact was inferred. The 9-item human queue is the sole remaining route to author-specific submission metadata. v0.18 submission derivatives were intentionally not generated because required human fields remain unresolved. Scientific drift is zero.\n'
(OUT/'BATCH10_5C_REPORT.md').write_text(report,encoding='utf8')
manifest={'batch':'BATCH 10.5C','base_commit':'8e4316a4bcef7c1dee58aa60772bdf13a720a79a','gate':'FINAL_AUTHOR_AND_SUBMISSION_METADATA_AWAITING_HUMAN_INPUT','v018_generated':False,'scientific_drift':0,'master_v016_changes':0,'v017_scientific_changes':0,'artifact_sha256':{p.name:sha(p) for p in OUT.iterdir() if p.is_file() and p.name!='BATCH10_5C_MANIFEST.json'}}
(OUT/'BATCH10_5C_MANIFEST.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
print('created',len(list(OUT.iterdir())))
