"""Create the limited HR-009 record; no manuscript or Zotero mutation."""
import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'batch10_4e';A=R/'batch10_4d'
D={'HUMAN_DECISION':'KEEP_CURRENT','HUMAN_REVIEWER':'Matheus Florindo de Deus','HUMAN_REVIEW_DATE':'2026-10-06','HUMAN_RATIONALE':'After final comparative review of the current verified reference architecture and EV-1458, the current reference was retained because it provides equal or superior claim alignment, population and outcome directness, methodological suitability, and citation value without a material incremental benefit from replacement or reference inflation.'}
def rd(p):
 with p.open(encoding='utf-8-sig',newline='') as h:return list(csv.DictReader(h))
def wr(p,f,x):
 with p.open('w',encoding='utf-8',newline='') as h:w=csv.DictWriter(h,fieldnames=f);w.writeheader();w.writerows(x)
def main():
 ds=['claim alignment','population directness','tactical/occupational relevance','study design','sample adequacy','outcome alignment','methodological quality','risk of bias','statistical informativeness','recency','generalizability','Brazil relevance','international relevance','incremental value','overlap/redundancy','integrity','citation fitness','suitability for exact manuscript wording']
 cur=['Current citations support Brazilian academy fitness and cadet use-of-force claims.','Brazilian police recruits/cadets.','Direct police academy/cadet context.','Longitudinal pre-post and quasi-experimental.','219 recruits plus 34 cadets, bounded claims.','Academy fitness and simulated use-of-force outcomes.','Verified and used within stated limits.','No integrity block; limits disclosed.','Answers active claims.','2022/2026.','Bounded Brazilian applicability.','Direct.','Bounded adaptation role.','Retains exact cited content.','Distinct current roles.','No integrity block.','Cited in both manuscripts.','Fits current wording.']
 ev=['Only supports absent INT-LOAD-ARMOR claim.','International law-enforcement studies.','Armor-load context, not current claims.','Systematic review.','16 heterogeneous studies; mean sample 22.16.','Workload/task/balance/RPE, not academy change or use-of-force.','AMSTAR 2 LOW_CONFIDENCE.','Small heterogeneous studies; no pooled causal estimate.','Effects on marksmanship/physiology uncertain.','2017.','Moderate transferability only.','No direct Brazilian validation.','Potential contextual role only.','Requires new human-approved sentence.','Review-level overlap with primary studies.','Clear as of 2026-10-03.','Direct support but uncited/HUMAN_REVIEW_PENDING.','Would require narrowing and cannot generalize.']
 c=[{'Comparison_ID':'HR009-REPL-EV-1458','Dimension_Number':i+1,'Dimension':d,'Current_Reference_Set':'EV-1481 (Ref 12) + EV-1480 (Ref 13)','Current_Evidence':cur[i],'EV1458_Evidence':ev[i],'Finding_Favors':'CURRENT' if d not in {'integrity'} else 'TIE','Source':'Canonical master; FT1 appraisal; HR001 mapping; FINAL_REFERENCE_AUDIT','Final_Classification':'KEEP_CURRENT'} for i,d in enumerate(ds)]
 wr(O/'HR009_REPLACEMENT_COMPARISON.csv',list(c[0]),c)
 x=[{'Claim_ID':'BR-ACADEMY-FITNESS','Manuscript':'Both','Section':'Physical and Academy Readiness / Aptidão e academia','Current_Wording':'Brazilian police academy fitness change; no causal component attribution.','Current_Citation':'EV-1481 / Ref 12','Current_Support':'DIRECT_FOR_ACTIVE_CLAIM','EV1458_Support':'NO_DIRECT_SUPPORT','Directness_Difference':'CURRENT_HIGHER','Certainty_Difference':'NO_REPLACEMENT_GAIN','Population_Outcome_Difference':'Brazilian recruits/academy change versus heterogeneous armor studies','Replacement_Requires_Narrowing':'YES','Replacement_Creates_Overclaim':'YES','Keep_Both_Value':'NO_ACTIVE_SENTENCE_ROLE','Decision':'KEEP_CURRENT'},{'Claim_ID':'BR-CADET-USE-OF-FORCE','Manuscript':'Both','Section':'Physical and Academy Readiness / Aptidão e academia','Current_Wording':'Supplemental martial arts associated with simulated use-of-force performance in Brazilian cadets.','Current_Citation':'EV-1480 / Ref 13','Current_Support':'DIRECT_FOR_ACTIVE_CLAIM','EV1458_Support':'NO_DIRECT_SUPPORT','Directness_Difference':'CURRENT_HIGHER','Certainty_Difference':'NO_REPLACEMENT_GAIN','Population_Outcome_Difference':'Brazilian cadets/use-of-force versus armor task synthesis','Replacement_Requires_Narrowing':'YES','Replacement_Creates_Overclaim':'YES','Keep_Both_Value':'NO_ACTIVE_SENTENCE_ROLE','Decision':'KEEP_CURRENT'},{'Claim_ID':'INT-LOAD-ARMOR','Manuscript':'Both','Section':'NOT_PRESENT_AS_SUPPORTING_SECTION','Current_Wording':'NOT PRESENT AS A SUPPORTING CLAIM IN V0.13.','Current_Citation':'No assigned v0.13 citation','Current_Support':'NOT_APPLICABLE','EV1458_Support':'DIRECT_SUPPORT_WITH_BOUNDARY','Directness_Difference':'CANDIDATE_ONLY_FOR_ABSENT_CLAIM','Certainty_Difference':'AMSTAR2_LOW_CONFIDENCE','Population_Outcome_Difference':'Heterogeneous law-enforcement armor studies','Replacement_Requires_Narrowing':'YES','Replacement_Creates_Overclaim':'YES_IF_GENERALIZED','Keep_Both_Value':'NOT_UNTIL_HUMAN_APPROVED_SENTENCE','Decision':'KEEP_CURRENT'}]
 wr(O/'HR009_CLAIM_IMPACT.csv',list(x[0]),x)
 o=[{'Evidence_ID':'EV-1458','Overlap_Status':'REVIEW_LEVEL_OVERLAP_WITH_PRIMARY_STUDIES','Current_Set_Overlap':'NO_DOCUMENTED_SAME_COHORT_WITH_EV-1481_OR_EV-1480','Double_Counting_Risk':'YES_IF_REVIEW_AND_INCLUDED_PRIMARY_STUDIES_ARE_TREATED_AS_INDEPENDENT','Decision':'DO_NOT_PROMOTE_OR_ADD','Rationale':'No active v0.13 armor claim; adding the review would inflate citations without a distinct approved role.'}];wr(O/'HR009_OVERLAP_COHORT_AUDIT.csv',list(o[0]),o)
 rec={'Review_ID':'HR-009','Evidence_ID':'EV-1458','Replacement_Relationship':'DETERMINISTIC: EV-1481; EV-1480','Final_Classification':'KEEP_CURRENT',**D,'Current_References_Retained':'EV-1481 (Ref 12); EV-1480 (Ref 13)','EV1458_Use':'Not promoted as support or replacement; no manuscript change.','Final_Reference_Freeze':'NO'};wr(O/'HR009_HUMAN_DECISION_RECORD.csv',list(rec),[rec])
 qp=A/'FINAL_HUMAN_REVIEW_QUEUE.csv';q=rd(qp)
 for r in q:
  if r['Review_ID']=='HR-009':r.update(D)
 wr(qp,list(q[0]),q);mp=A/'BATCH10_4D_MANIFEST.json';m=json.loads(mp.read_text());m['files'][qp.name]=hashlib.sha256(qp.read_bytes()).hexdigest();m.setdefault('human_adjudication_updates',{})['HR-009']={'evidence_id':'EV-1458','decision':'KEEP_CURRENT','reviewer':'Matheus Florindo de Deus','review_date':'2026-10-06','scope':'Retain EV-1481/EV-1480 claims; do not promote EV-1458.'};mp.write_text(json.dumps(m,indent=2)+'\n')
 (O/'HR009_REPORT.md').write_text('# HR-009 — EV-1458 final reference decision\n\nThe deterministic relationship is EV-1458 against EV-1481 and EV-1480. All 18 dimensions and three claim impacts favor `KEEP_CURRENT`: the current set supports active Brazilian academy/cadet claims, whereas EV-1458 supports only the absent armor-load claim. It is an AMSTAR 2 `LOW_CONFIDENCE` review of 16 heterogeneous studies and has review-level overlap with primary evidence. Matheus Florindo de Deus recorded the conditionally authorized decision on 2026-10-06. No manuscript, Zotero, CEF-v1, Claim-Ready or final-freeze action occurred.\n\nGate: `HR009_ADJUDICATION_COMPLETE`; next: `GO_HR010_HUMAN_ADJUDICATION`.\n')
if __name__=='__main__':main()
