"""BATCH 10.4H-GAP2 — deterministic, source-bounded targeted gap closure."""
import csv, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'batch10_4h_gap2'; OUT.mkdir(exist_ok=True)
def read(path):
    with (ROOT/path).open(encoding='utf-8-sig',newline='') as f: return list(csv.DictReader(f))
def write(name, fields, rows):
    with (OUT/name).open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore'); w.writeheader(); w.writerows(rows)
def main():
    extraction={r['Evidence_ID']:r for r in read('batch10_4b/ft1/artifacts/PMC100_FULL_TEXT_EXTRACTION.csv')}
    appraisal={r['Evidence_ID']:r for r in read('batch10_4b/ft1/artifacts/PMC100_APPRAISAL_LEDGER.csv')}
    integrity={r['Evidence_ID']:r for r in read('batch10_4b/ft1/artifacts/PMC100_INTEGRITY_LEDGER.csv')}
    targets=[]
    for eid,gap,purpose in [
      ('EV-0140','Nutrition / supplementation','Contradictory HIGH: lawful full-text recovery and adjudication'),
      ('EV-0052','Physical fitness / academy readiness','Contradictory HIGH: lawful full-text recovery and adjudication'),
      ('EV-1066','Physical fitness / academy readiness','Contradictory HIGH: lawful full-text recovery and adjudication'),
      ('EV-1467','Brazil evidence density','Pre-versioned Brazilian result-level rescue candidate'),
      ('EV-0076','Hydration / heat','Pre-versioned tactical heat candidate'),
      ('EV-0402','Hydration / heat','Pre-versioned firefighter hydration review candidate'),
      ('EV-0846','Hydration / heat','Pre-versioned military heat candidate')]:
        s=extraction.get(eid,{})
        targets.append({'Evidence_ID':eid,'Gap':gap,'Purpose':purpose,'Title':s.get('Title','See HIGH25 record'),'PMID':s.get('PMID',''),'PMCID':s.get('PMCID',''),'DOI':s.get('DOI',''),'Versioned_Source':s.get('Full_Text_Source','batch10_4b/ft3/HIGH25_UNRESOLVED_ACCESS.csv'),'Authorized_Universe':'YES'})
    write('GAP2_TARGET_INVENTORY.csv',list(targets[0]),targets)
    recovery=[]
    for eid,label in [('EV-0052','EV0052_LAWFUL_FULL_TEXT_UNAVAILABLE'),('EV-0140','EV0140_LAWFUL_FULL_TEXT_UNAVAILABLE'),('EV-1066','EV1066_LAWFUL_FULL_TEXT_UNAVAILABLE')]:
        s=extraction.get(eid,{})
        recovery.append({'Evidence_ID':eid,'PMID':s.get('PMID',{'EV-0052':'42489479','EV-0140':'41843415','EV-1066':'28919497'}[eid]),'DOI':s.get('DOI',{'EV-0052':'10.1519/jsc.0000000000005436','EV-0140':'10.1249/mss.0000000000003908','EV-1066':'10.1016/j.jsams.2017.08.021'}[eid]),'Identity_Validation':'PMID and DOI match versioned HIGH25 access record','Lawful_Routes_Checked':'Previously versioned PubMed/PMC, publisher and institutional/open-repository recovery audit; current official metadata recheck','Lawful_Full_Text_Status':label,'Body_Available':'NO','Scientific_Adjudication':'INSUFFICIENT_TO_ADJUDICATE','Treatment':'UNADJUDICATED_CONTRADICTORY_EVIDENCE; NOT USED AS SUPPORT','FCR_Candidate':'NO','Human_Review':'PENDING'})
    write('CONTRADICTORY_FULLTEXT_RECOVERY.csv',list(recovery[0]),recovery)
    for eid,fn in [('EV-0052','EV0052_ADJUDICATION.csv'),('EV-0140','EV0140_ADJUDICATION.csv'),('EV-1066','EV1066_ADJUDICATION.csv')]:
        r=next(x for x in recovery if x['Evidence_ID']==eid)
        row={'Evidence_ID':eid,'PMID':r['PMID'],'DOI':r['DOI'],'Full_Text_Status':r['Lawful_Full_Text_Status'],'Adjudication':'INSUFFICIENT_TO_ADJUDICATE','Result_ID':'','Source_Locator':'','Classification':'UNADJUDICATED_CONTRADICTORY_EVIDENCE','Permitted_Use':'Limitation and uncertainty only.','Prohibited_Use':'Direct/indirect support, Claim-Ready, causal inference or claim modification.','Action':'Maintain current limitation; no automatic claim or freeze change.','Human_Review':'PENDING'}
        write(fn,list(row),[row])
    brazil=[]
    s=extraction['EV-1467']; a=appraisal['EV-1467']; it=integrity['EV-1467']
    brazil.append({'Evidence_ID':'EV-1467','PMID':s['PMID'],'PMCID':s['PMCID'],'DOI':s['DOI'],'Title':s['Title'],'Brazil_Relevance':'Brazilian military police, Vila Velha, Espírito Santo','Full_Text_Provenance':'LAWFUL_PMC_XML; '+s['Full_Text_Source'],'Design':'Cross-sectional comparative study','Population':'31 military police officers: administrative n=15; tactical force n=16','Result_Location':'Results; Table 1; Tables 2–5','Screen_Outcome':'RESULT_READY_AI_PROVISIONAL','Reason':'Specific result and locator available; cross-sectional and small sample require bounded contextual use only.','Prospective_Replication':'NO','Integrity':it['Integrity_Status'],'Appraisal':a['Appraisal_Overall_AI'],'Cohort_Status':'No known overlap with current reconstruction claims from versioned metadata; final human verification pending.'})
    brazil.append({'Evidence_ID':'EV-0857','PMID':extraction['EV-0857']['PMID'],'PMCID':extraction['EV-0857']['PMCID'],'DOI':extraction['EV-0857']['DOI'],'Title':extraction['EV-0857']['Title'],'Brazil_Relevance':'No verified Brazilian setting in versioned record','Full_Text_Provenance':'LAWFUL_PMC_XML; '+extraction['EV-0857']['Full_Text_Source'],'Design':'Cross-sectional study','Population':'237 police officers across occupations','Result_Location':'Results; Tables 1–5','Screen_Outcome':'NOT_BRAZIL_ELIGIBLE','Reason':'Not a Brazil-specific source; no reclassification.','Prospective_Replication':'NO','Integrity':integrity['EV-0857']['Integrity_Status'],'Appraisal':appraisal['EV-0857']['Appraisal_Overall_AI'],'Cohort_Status':'Not applicable to Brazil-density rescue.'})
    write('BRAZIL_TARGETED_CANDIDATE_SCREEN.csv',list(brazil[0]),brazil)
    heat=[]
    heat.append({'Evidence_ID':'EV-0076','PMID':extraction['EV-0076']['PMID'],'PMCID':extraction['EV-0076']['PMCID'],'Title':extraction['EV-0076']['Title'],'Full_Text_Provenance':'LAWFUL_PMC_XML; '+extraction['EV-0076']['Full_Text_Source'],'Population':'27 healthy volunteers; not a verified tactical-service population','Design':'Secondary analysis of controlled heat-acclimation investigation','Result_Location':'Results; Figure 1','Result_Checked':'Rate-pressure product decreased day 1 to day 10 in both sexes; no sex-by-time interaction.','Screen_Outcome':'NOT_RESULT_READY_FOR_TACTICAL_HYDRATION_HEAT_CLAIM','Reason':'Heat physiology result is located but population does not meet the required tactical-compatibility criterion; no hydration outcome or field readiness outcome.','Decision':'Do not promote; retain only as screened context.'})
    heat.append({'Evidence_ID':'EV-0402','PMID':extraction['EV-0402']['PMID'],'PMCID':extraction['EV-0402']['PMCID'],'Title':extraction['EV-0402']['Title'],'Full_Text_Provenance':'LAWFUL_PMC_XML; '+extraction['EV-0402']['Full_Text_Source'],'Population':'Firefighters as narrative-review context','Design':'Narrative review','Result_Location':'Review text; no primary result packet','Result_Checked':'Review reports no firefighter randomized trials demonstrating health effects of maintained euhydration.','Screen_Outcome':'NOT_RESULT_READY','Reason':'No primary, result-level tactical hydration packet.','Decision':'No promotion.'})
    heat.append({'Evidence_ID':'EV-0846','PMID':extraction['EV-0846']['PMID'],'PMCID':extraction['EV-0846']['PMCID'],'Title':extraction['EV-0846']['Title'],'Full_Text_Provenance':'PMC record was previously classified insufficient','Population':'Military setting asserted in title/abstract only','Design':'Operational heat-acclimatization study','Result_Location':'Unavailable for full appraisal','Result_Checked':'None; prior body validation was insufficient.','Screen_Outcome':'FULL_TEXT_INSUFFICIENT','Reason':'No adequate Methods/Results available in versioned body.','Decision':'Fail closed; no promotion.'})
    write('HYDRATION_HEAT_TARGETED_SCREEN.csv',list(heat[0]),heat)
    result={'Evidence_ID':'EV-1467','Result_ID':'EV-1467-GAP2-R01','PMID':s['PMID'],'PMCID':s['PMCID'],'DOI':s['DOI'],'Title':s['Title'],'Full_Text_Source':s['Full_Text_Source'],'Source_Locator':'Results; Table 1; Tables 2–5','Population':'31 Brazilian military police officers (administrative n=15; tactical force n=16)','Design':'Cross-sectional comparative study','Exact_Result':'Weekly physical-activity time did not differ significantly between administrative (454 ± 217 min/week) and tactical-force officers (623 ± 301 min/week; p=0.0832); the groups also showed no significant differences in reported musculoskeletal discomfort.','Null_Result_Preserved':'YES','Result_Status':'EXTRACTED_FROM_PREVIOUSLY_VERSIONED_LAWFUL_FULL_TEXT','Human_Confirmation':'PENDING'}
    write('NEW_RESULT_LEVEL_EXTRACTION.csv',list(result),[result])
    locator={'Result_ID':'EV-1467-GAP2-R01','Evidence_ID':'EV-1467','Source_Type':'PMC XML full text','Source_URL':s['Full_Text_Source'],'Source_SHA256':s['Raw_XML_SHA256'],'Locator':'Results; Table 1; Tables 2–5','Locator_Validation':'Exact result text extracted from versioned full-text digest and bounded to the reported cross-sectional comparison.','Human_Confirmation':'PENDING'}
    write('NEW_RESULT_SOURCE_LOCATORS.csv',list(locator),[locator])
    claim={'Claim_ID':'RC-GAP2-BRA-MSK-01','Evidence_ID':'EV-1467','Result_ID':'EV-1467-GAP2-R01','Manuscript_Eligibility':'Brazil only','Domain':'Brazil evidence density / musculoskeletal context','AI_Provisional_Claim':'In one small cross-sectional sample of Brazilian military police officers, administrative and tactical-force groups did not differ significantly in weekly physical-activity time or reported musculoskeletal discomfort; the finding is contextual and does not establish occupational, behavioral, or preventive effects.','Source_Locator':locator['Locator'],'Population':result['Population'],'Design':result['Design'],'Certainty':'AI-provisional; JBI some concerns; human confirmation pending','Transferability':'Limited to one Espírito Santo company; no nationwide inference.','Prohibited_Inference':'No causal, prospective, preventive, readiness-score, or national-generalization claim.','Claim_Ready':'NO','Final_Reference_Promotion':'NO'}
    write('NEW_BOUNDED_CLAIMS.csv',list(claim),[claim])
    overlap={'Evidence_ID':'EV-1467','Result_ID':'EV-1467-GAP2-R01','Cohort_Identifier':'Brazilian military police, 17th Independent Company, Vila Velha, Espírito Santo','Compared_Against':'Current reconstruction claim set and versioned Brazil candidates','Overlap_Assessment':'NO_KNOWN_SHARED_COHORT_FROM_VERSIONED_METADATA','Double_Counting_Risk':'Not observed in this targeted comparison; human verification pending.','Decision':'One contextual result only; do not count as a replication.'}
    write('NEW_COHORT_OVERLAP_AUDIT.csv',list(overlap),[overlap])
    statuses=[
      {'Gap':'Nutrition / supplementation','Decision':'UNRESOLVED','Detailed_Status':'UNRESOLVED_AFTER_LAWFUL_RECOVERY','Basis':'EV-0140 remains inaccessible for full-text adjudication; no independent Brazilian direct result packet found in the versioned universe.'},
      {'Gap':'Physical fitness / academy readiness','Decision':'UNRESOLVED','Detailed_Status':'UNRESOLVED_AFTER_LAWFUL_RECOVERY','Basis':'EV-0052 and EV-1066 remain inaccessible for adjudication; no eligible prospective Brazilian replication found.'},
      {'Gap':'Hydration / heat','Decision':'UNRESOLVED','Detailed_Status':'HYDRATION_HEAT_GAP_CONFIRMED','Basis':'Three screened records produced no tactical-population, hydration/heat result packet meeting all criteria.'},
      {'Gap':'Brazil evidence density','Decision':'PARTIAL','Detailed_Status':'PARTIALLY_CLOSED','Basis':'EV-1467 adds one independent, Brazil-specific, located cross-sectional null-result packet; density remains insufficient for broad Brazil claims.'}]
    write('GAP_STATUS_FINAL.csv',list(statuses[0]),statuses)
    write('FCR_CANDIDATES.csv',['Evidence_ID','FCR_Candidate','Reason','Action'],[{'Evidence_ID':'','FCR_Candidate':'NO','Reason':'No recovered contradictory full text was adjudicated and the sole new claim is bounded, AI-provisional, and does not alter CEF-v1.','Action':'CEF-v1 unchanged.'}])
    gapmatrix=read('batch10_4h_gap/UPDATED_RECONSTRUCTION_GAP_MATRIX.csv')
    mapx={x['Gap']:x for x in statuses}
    for r in gapmatrix:
        key=r['Domain']
        if key in mapx:
            x=mapx[key]; r['Gap']='YES'; r['Action']='REMOVE_DOMAIN' if x['Decision']=='UNRESOLVED' else 'DISCUSSION_ONLY'; r['Evidence_Available']=x['Basis']
            r['Result_ID_Count']='1' if key=='Brazil evidence density' else '0'; r['Independent_Cohort_Count']='1' if key=='Brazil evidence density' else '0'
    write('UPDATED_RECONSTRUCTION_GAP_MATRIX.csv',list(gapmatrix[0]),gapmatrix)
    report='''# BATCH 10.4H-GAP2 — targeted final gap closure\n\n## Gate\n\n`TARGETED_GAP_CLOSURE_INSUFFICIENT`\n\n## Scope and controls\n\nOnly the four documented gaps and records already in the versioned universe were assessed. No broad search, Zotero write, reference freeze, CEF-v1 change, Architecture A restoration, or manuscript edit occurred.\n\n## Results\n\n- Contradictory targets: 3/3 identity and lawful-access records reviewed; 0/3 lawful full texts recovered; 0/3 scientifically adjudicated. EV-0052, EV-0140 and EV-1066 remain unadjudicated contradictory evidence and cannot support claims.\n- Brazil rescue: 2 candidates screened. EV-1467 supplied one located, Brazilian, cross-sectional null-result packet; it is AI-provisional, context-only and not a prospective replication. EV-0857 was not Brazil-specific.\n- Hydration/heat: 3 candidates screened; 0 result-ready packets. EV-0076 has a located heat-acclimation result but its healthy-volunteer population does not meet the tactical-population criterion; EV-0402 is a narrative review; EV-0846 remains source-insufficient.\n- New result IDs / bounded claims: 1 / 1. Human review remains pending; no Claim-Ready or final-reference promotion occurred.\n\n## Gap decisions\n\n| Gap | Decision |\n|---|---|\n| Nutrition / supplementation | UNRESOLVED |\n| Physical fitness / academy readiness | UNRESOLVED |\n| Hydration / heat | UNRESOLVED |\n| Brazil evidence density | PARTIAL |\n\nThe remaining three structural gaps prevent a reconstruction retry. The appropriate next technical step is to remove or explicitly narrow the unresolved domains in the evidence-first architecture; it is not a new broad search.\n'''
    (OUT/'BATCH10_4H_GAP2_REPORT.md').write_text(report,encoding='utf-8')
    files=[p for p in OUT.iterdir() if p.is_file() and p.name!='BATCH10_4H_GAP2_MANIFEST.json']
    manifest={'batch':'BATCH 10.4H-GAP2','base_commit':'35c59cedf498a894c3c62c548f6f40c6ee8c221e','gate':'TARGETED_GAP_CLOSURE_INSUFFICIENT','contradictory_targets':3,'contradictory_full_texts_recovered':0,'contradictory_records_adjudicated':0,'brazil_candidates_assessed':2,'independent_brazil_result_ready_sources_added':1,'hydration_heat_candidates_assessed':3,'hydration_heat_result_ready_packets':0,'new_result_ids':1,'new_bounded_claims':1,'forced_semantic_links':0,'blocked_evidence_used':0,'source_insufficient_evidence_promoted':0,'cohort_double_counting':0,'rejected_pmcid_reused':0,'CEF_v1_silently_changed':0,'Zotero_changed':0,'v015_changed':0,'human_review':'PENDING','deterministic_regeneration':'python analysis/build_batch10_4h_gap2.py','artifact_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
    (OUT/'BATCH10_4H_GAP2_MANIFEST.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__': main()
