"""BATCH 10.4H-B2 — deterministic scope-pruning blueprint; no manuscript mutation."""
import csv, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'batch10_4h_b2'; OUT.mkdir(exist_ok=True)
def read(path):
 with (ROOT/path).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def write(name,fields,rows):
 with (OUT/name).open('w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
def main():
 base=read('batch10_4g/NEW_CLAIM_LIBRARY.csv')
 gap=read('batch10_4h_gap/GAP_CLOSURE_NEW_CLAIMS.csv')
 ev1467=read('batch10_4h_gap2/NEW_BOUNDED_CLAIMS.csv')[0]
 # Exact disposition across the final narrowed B2 architecture; all claims remain AI-provisional.
 rules={
  'RC-INT-SLEEP-01':('KEEP_SUPPORTING','Sleep/caffeine is task-dependent and International-only; one review supports a bounded supporting section, not broad readiness advice.','International'),
  'RC-BRA-CVD-01':('KEEP','Direct, result-located Brazilian medical-readiness evidence; International use remains transferability context only.','Both'),
  'RC-BRA-MSK-01':('KEEP_CONTEXTUAL','Weak cross-sectional discrimination; retain only to delimit musculoskeletal inference.','Brazil'),
  'RC-BRA-SHOOT-01':('KEEP_SUPPORTING','Null result preserves tactical-performance specificity.','Both'),
  'RC-BRA-SHOOT-02':('KEEP_SUPPORTING','Null correlations are useful, but cohort overlaps RC-BRA-SHOOT-01 and count as one independent cohort.','Both'),
  'RC-BRA-APH-01':('KEEP_SUPPORTING','Descriptive tactical-medicine record evidence; no training or patient-outcome inference.','Brazil'),
  'RC-BRA-ORG-01':('KEEP_SUPPORTING','Null implementation evaluation is retained for organizational context.','Brazil'),
  'RC-BRA-IMPL-01':('KEEP_CONTEXTUAL','Documentary institutional proposal, not effectiveness evidence.','Brazil'),
  'RC-BRA-MED-01':('KEEP','Large Paraná occupational cohort supports a bounded medical non-readiness section.','Brazil'),
  'RC-GAP-INT-NUTR-01':('REMOVE_FROM_MANUSCRIPT','Nutrition/supplementation is an unresolved core gap and EV-0140 remains unadjudicated contradictory evidence.','None'),
  'RC-GAP-INT-NUTR-02':('REMOVE_FROM_MANUSCRIPT','Nutrition/supplementation is removed from core scope.','None'),
  'RC-GAP-INT-PHYS-01':('REMOVE_FROM_MANUSCRIPT','Physical fitness/academy readiness is an unresolved core gap with unresolved contradictory HIGH evidence.','None'),
  'RC-GAP-INT-MEAS-01':('REMOVE_FROM_MANUSCRIPT','Physical fitness/academy readiness is removed from core scope.','None'),
  'RC-GAP2-BRA-MSK-01':('KEEP_CONTEXTUAL','Located Brazilian null result; small cross-sectional sample, contextual only.','Brazil')}
 allraw=[]
 for r in base+gap:
  cid=r.get('Reconstruction_Claim_ID'); allraw.append({'Claim_ID':cid,'Evidence_ID':r['Evidence_ID'],'Result_ID':r['Result_ID'],'Claim':r['Exact_Proposed_Claim'],'Domain':r['Proposed_Section'],'Locator':r['Source_Locator'],'Population':r['Population'],'Design':r['Design'],'Boundary':r.get('Claim_Boundary','See upstream source packet')})
 allraw.append({'Claim_ID':ev1467['Claim_ID'],'Evidence_ID':ev1467['Evidence_ID'],'Result_ID':ev1467['Result_ID'],'Claim':ev1467['AI_Provisional_Claim'],'Domain':ev1467['Domain'],'Locator':ev1467['Source_Locator'],'Population':ev1467['Population'],'Design':ev1467['Design'],'Boundary':ev1467['Prohibited_Inference']})
 claims=[]
 for r in allraw:
  disp,reason,eligible=rules[r['Claim_ID']]
  claims.append({**r,'B2_Disposition':disp,'B2_Manuscript_Eligibility':eligible,'Disposition_Rationale':reason,'Human_Review':'PENDING' if disp!='REMOVE_FROM_MANUSCRIPT' else 'NOT_REQUIRED_FOR_REMOVAL','Claim_Ready':'NO','Final_Reference_Promotion':'NO'})
 write('FINAL_B2_CLAIM_LIBRARY.csv',list(claims[0]),claims)
 resultmatrix=[]
 for r in claims:
  resultmatrix.append({'Claim_ID':r['Claim_ID'],'Evidence_ID':r['Evidence_ID'],'Result_ID':r['Result_ID'],'Source_Locator':r['Locator'],'Domain':r['Domain'],'B2_Disposition':r['B2_Disposition'],'Use':'No use' if r['B2_Disposition']=='REMOVE_FROM_MANUSCRIPT' else 'AI-provisional and bounded','Claim_Boundary':r['Boundary'],'Chain_Complete':'YES','Human_Review':r['Human_Review']})
 write('FINAL_B2_CLAIM_RESULT_MATRIX.csv',list(resultmatrix[0]),resultmatrix)
 domains=[
 {'Domain':'Medical / cardiometabolic readiness','Core_Status':'CORE','International_Role':'Transferability context only','Brazil_Role':'Core evidence section','Claims':'RC-BRA-CVD-01; RC-BRA-MED-01','Evidence_Density':'2 result-located sources; 2 independent cohorts','Decision':'KEEP'},
 {'Domain':'Task-specific shooting / tactical-performance boundaries','Core_Status':'SUPPORTING','International_Role':'Boundary example','Brazil_Role':'Supporting evidence section','Claims':'RC-BRA-SHOOT-01; RC-BRA-SHOOT-02','Evidence_Density':'2 publications; 1 overlapping cohort; null findings retained','Decision':'KEEP_WITH_NO_DOUBLE_COUNTING'},
 {'Domain':'Sleep / caffeine','Core_Status':'SUPPORTING','International_Role':'Bounded supporting section only','Brazil_Role':'Not used','Claims':'RC-INT-SLEEP-01','Evidence_Density':'1 systematic review/meta-analysis','Decision':'KEEP_INTERNATIONAL_ONLY'},
 {'Domain':'Tactical medicine / APH','Core_Status':'SUPPORTING','International_Role':'Not used','Brazil_Role':'Supporting descriptive section','Claims':'RC-BRA-APH-01','Evidence_Density':'1 state record-review source','Decision':'KEEP_BOUNDED'},
 {'Domain':'Organizational / implementation context','Core_Status':'SUPPORTING_CONTEXTUAL','International_Role':'Not used','Brazil_Role':'Supporting/contextual section','Claims':'RC-BRA-ORG-01; RC-BRA-IMPL-01','Evidence_Density':'2 setting-specific sources; one null evaluation, one documentary case','Decision':'KEEP_BOUNDED'},
 {'Domain':'Musculoskeletal context','Core_Status':'CONTEXTUAL','International_Role':'Not used','Brazil_Role':'Context/limitations only','Claims':'RC-BRA-MSK-01; RC-GAP2-BRA-MSK-01','Evidence_Density':'2 cross-sectional localized sources; no preventive inference','Decision':'KEEP_CONTEXTUAL'},
 {'Domain':'Nutrition / supplementation','Core_Status':'REMOVED_FROM_CORE_SCOPE','International_Role':'Limitations/future research only','Brazil_Role':'Limitations/future research only','Claims':'RC-GAP-INT-NUTR-01; RC-GAP-INT-NUTR-02','Evidence_Density':'Insufficient after targeted closure; EV-0140 unadjudicated contradictory HIGH','Decision':'REMOVE'},
 {'Domain':'Physical fitness / academy readiness','Core_Status':'REMOVED_FROM_CORE_SCOPE','International_Role':'Evidence-gap discussion only','Brazil_Role':'Evidence-gap discussion only','Claims':'RC-GAP-INT-PHYS-01; RC-GAP-INT-MEAS-01','Evidence_Density':'Insufficient after targeted closure; EV-0052 and EV-1066 unresolved contradictory HIGH','Decision':'REMOVE'},
 {'Domain':'Hydration / heat','Core_Status':'REMOVED_FROM_CORE_SCOPE','International_Role':'Structural-gap statement only','Brazil_Role':'Structural-gap statement only','Claims':'None','Evidence_Density':'No reconstruction-ready result packet','Decision':'REMOVE'}]
 write('FINAL_DOMAIN_SCOPE_MATRIX.csv',list(domains[0]),domains)
 refs=[]
 # planned working-set rows are strictly mapped to retained claims, no freeze/promotion.
 for r in claims:
  if r['B2_Disposition']=='REMOVE_FROM_MANUSCRIPT': continue
  scope=r['B2_Manuscript_Eligibility']
  refs.append({'Evidence_ID':r['Evidence_ID'],'Claim_ID':r['Claim_ID'],'Result_ID':r['Result_ID'],'International_Planned_Use':'YES' if scope in ('Both','International') else 'NO','Brazil_Planned_Use':'YES' if scope in ('Both','Brazil') else 'NO','Working_Role':r['B2_Disposition'],'Reference_Status':'WORKING_ONLY_NOT_FROZEN','Reason':r['Disposition_Rationale'],'Human_Review':'PENDING'})
 write('FINAL_B2_WORKING_REFERENCE_SET.csv',list(refs[0]),refs)
 density=[
 {'Manuscript':'International','Core_Claims':1,'Supporting_Claims':3,'Contextual_Claims':0,'Independent_Cohorts_or_Source_Families':3,'Result_IDs':4,'Unique_Evidence_IDs':4,'Direct_Evidence':'1 sleep/caffeine review; task-boundary examples are indirect to broad readiness','Indirect_Evidence':'Cardiometabolic and Brazilian shooting transferability examples','Narrative_Density':'Sufficient for a short evidence-informed integrative synthesis focused on evidence boundaries and transferability.','Status':'B2_VIABLE_SHORT_FORM'},
 {'Manuscript':'Brazil','Core_Claims':2,'Supporting_Claims':4,'Contextual_Claims':3,'Independent_Cohorts_or_Source_Families':7,'Result_IDs':9,'Unique_Evidence_IDs':9,'Direct_Evidence':'Brazilian PMDF, Paraná, shooting, APH, organizational and musculoskeletal sources','Indirect_Evidence':'International sleep/caffeine is excluded from Brazil working set','Narrative_Density':'Sufficient for a bounded full integrative manuscript with three substantive sections.','Status':'B2_VIABLE_FULL_MANUSCRIPT'}]
 write('FINAL_B2_EVIDENCE_DENSITY.csv',list(density[0]),density)
 cohorts=[
 {'Cohort_Family':'CF-BR-PMES-CFO-2023-01','Evidence_IDs':'EV-1473; EV-1474','Claims':'RC-BRA-SHOOT-01; RC-BRA-SHOOT-02','Independent_Cohort_Count':1,'Control':'Do not represent as independent replications.'},
 {'Cohort_Family':'PMDF_OLDER_MALE_OFFICERS','Evidence_IDs':'EV-1463','Claims':'RC-BRA-CVD-01','Independent_Cohort_Count':1,'Control':'Cross-sectional, sampled-setting only.'},
 {'Cohort_Family':'PARANA_OCCUPATIONAL_COHORT','Evidence_IDs':'EV-1484','Claims':'RC-BRA-MED-01','Independent_Cohort_Count':1,'Control':'No national-prevalence inference.'},
 {'Cohort_Family':'PMES_VILA_VELHA_17TH_COMPANY','Evidence_IDs':'EV-1467','Claims':'RC-GAP2-BRA-MSK-01','Independent_Cohort_Count':1,'Control':'Cross-sectional context only.'}]
 write('FINAL_B2_INDEPENDENT_COHORT_COUNT.csv',list(cohorts[0]),cohorts)
 evrow={'Evidence_ID':'EV-1467','Result_ID':'EV-1467-GAP2-R01','Locator':'Results; Table 1; Tables 2–5','Population':'31 Brazilian military police officers: administrative n=15; tactical n=16','Design':'Cross-sectional comparative study','Permitted_Claim':'In this sample, weekly physical-activity time and reported musculoskeletal discomfort did not differ significantly between sectors.','Classification':'CONTEXTUAL_CLAIM','Prohibited_Inference':'Causal sector effect; prospective readiness prediction; Brazil prevalence; occupational-performance benefit; academy-readiness claim; equivalent health impact.','Core_Claim':'NO','Claim_Ready':'NO','Human_Review':'PENDING'}
 write('EV1467_CLAIM_INTEGRATION.csv',list(evrow),[evrow])
 removed=[{'Domain':'Nutrition / supplementation','Status':'REMOVE_FROM_CORE_SCOPE','Evidence_Gap':'EV-0140 unadjudicated contradictory HIGH; no direct Brazil evidence density.','Permitted_Remnant':'Limitations / future research only','Core_Use':'NO'}, {'Domain':'Physical fitness / academy readiness','Status':'REMOVE_FROM_CORE_SCOPE','Evidence_Gap':'EV-0052 and EV-1066 unadjudicated contradictory HIGH; no prospective Brazilian replication.','Permitted_Remnant':'Contextual evidence gap / future research only','Core_Use':'NO'}, {'Domain':'Hydration / heat','Status':'REMOVE_FROM_CORE_SCOPE','Evidence_Gap':'No eligible reconstruction-ready, result-located tactical packet.','Permitted_Remnant':'Structural evidence gap only','Core_Use':'NO'}]
 write('REMOVED_DOMAIN_JUSTIFICATION.csv',list(removed[0]),removed)
 reassess=[
 {'Architecture':'A','Status':'EXCLUDED','Reason':'Previously excluded; no restoration authorized.'},
 {'Architecture':'B2 — single narrowed integrative manuscript','International':'B2_VIABLE_SHORT_FORM','Brazil':'B2_VIABLE_FULL_MANUSCRIPT','Decision':'PREFERRED','Reason':'Shared evidence-boundary framing is coherent while allowing asymmetric manuscript scope.'},
 {'Architecture':'C — split manuscripts','International':'POSSIBLE_FUTURE_FORMAT_OPTION','Brazil':'POSSIBLE_FUTURE_FORMAT_OPTION','Decision':'NOT_PREFERRED_NOW','Reason':'Split does not improve evidence density; it would amplify the sparse International set.'}]
 write('B2_VS_C_REASSESSMENT.csv',list(reassess[0]),reassess)
 viability=[{'Manuscript':'International','Status':'B2_VIABLE_SHORT_FORM','Central_Question':'What can selected, result-located operational-readiness evidence support, and where do transferability boundaries begin?','Substantive_Sections':2,'Conclusion':'A short, evidence-informed integrative synthesis is viable; a broad full readiness manuscript is not.'}, {'Manuscript':'Brazil','Status':'B2_VIABLE_FULL_MANUSCRIPT','Central_Question':'What do result-located Brazilian public-safety sources support about bounded medical readiness, task-specific performance, tactical medicine and implementation context?','Substantive_Sections':3,'Conclusion':'A narrowly scoped full evidence-informed integrative manuscript is viable.'}]
 write('B2_MANUSCRIPT_VIABILITY.csv',list(viability[0]),viability)
 hq=[]
 for r in claims:
  if r['B2_Disposition']!='REMOVE_FROM_MANUSCRIPT': hq.append({'Review_Item':r['Claim_ID'],'Type':'NEW_CLAIM' if r['Claim_ID']=='RC-GAP2-BRA-MSK-01' else 'ROLE_OR_SCOPE_CONFIRMATION','Requested_Human_Decision':'Confirm B2 use, role and wording boundary','Status':'PENDING','No_Human_Decision_Recorded':'YES'})
 hq += [{'Review_Item':'International objective and short-form status','Type':'OBJECTIVE_CHANGE','Requested_Human_Decision':'Confirm narrowed International objective','Status':'PENDING','No_Human_Decision_Recorded':'YES'}, {'Review_Item':'Brazil objective and full-manuscript status','Type':'OBJECTIVE_CHANGE','Requested_Human_Decision':'Confirm narrowed Brazil objective','Status':'PENDING','No_Human_Decision_Recorded':'YES'}]
 write('B2_HUMAN_REVIEW_QUEUE.csv',list(hq[0]),hq)
 write('B2_FCR_CANDIDATES.csv',['FCR_Candidate','Status','Reason','Action'],[{'FCR_Candidate':'NONE','Status':'NO','Reason':'Scope pruning and working blueprint do not alter CEF-v1 or frozen wording.','Action':'CEF-v1 unchanged.'}])
 intl='''# INTERNATIONAL B2 — FINAL NARROWED BLUEPRINT\n\n## Title\n\n**Evidence boundaries and transferability in selected operational-readiness domains: an evidence-informed integrative synthesis**\n\n## Central question and objective\n\nWhat can result-located evidence in selected operational-readiness domains support, and where must claims stop because of transferability and evidence-density limits? The objective is to synthesize bounded sleep/caffeine, cardiometabolic-transferability and task-specific performance evidence without presenting a global readiness model.\n\n## Article type\n\nEvidence-informed integrative synthesis; not a systematic review. The `PROPOSED SYNTHESIS FRAMEWORK — NOT YET VALIDATED` remains a conceptual organizer only.\n\n## Claims and structure\n\n- Supporting: task-dependent sleep/caffeine evidence; cardiometabolic transferability context; shooting null-result boundaries.\n- Sections: evidence-boundary framing; selected domain evidence and transferability; limitations and future validation.\n- Removed from core: nutrition/supplementation, physical fitness/academy readiness, hydration/heat.\n\n## Density and viability\n\nFour result IDs across three independent source families support a **short form** (estimated 2,500–3,500 words), not a broad full manuscript. All citations remain working-only and human review is pending.\n\n## Limitations\n\nUnadjudicated contradictory evidence (EV-0052, EV-0140, EV-1066) is not support. No global readiness score, framework validation, causal inference or Brazil-generalization is permitted.\n'''
 brazilmd='''# BRAZIL B2 — FINAL NARROWED BLUEPRINT\n\n## Title\n\n**Evidence boundaries in Brazilian public-safety readiness: a bounded evidence-informed integrative synthesis**\n\n## Central question and objective\n\nWhat do result-located Brazilian public-safety sources support about medical readiness, task-specific performance, tactical medicine and organizational context? The objective is to synthesize the available evidence while retaining null findings, cohort limits and institutional transferability constraints.\n\n## Article type\n\nEvidence-informed integrative synthesis; not a systematic review. The `PROPOSED SYNTHESIS FRAMEWORK — NOT YET VALIDATED` is conceptual only.\n\n## Claims and structure\n\n- Core: bounded cardiometabolic surveillance context; medical non-readiness associations.\n- Supporting: shooting null findings, tourniquet-use record review, Escola Segura null evaluation.\n- Contextual: institutional implementation case and two cross-sectional musculoskeletal observations, including EV-1467.\n- Sections: medical readiness; task-specific and tactical-medicine evidence; organizational/implementation context; limitations and future validation.\n- Removed from core: nutrition/supplementation, physical fitness/academy readiness, hydration/heat.\n\n## Density and viability\n\nNine result IDs across seven independent source families support a **bounded full manuscript** (estimated 3,000–4,000 words). Citations are working-only and human review remains pending.\n\n## Limitations\n\nEvidence is heterogeneous and mostly observational or descriptive; the shooting publications overlap in one cohort; no national prevalence, causal, intervention-effect, framework-validation or global-readiness inference is permitted.\n'''
 (OUT/'INTERNATIONAL_B2_BLUEPRINT.md').write_text(intl,encoding='utf-8'); (OUT/'BRAZIL_B2_BLUEPRINT.md').write_text(brazilmd,encoding='utf-8')
 report='''# BATCH 10.4H-B2 — Architecture B scope pruning\n\n## Gate\n\n`ARCHITECTURE_B2_SCOPE_PRUNING_PASS`\n\n## Decision\n\nThe three unresolved domains are removed from core scope: nutrition/supplementation, physical fitness/academy readiness and hydration/heat. They may appear only as limitations, structural gaps or future-research needs. EV-0052, EV-0140 and EV-1066 remain unadjudicated contradictory evidence and have zero support use.\n\n## Viability\n\n- **International:** `B2_VIABLE_SHORT_FORM` — four retained result IDs across three independent source families, suitable for an evidence-boundary and transferability synthesis.\n- **Brazil:** `B2_VIABLE_FULL_MANUSCRIPT` — nine retained result IDs across seven independent source families, suitable for a bounded evidence-informed integrative synthesis.\n\nEV-1467 is incorporated only as a contextual, small, cross-sectional Brazilian null-result packet. No manuscript, Zotero, CEF-v1 or frozen reference set was changed. Human review remains pending.\n\n## Next gate\n\n`BATCH 10.4H-R — EVIDENCE-FIRST v0.15 RECONSTRUCTION RETRY` may proceed only with these blueprints and their stated limits.\n'''
 (OUT/'BATCH10_4H_B2_REPORT.md').write_text(report,encoding='utf-8')
 fs=[p for p in OUT.iterdir() if p.is_file() and p.name!='BATCH10_4H_B2_MANIFEST.json']
 m={'batch':'BATCH 10.4H-B2','base_commit':'c6a42b65d145ab5d7205bdee4a81c08eeeb2210a','gate':'ARCHITECTURE_B2_SCOPE_PRUNING_PASS','international_status':'B2_VIABLE_SHORT_FORM','brazil_status':'B2_VIABLE_FULL_MANUSCRIPT','claims_total':len(claims),'claims_retained':sum(r['B2_Disposition']!='REMOVE_FROM_MANUSCRIPT' for r in claims),'claims_removed':sum(r['B2_Disposition']=='REMOVE_FROM_MANUSCRIPT' for r in claims),'unresolved_domains_promoted_to_core':0,'hydration_claims_without_result_id':0,'nutrition_claims_relying_on_EV0140':0,'fitness_core_claims_relying_on_EV0052_or_EV1066':0,'source_insufficient_evidence_promoted':0,'blocked_evidence_support':0,'cohort_double_counting':0,'null_suppression':0,'framework_validation_inflation':0,'CEF_v1_unauthorized_change':0,'Zotero_changed':0,'v015_changed':0,'human_review':'PENDING','deterministic_regeneration':'python analysis/build_batch10_4h_b2.py','artifact_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in fs}}
 (OUT/'BATCH10_4H_B2_MANIFEST.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__':main()
